Repository hiero-ledger/hiero-mirror-node, pull requests merged in 2019-12, with the labels that each got.

#418 Add missing response codes
  hedera-mirror-coverage/pom.xml
  hedera-mirror-importer/pom.xml
  hedera-mirror-importer/src/main/resources/db/migration/V1.14__response_codes.sql
  hedera-mirror-importer/src/main/resources/db/migration/V1.16__cryptotransferlist_realm_num.sql
  hedera-mirror-rest/package-lock.json
  hedera-mirror-rest/package.json
  hedera-mirror-rest/pom.xml
  pom.xml
Labels: P1, bug, database

#419 Bug/exp overflow master
  docs/troubleshooting.md
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/Entities.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/util/Utility.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/RecordFileLoggerCryptoTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/RecordFileLoggerFileTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/util/UtilityTest.java
  hedera-mirror-rest/__tests__/integration.test.js
  hedera-mirror-rest/__tests__/integration_test_data.json
  hedera-mirror-rest/__tests__/specs/accounts-01-no-args.spec.json
  hedera-mirror-rest/__tests__/utils.test.js
Labels: P1, bug, parser

#420 Bump version for v0.4.1
  pom.xml
  rest-api/package-lock.json
  rest-api/package.json
Labels: P1, enhancement, process

#423 Extract common plugin config to parent pom
  .gitignore
  hedera-mirror-coverage/pom.xml
  hedera-mirror-importer/pom.xml
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/util/ShutdownHelper.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/downloader/AbstractDownloaderTest.java
  hedera-mirror-rest/.dockerignore
  hedera-mirror-rest/.gitignore
  hedera-mirror-rest/.maven-dockerignore
  hedera-mirror-rest/.npmignore
  hedera-mirror-rest/__acceptancetests__/acceptancetest_utils.js
  hedera-mirror-rest/monitoring/monitor_apis/monitortest_utils.js
  hedera-mirror-rest/package.json
  hedera-mirror-rest/pom.xml
  pom.xml
Labels: P3, enhancement, process

#417 HCS GRPC Stub
  docs/configuration.md
  hedera-mirror-coverage/pom.xml
  hedera-mirror-grpc/pom.xml
  hedera-mirror-grpc/scripts/deploy.sh
  hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/MirrorGrpcApplication.java
  hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/service/ConsensusService.java
  hedera-mirror-grpc/src/main/resources/application.yml
  hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/service/ConsensusServiceTest.java
  hedera-mirror-grpc/src/test/resources/application-default.yml
  hedera-mirror-importer/pom.xml
  hedera-mirror-protobuf/pom.xml
  hedera-mirror-protobuf/src/main/proto/com/hedera/mirror/api/proto/ConsensusService.proto
  hedera-mirror-rest/package.json
  hedera-mirror-rest/pom.xml
  pom.xml
Labels: P1, enhancement, hcs

#425 Merge master into HCS
  .gitignore
  docs/troubleshooting.md
  hedera-mirror-coverage/pom.xml
  hedera-mirror-importer/pom.xml
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/Entities.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/util/ShutdownHelper.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/util/Utility.java
  hedera-mirror-importer/src/main/resources/db/migration/V1.14__response_codes.sql
  hedera-mirror-importer/src/main/resources/db/migration/V1.16__cryptotransferlist_realm_num.sql
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/downloader/AbstractDownloaderTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/RecordFileLoggerCryptoTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/RecordFileLoggerFileTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/util/UtilityTest.java
  hedera-mirror-rest/.dockerignore
  hedera-mirror-rest/.gitignore
  hedera-mirror-rest/.maven-dockerignore
  hedera-mirror-rest/.npmignore
  hedera-mirror-rest/__acceptancetests__/acceptancetest_utils.js
  hedera-mirror-rest/__tests__/integration.test.js
  hedera-mirror-rest/__tests__/integration_test_data.json
  hedera-mirror-rest/__tests__/specs/accounts-01-no-args.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-02-specific-id.spec.json
  hedera-mirror-rest/__tests__/utils.test.js
  hedera-mirror-rest/accounts.js
  hedera-mirror-rest/monitoring/monitor_apis/monitortest_utils.js
  hedera-mirror-rest/package-lock.json
  hedera-mirror-rest/pom.xml
  hedera-mirror-rest/transactions.js
  pom.xml
Labels: P2, enhancement, hcs, process

#428 Store transaction bytes (optional)
  docs/configuration.md
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Transaction.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/RecordFileLogger.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/RecordFileParser.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/RecordParserProperties.java
  hedera-mirror-importer/src/main/resources/db/migration/V1.17__transaction_bytes.sql
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/AbstractRecordFileLoggerTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/RecordFileLoggerCryptoTest.java
Labels: P3, database, enhancement

#408 Update DB to support HCS topic message
  hedera-mirror-importer/pom.xml
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Entities.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/TopicMessage.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/TopicMessageRepository.java
  hedera-mirror-importer/src/main/resources/db/migration/V1.17__hcs_support.sql
  hedera-mirror-importer/src/main/resources/db/scripts/cleanup.sql
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/repository/EntityRepositoryTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/repository/TopicMessageRepositoryTest.java
Labels: P1, database, hcs

#436 Import HCS transactions
  docs/troubleshooting.md
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Entities.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/Entities.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/RecordFileLogger.java
  hedera-mirror-importer/src/main/resources/db/migration/V1.17.0__hcs_support.sql
  hedera-mirror-importer/src/main/resources/db/migration/V1.17.1__f_entity_create.sql
  hedera-mirror-importer/src/main/resources/db/migration/V1.17__hcs_support.sql
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/KeyConverter.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/TestUtils.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/TopicIdConverter.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/AbstractRecordFileLoggerTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/EntitiesTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/RecordFileLoggerContractTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/RecordFileLoggerTopicTest.java
Labels: P1

#441 Add demo bucket as default
  README.md
  docker-compose.yml
  docs/configuration.md
  docs/installation.md
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/MirrorProperties.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/MirrorNodeConfiguration.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/HederaNetwork.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/CommonDownloaderProperties.java
  hedera-mirror-importer/src/main/resources/addressbook/demo
Labels: P1, downloader, enhancement

#445 Build hedera-mirror-protobuf artifact with target of Java 8
  hedera-mirror-protobuf/pom.xml
Labels: P1, enhancement, hcs, process

#438 HCS Topic Listener
  hedera-mirror-grpc/pom.xml
  hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/converter/LongToInstantDeserializer.java
  hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/domain/TopicMessage.java
  hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/domain/TopicMessageFilter.java
  hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/listener/NotifyingTopicListener.java
  hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/listener/TopicListener.java
  hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/service/ConsensusService.java
  hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/service/TopicMessageServiceImpl.java
  hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/domain/DomainBuilder.java
  hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/listener/NotifyingTopicListenerTest.java
  hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/repository/TopicMessageRepositoryTest.java
  hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/service/ConsensusServiceTest.java
  hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/service/TopicMessageServiceTest.java
  lombok.config
Labels: P1, enhancement, hcs

#447 Fix deploy script bug. Update version to 0.5.0-rc1
  hedera-mirror-coverage/pom.xml
  hedera-mirror-importer/pom.xml
  hedera-mirror-importer/scripts/deploy.sh
  hedera-mirror-rest/package-lock.json
  hedera-mirror-rest/package.json
  hedera-mirror-rest/pom.xml
  pom.xml
Labels: P1, bug, process

#446 HCS fix deploy script and service files. Update version to 0.1.0-rc1
  .circleci/config.yml
  hedera-mirror-coverage/pom.xml
  hedera-mirror-grpc/pom.xml
  hedera-mirror-grpc/scripts/deploy.sh
  hedera-mirror-importer/pom.xml
  hedera-mirror-importer/scripts/deploy.sh
  hedera-mirror-importer/scripts/hedera-mirror-importer.service
  hedera-mirror-protobuf/pom.xml
  hedera-mirror-rest/package-lock.json
  hedera-mirror-rest/package.json
  hedera-mirror-rest/pom.xml
  pom.xml
Labels: P1, bug, hcs

#449 Adopt insert instead of update for v1.16 db migration. Avoids temp_fi…
  hedera-mirror-importer/src/main/resources/db/migration/V1.16__cryptotransferlist_realm_num.sql
Labels: P1, bug, database

#443 Update log message alerting rules
  docs/operations.md
  docs/troubleshooting.md
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/NetworkAddressBook.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/PendingDownload.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/event/EventStreamFileParser.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/RecordFileLogger.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/RecordFileParser.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/util/ShutdownHelper.java
Labels: P1, documentation, ops

#456 Add a polling topic listener
  docs/configuration.md
  hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/listener/CompositeTopicListener.java
  hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/listener/ListenerProperties.java
  hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/listener/PollingTopicListener.java
  hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/service/TopicMessageServiceImpl.java
  hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/listener/AbstractTopicListenerTest.java
  hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/listener/NotifyingTopicListenerTest.java
  hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/listener/PollingTopicListenerTest.java
  hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/service/TopicMessageServiceTest.java
  hedera-mirror-grpc/src/test/resources/application-default.yml
Labels: P1, enhancement, hcs

#460 Fix NoSuchMethodError parsing HCS transactions
  docker-compose.yml
  docs/installation.md
  hedera-mirror-grpc/scripts/db/init.sh
  hedera-mirror-importer/pom.xml
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Entities.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/RecordFileParser.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/util/DatabaseUtilities.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/util/Utility.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/util/UtilityTest.java
  pom.xml
Labels: P1, bug, hcs, parser

#398 Test data generator + Performance tests for REST API (#282)
  .circleci/config.yml
  README.md
  docs/images/rest_api_perf_test_architecture.png
  docs/images/rest_api_perf_test_migration.png
  docs/testing.md
  hedera-mirror-datagenerator/docs/README.md
  hedera-mirror-datagenerator/docs/data-generator-future.png
  hedera-mirror-datagenerator/docs/data-generator.png
  hedera-mirror-datagenerator/pom.xml
  hedera-mirror-datagenerator/run.sh
  hedera-mirror-datagenerator/scripts/load_data.sql
  hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/DataGenerator.java
  hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/DataGeneratorProperties.java
  hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/common/CryptoTransactionProperties.java
  hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/common/EntityManager.java
  hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/common/FileTransactionProperties.java
  hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/common/TransactionGenerator.java
  hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/common/TransactionGeneratorProperties.java
  hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/domain/DomainDriver.java
  hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/domain/generators/entity/EntityGenerator.java
  hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/domain/generators/transaction/CryptoTransactionGenerator.java
  hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/domain/generators/transaction/DomainTransactionGenerator.java
  hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/domain/generators/transaction/FileTransactionGenerator.java
  hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/domain/writer/DomainWriter.java
  hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/domain/writer/PostgresCSVDomainWriter.java
  hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sampling/ConstantValueDistribution.java
  hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sampling/Distribution.java
  hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sampling/FrequencyDistribution.java
  hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sampling/NumberDistributionConfig.java
  hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sampling/RandomDistributionFromRange.java
  hedera-mirror-datagenerator/src/main/resources/application.yml
  hedera-mirror-importer/pom.xml
  hedera-mirror-importer/src/main/resources/db/scripts/manage_constraints_and_indexes.sql
  hedera-mirror-rest/__performancetests__/generateQuerySets.js
  hedera-mirror-rest/__performancetests__/perfTest.js
  hedera-mirror-rest/__performancetests__/perfTestConfig.yml
  hedera-mirror-rest/__performancetests__/tests.yml
  hedera-mirror-rest/__performancetests__/utils.js
  hedera-mirror-rest/package.json
  pom.xml
Labels: P1, api, performance, test

#463 Fix default results success value. Also ensure single failure is pick…
  hedera-mirror-rest/monitoring/monitor_apis/account_tests.js
  hedera-mirror-rest/monitoring/monitor_apis/balance_tests.js
  hedera-mirror-rest/monitoring/monitor_apis/common.js
  hedera-mirror-rest/monitoring/monitor_apis/monitor.js
  hedera-mirror-rest/monitoring/monitor_apis/monitor_tests.js
  hedera-mirror-rest/monitoring/monitor_apis/monitortest_utils.js
  hedera-mirror-rest/monitoring/monitor_apis/transaction_tests.js
  hedera-mirror-rest/monitoring/monitor_dashboard/js/main.js
Labels: P1, bug, monitor

#467 Fix Monitor Error Handling for long running tests
  hedera-mirror-rest/monitoring/monitor_apis/account_tests.js
  hedera-mirror-rest/monitoring/monitor_apis/balance_tests.js
  hedera-mirror-rest/monitoring/monitor_apis/common.js
  hedera-mirror-rest/monitoring/monitor_apis/monitor.js
  hedera-mirror-rest/monitoring/monitor_apis/monitortest_utils.js
  hedera-mirror-rest/monitoring/monitor_apis/package-lock.json
  hedera-mirror-rest/monitoring/monitor_apis/package.json
  hedera-mirror-rest/monitoring/monitor_apis/transaction_tests.js
  hedera-mirror-rest/monitoring/monitor_dashboard/js/main.js
Labels: P1, bug, monitor

#469 Merge master into HCS
  hedera-mirror-rest/monitoring/monitor_apis/account_tests.js
  hedera-mirror-rest/monitoring/monitor_apis/balance_tests.js
  hedera-mirror-rest/monitoring/monitor_apis/common.js
  hedera-mirror-rest/monitoring/monitor_apis/monitor.js
  hedera-mirror-rest/monitoring/monitor_apis/monitor_tests.js
  hedera-mirror-rest/monitoring/monitor_apis/monitortest_utils.js
  hedera-mirror-rest/monitoring/monitor_apis/package-lock.json
  hedera-mirror-rest/monitoring/monitor_apis/package.json
  hedera-mirror-rest/monitoring/monitor_apis/transaction_tests.js
  hedera-mirror-rest/monitoring/monitor_dashboard/js/main.js
Labels: P1, enhancement, hcs

#471 Remove hcs from artifacts and bump to 0.5.0-beta1
  .circleci/config.yml
  docker-compose.yml
  docs/operations.md
  hedera-mirror-coverage/pom.xml
  hedera-mirror-datagenerator/pom.xml
  hedera-mirror-grpc/pom.xml
  hedera-mirror-grpc/scripts/deploy.sh
  hedera-mirror-importer/pom.xml
  hedera-mirror-importer/scripts/deploy.sh
  hedera-mirror-protobuf/pom.xml
  hedera-mirror-rest/__acceptancetests__/acceptancetests
  hedera-mirror-rest/package-lock.json
  hedera-mirror-rest/package.json
  hedera-mirror-rest/pom.xml
  pom.xml
Labels: P1, enhancement, hcs, process

#472 Fix CircleCI tag format
  .circleci/config.yml
  hedera-mirror-coverage/pom.xml
  hedera-mirror-datagenerator/pom.xml
  hedera-mirror-grpc/pom.xml
  hedera-mirror-importer/pom.xml
  hedera-mirror-protobuf/pom.xml
  hedera-mirror-rest/package-lock.json
  hedera-mirror-rest/package.json
  hedera-mirror-rest/pom.xml
  pom.xml
Labels: P1, bug, process

#473 Fix importer jar name in release artifact
  .circleci/config.yml
  hedera-mirror-coverage/pom.xml
  hedera-mirror-datagenerator/pom.xml
  hedera-mirror-grpc/pom.xml
  hedera-mirror-importer/pom.xml
  hedera-mirror-protobuf/pom.xml
  hedera-mirror-rest/package-lock.json
  hedera-mirror-rest/package.json
  hedera-mirror-rest/pom.xml
  pom.xml
Labels: P1, enhancement, process

#474 Fix GRPC user permissions and deploy script
  hedera-mirror-coverage/pom.xml
  hedera-mirror-datagenerator/pom.xml
  hedera-mirror-grpc/pom.xml
  hedera-mirror-grpc/scripts/db/init.sh
  hedera-mirror-grpc/scripts/deploy.sh
  hedera-mirror-importer/pom.xml
  hedera-mirror-importer/scripts/deploy.sh
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/MirrorProperties.java
  hedera-mirror-importer/src/main/resources/db/scripts/init.sql
  hedera-mirror-protobuf/pom.xml
  hedera-mirror-rest/package-lock.json
  hedera-mirror-rest/package.json
  hedera-mirror-rest/pom.xml
  pom.xml
Labels: P1, bug, process
