Repository hiero-ledger/hiero-mirror-node, pull requests merged in 2019-10, with the labels that each got.

#304 v0.3.0-rc1
  pom.xml
  rest-api/package.json
Labels: P1

#308 Add .editorconfig
  .editorconfig
Labels: enhancement

#311 Updated protobuf library to include new HAPI response codes.
  pom.xml
  rest-api/package.json
  src/main/resources/db/migration/V1.11.5.1__response_codes.sql
Labels: P1, bug

#312 Updated protobuf library to include new HAPI response codes.
  pom.xml
  src/main/resources/db/migration/V1.11.5.1__response_codes.sql
Labels: P1, bug, parser

#313 AccountBalancesFileLoader improvements (Issues #297, #117)
  src/main/java/com/hedera/configLoader/ConfigLoader.java
  src/main/java/com/hedera/mirror/dataset/AccountBalancesFileLoader.java
  src/test/java/com/hedera/mirror/dataset/AccountBalancesFileLoaderIT.java
Labels: P2, bug, parser

#318 Fix install/upgrade to use of application.yml for DB config (instead of config.json)
  scripts/deploy-mirror-node.sh
  scripts/mirror-node.service
Labels: P1, bug

#273 Fill in entities from a file
  src/main/java/com/hedera/mirror/MirrorNodeConfiguration.java
  src/main/java/com/hedera/mirror/domain/Entities.java
  src/main/java/com/hedera/mirror/migration/V1_11_6__Missing_Entities.java
  src/main/java/com/hedera/mirror/repository/EntityTypeRepository.java
  src/main/java/com/hedera/mirror/repository/TransactionRepository.java
  src/main/java/com/hedera/recordFileLogger/Entities.java
  src/main/resources/application.yml
  src/test/java/com/hedera/IntegrationTest.java
  src/test/java/com/hedera/mirror/migration/V1_11_6__Missing_EntitiesTest.java
  src/test/java/com/hedera/mirror/repository/AbstractRepositoryTest.java
  src/test/java/com/hedera/mirror/repository/ContractResultRepositoryTest.java
  src/test/java/com/hedera/mirror/repository/EntityRepositoryTest.java
  src/test/java/com/hedera/mirror/repository/EntityTypeRepositoryTest.java
  src/test/java/com/hedera/mirror/repository/FileDataRepositoryTest.java
  src/test/java/com/hedera/mirror/repository/LiveHashRepositoryTest.java
  src/test/java/com/hedera/mirror/repository/RecordFileRepositoryTest.java
  src/test/java/com/hedera/mirror/repository/TransactionRepositoryTest.java
  src/test/java/com/hedera/mirror/repository/TransactionResultRepositoryTest.java
  src/test/java/com/hedera/mirror/repository/TransactionTypeRepositoryTest.java
Labels: P1, enhancement

#323 Fix sporadic circle CI integration test failures
  src/test/java/com/hedera/mirror/dataset/AccountBalancesFileLoaderIT.java
  src/test/java/com/hedera/mirror/repository/EntityRepositoryTest.java
  src/test/java/com/hedera/mirror/repository/FileDataRepositoryTest.java
  src/test/java/com/hedera/mirror/repository/LiveHashRepositoryTest.java
  src/test/java/com/hedera/mirror/repository/RecordFileRepositoryTest.java
  src/test/java/com/hedera/mirror/repository/TransactionRepositoryTest.java
  src/test/java/com/hedera/parser/RecordFileParserTest.java
  src/test/java/com/hedera/recordLogger/RecordFileLoggerCryptoTest.java
  src/test/java/com/hedera/recordLogger/RecordFileLoggerFileTest.java
Labels: P1

#319 316-Improved test coverage
  src/main/java/com/hedera/recordFileLogger/RecordFileLogger.java
  src/test/java/com/hedera/recordFileLogger/AbstractRecordFileLoggerTest.java
  src/test/java/com/hedera/recordFileLogger/RecordFileLoggerCryptoTest.java
  src/test/java/com/hedera/recordFileLogger/RecordFileLoggerFileTest.java
  src/test/java/com/hedera/recordFileLogger/RecordFileLoggerTest.java
Labels: P3, parser, test

#330 [Downloader] Simplify downloader code
  src/main/java/com/hedera/mirror/downloader/Downloader.java
  src/main/java/com/hedera/mirror/downloader/NodeSignatureVerifier.java
  src/main/java/com/hedera/mirror/downloader/balance/AccountBalancesDownloader.java
  src/main/java/com/hedera/mirror/downloader/event/EventStreamFileDownloader.java
  src/main/java/com/hedera/mirror/downloader/record/RecordFileDownloader.java
  src/main/java/com/hedera/utilities/Utility.java
Labels: P3, downloader, enhancement, technical debt

#320 301 - Adds contract transactions tests
  src/test/java/com/hedera/recordFileLogger/AbstractRecordFileLoggerTest.java
  src/test/java/com/hedera/recordFileLogger/RecordFileLoggerContractTest.java
  src/test/java/com/hedera/recordFileLogger/RecordFileLoggerCryptoTest.java
Labels: P3, parser, test

#334 Add missing validDuration and maxFee columns
  CHANGELOG.md
  rest-api/__acceptancetests__/transactions.test.js
  rest-api/__tests__/integration.test.js
  rest-api/__tests__/specs/transactions-01-no-args.spec.json
  rest-api/__tests__/transactions.test.js
  rest-api/__tests__/transactionsTest.test.js
  rest-api/__tests__/utils.test.js
  rest-api/transactions.js
  rest-api/utils.js
  src/main/java/com/hedera/mirror/domain/Transaction.java
  src/main/java/com/hedera/recordFileLogger/RecordFileLogger.java
  src/main/resources/db/migration/V1.12__transactions_maxfee_duration.sql
  src/test/java/com/hedera/mirror/repository/AbstractRepositoryTest.java
  src/test/java/com/hedera/mirror/repository/TransactionRepositoryTest.java
  src/test/java/com/hedera/recordFileLogger/AbstractRecordFileLoggerTest.java
Labels: P2, api, database, good first issue

#343 Long overflow on CryptoAddClaim processing (#263)
  .gitignore
  docs/troubleshooting.md
  src/main/java/com/hedera/mirror/domain/Entities.java
  src/main/java/com/hedera/recordFileLogger/Entities.java
  src/main/java/com/hedera/recordFileLogger/RecordFileLogger.java
  src/main/java/com/hedera/utilities/Utility.java
  src/test/java/com/hedera/mirror/parser/record/RecordFileParserTest.java
  src/test/java/com/hedera/utilities/UtilityTest.java
  src/test/resources/data/badTimestampLongOverflowTest/2019-09-13T12_12_30.144357Z.rcd
Labels: bug, parser
