Repository hiero-ledger/hiero-mirror-node, pull requests merged in 2019-09, with the labels that each got.

#172 Updating proxy_account_id to fx_prox_acc_id
  src/main/java/com/hedera/recordFileLogger/Entities.java
Labels: OABlocker, bug

#176 Fix balances query performance with related schema changes
  rest-api/balances.js
  src/main/java/com/hedera/mirror/dataset/AccountBalancesFileLoader.java
  src/main/resources/db/migration/V1.10.3__account_balances.sql
Labels: OABlocker, bug

#159 Record file hash mismatch
  src/main/java/com/hedera/databaseUtilities/ApplicationStatus.java
  src/main/java/com/hedera/downloader/AccountBalancesDownloader.java
  src/main/java/com/hedera/downloader/RecordFileDownloader.java
  src/main/java/com/hedera/parser/RecordFileParser.java
  src/main/java/com/hedera/utilities/Utility.java
Labels: OABlocker, bug

#182 181 incorrect hash calculations
  config/0.0.102-mainnet
  config/0.0.102-testnet
  src/main/java/com/hedera/downloader/RecordFileDownloader.java
  src/main/java/com/hedera/filedelimiters/FileDelimiter.java
  src/main/java/com/hedera/parser/EventStreamFileParser.java
  src/main/java/com/hedera/parser/RecordFileParser.java
  src/main/java/com/hedera/recordFileLogger/RecordFileLogger.java
  src/main/java/com/hedera/utilities/Utility.java
  src/test/java/com/hedera/downloader/RecordFileDownloaderTestV1.java
  src/test/java/com/hedera/downloader/RecordFileDownloaderTestV2.java
  src/test/resources/data/recordstreamsV1/record0.0.3/2019-07-01T14:13:00.317763Z.rcd
  src/test/resources/data/recordstreamsV1/record0.0.3/2019-07-01T14:13:00.317763Z.rcd_sig
  src/test/resources/data/recordstreamsV1/record0.0.3/2019-07-01T14:29:00.302068Z.rcd
  src/test/resources/data/recordstreamsV1/record0.0.3/2019-07-01T14:29:00.302068Z.rcd_sig
  src/test/resources/data/recordstreamsV1/record0.0.4/2019-07-01T14:13:00.317763Z.rcd
  src/test/resources/data/recordstreamsV1/record0.0.4/2019-07-01T14:13:00.317763Z.rcd_sig
  src/test/resources/data/recordstreamsV1/record0.0.4/2019-07-01T14:29:00.302068Z.rcd
  src/test/resources/data/recordstreamsV1/record0.0.4/2019-07-01T14:29:00.302068Z.rcd_sig
  src/test/resources/data/recordstreamsV1/record0.0.5/2019-07-01T14:13:00.317763Z.rcd
  src/test/resources/data/recordstreamsV1/record0.0.5/2019-07-01T14:13:00.317763Z.rcd_sig
  src/test/resources/data/recordstreamsV1/record0.0.5/2019-07-01T14:29:00.302068Z.rcd
  src/test/resources/data/recordstreamsV1/record0.0.5/2019-07-01T14:29:00.302068Z.rcd_sig
  src/test/resources/data/recordstreamsV1/record0.0.6/2019-07-01T14:13:00.317763Z.rcd
  src/test/resources/data/recordstreamsV1/record0.0.6/2019-07-01T14:13:00.317763Z.rcd_sig
  src/test/resources/data/recordstreamsV1/record0.0.6/2019-07-01T14:29:00.302068Z.rcd
  src/test/resources/data/recordstreamsV1/record0.0.6/2019-07-01T14:29:00.302068Z.rcd_sig
  src/test/resources/data/recordstreamsV2/record0.0.3/2019-08-30T18_10_00.419072Z.rcd
  src/test/resources/data/recordstreamsV2/record0.0.3/2019-08-30T18_10_00.419072Z.rcd_sig
  src/test/resources/data/recordstreamsV2/record0.0.3/2019-08-30T18_10_05.249678Z.rcd
  src/test/resources/data/recordstreamsV2/record0.0.3/2019-08-30T18_10_05.249678Z.rcd_sig
  src/test/resources/data/recordstreamsV2/record0.0.4/2019-08-30T18_10_00.419072Z.rcd
  src/test/resources/data/recordstreamsV2/record0.0.4/2019-08-30T18_10_00.419072Z.rcd_sig
  src/test/resources/data/recordstreamsV2/record0.0.4/2019-08-30T18_10_05.249678Z.rcd
  src/test/resources/data/recordstreamsV2/record0.0.4/2019-08-30T18_10_05.249678Z.rcd_sig
  src/test/resources/data/recordstreamsV2/record0.0.5/2019-08-30T18_10_00.419072Z.rcd
  src/test/resources/data/recordstreamsV2/record0.0.5/2019-08-30T18_10_00.419072Z.rcd_sig
  src/test/resources/data/recordstreamsV2/record0.0.5/2019-08-30T18_10_05.249678Z.rcd
  src/test/resources/data/recordstreamsV2/record0.0.5/2019-08-30T18_10_05.249678Z.rcd_sig
  src/test/resources/data/recordstreamsV2/record0.0.6/2019-08-30T18_10_00.419072Z.rcd
  src/test/resources/data/recordstreamsV2/record0.0.6/2019-08-30T18_10_00.419072Z.rcd_sig
  src/test/resources/data/recordstreamsV2/record0.0.6/2019-08-30T18_10_05.249678Z.rcd
  src/test/resources/data/recordstreamsV2/record0.0.6/2019-08-30T18_10_05.249678Z.rcd_sig
Labels: OABlocker, bug

#179 Updated accounts.js with the new account_balances table, and fixed th…
  rest-api/accounts.js
  rest-api/balances.js
  rest-api/env.sample
Labels: OABlocker, performance

#187 Add Systemd service files
  CHANGELOG.md
  README.md
  buildimages.sh
  docker/docker-compose.yml
  pom.xml
  src/main/java/com/hedera/configLoader/ConfigLoader.java
  src/main/resources/shellScripts/balancedownload.sh
  src/main/resources/shellScripts/balanceparse.sh
  src/main/resources/shellScripts/crontab.txt
  src/main/resources/shellScripts/recorddownload.sh
  src/main/resources/shellScripts/recorddownloadandparse.sh
  src/main/resources/shellScripts/recordparse.sh
  systemd/mirror-balance-downloader.service
  systemd/mirror-balance-parser.service
  systemd/mirror-record-downloader.service
  systemd/mirror-record-parser.service
Labels: OABlocker, enhancement

#193 Fixes mirror node breaks when large address book is updated
  src/main/java/com/hedera/addressBook/NetworkAddressBook.java
  src/main/java/com/hedera/recordFileLogger/RecordFileLogger.java
Labels: P1, bug

#178 CircleCI store artifact on releases tagged with /v.*/
  .circleci/config.yml
Labels: ops, process

#199 Fix RecordDownloaderTest
  src/test/java/com/hedera/downloader/RecordFileDownloaderTest.java
  src/test/java/com/hedera/downloader/RecordFileDownloaderTestV2.java
  src/test/resources/data/recordstreams/v1/record0.0.3/2019-07-01T14:13:00.317763Z.rcd
  src/test/resources/data/recordstreams/v1/record0.0.3/2019-07-01T14:13:00.317763Z.rcd_sig
  src/test/resources/data/recordstreams/v1/record0.0.3/2019-07-01T14:29:00.302068Z.rcd
  src/test/resources/data/recordstreams/v1/record0.0.3/2019-07-01T14:29:00.302068Z.rcd_sig
  src/test/resources/data/recordstreams/v1/record0.0.4/2019-07-01T14:13:00.317763Z.rcd
  src/test/resources/data/recordstreams/v1/record0.0.4/2019-07-01T14:13:00.317763Z.rcd_sig
  src/test/resources/data/recordstreams/v1/record0.0.4/2019-07-01T14:29:00.302068Z.rcd
  src/test/resources/data/recordstreams/v1/record0.0.4/2019-07-01T14:29:00.302068Z.rcd_sig
  src/test/resources/data/recordstreams/v1/record0.0.5/2019-07-01T14:13:00.317763Z.rcd
  src/test/resources/data/recordstreams/v1/record0.0.5/2019-07-01T14:13:00.317763Z.rcd_sig
  src/test/resources/data/recordstreams/v1/record0.0.5/2019-07-01T14:29:00.302068Z.rcd
  src/test/resources/data/recordstreams/v1/record0.0.5/2019-07-01T14:29:00.302068Z.rcd_sig
  src/test/resources/data/recordstreams/v1/record0.0.6/2019-07-01T14:13:00.317763Z.rcd
  src/test/resources/data/recordstreams/v1/record0.0.6/2019-07-01T14:13:00.317763Z.rcd_sig
  src/test/resources/data/recordstreams/v1/record0.0.6/2019-07-01T14:29:00.302068Z.rcd
  src/test/resources/data/recordstreams/v1/record0.0.6/2019-07-01T14:29:00.302068Z.rcd_sig
  src/test/resources/data/recordstreams/v2/record0.0.3/2019-08-30T18_10_00.419072Z.rcd
  src/test/resources/data/recordstreams/v2/record0.0.3/2019-08-30T18_10_00.419072Z.rcd_sig
  src/test/resources/data/recordstreams/v2/record0.0.3/2019-08-30T18_10_05.249678Z.rcd
  src/test/resources/data/recordstreams/v2/record0.0.3/2019-08-30T18_10_05.249678Z.rcd_sig
  src/test/resources/data/recordstreams/v2/record0.0.4/2019-08-30T18_10_00.419072Z.rcd
  src/test/resources/data/recordstreams/v2/record0.0.4/2019-08-30T18_10_00.419072Z.rcd_sig
  src/test/resources/data/recordstreams/v2/record0.0.4/2019-08-30T18_10_05.249678Z.rcd
  src/test/resources/data/recordstreams/v2/record0.0.4/2019-08-30T18_10_05.249678Z.rcd_sig
  src/test/resources/data/recordstreams/v2/record0.0.5/2019-08-30T18_10_00.419072Z.rcd
  src/test/resources/data/recordstreams/v2/record0.0.5/2019-08-30T18_10_00.419072Z.rcd_sig
  src/test/resources/data/recordstreams/v2/record0.0.5/2019-08-30T18_10_05.249678Z.rcd
  src/test/resources/data/recordstreams/v2/record0.0.5/2019-08-30T18_10_05.249678Z.rcd_sig
  src/test/resources/data/recordstreams/v2/record0.0.6/2019-08-30T18_10_00.419072Z.rcd
  src/test/resources/data/recordstreams/v2/record0.0.6/2019-08-30T18_10_00.419072Z.rcd_sig
  src/test/resources/data/recordstreams/v2/record0.0.6/2019-08-30T18_10_05.249678Z.rcd
  src/test/resources/data/recordstreams/v2/record0.0.6/2019-08-30T18_10_05.249678Z.rcd_sig
Labels: bug, test

#196 CircleCI jacoco test coverage
  .circleci/config.yml
  README.md
  pom.xml
Labels: P1, test

#207 Fix coverage & license badge links
  README.md
Labels: documentation

#211 Force anonymous AWS credentials to be used by downloader when so configured
  src/main/java/com/hedera/downloader/Downloader.java
Labels: P2, bug

#213 Fix db migration error
  src/main/java/com/hedera/databaseUtilities/DatabaseUtilities.java
  src/main/java/db/migration/V1_8__MigrateConfig.java
Labels: P2, bug

#218 Remove deprecated tables and columns from v0.1.
  src/main/resources/db/migration/V1.11.0__remove_deprecated.sql
Labels: P3, technical debt

#216 Spring Boot & single process
  .circleci/config.yml
  .gitignore
  README.md
  buildimages.sh
  config/config.json.sample
  config/dotenv.sample
  docker-compose.yml
  docker/docker-compose.yml
  docker/restapi.sh
  docker/scripts/cleanContainers.sh
  pom.xml
  rest-api/.dockerignore
  rest-api/Dockerfile
  scripts/deploy-mirror-node.sh
  scripts/mirror-node.service
  src/main/java/com/hedera/MirrorNodeApplication.java
  src/main/java/com/hedera/balanceFileLogger/BalanceFileLogger.java
  src/main/java/com/hedera/configLoader/ConfigLoader.java
  src/main/java/com/hedera/downloader/AccountBalancesDownloader.java
  src/main/java/com/hedera/downloader/DownloadAndParseEventFiles.java
  src/main/java/com/hedera/downloader/DownloadAndParseRecordFiles.java
  src/main/java/com/hedera/downloader/Downloader.java
  src/main/java/com/hedera/downloader/EventStreamFileDownloader.java
  src/main/java/com/hedera/downloader/RecordFileDownloader.java
  src/main/java/com/hedera/fileWatcher/FileWatcher.java
  src/main/java/com/hedera/mirror/config/BalanceProperties.java
  src/main/java/com/hedera/mirror/config/EventProperties.java
  src/main/java/com/hedera/mirror/config/RecordProperties.java
  src/main/java/com/hedera/parser/EventStreamFileParser.java
  src/main/java/com/hedera/parser/FileParser.java
  src/main/java/com/hedera/parser/RecordFileParser.java
  src/main/java/com/hedera/utilities/Utility.java
  src/main/resources/application.yml
  src/main/resources/banner.txt
  src/main/resources/log4j2.xml
  src/test/java/com/hedera/downloader/AccountBalancesDownloaderTest.java
  src/test/java/com/hedera/downloader/RecordFileDownloaderTest.java
  src/test/java/com/hedera/utilities/UtilityTest.java
  src/test/resources/log4j2-test.xml
  systemd/mirror-balance-downloader.service
  systemd/mirror-balance-parser.service
  systemd/mirror-record-downloader.service
  systemd/mirror-record-parser.service
Labels: P1, enhancement

#226 Remove balanceVerifySigs property
  config/config.json.sample
  pom.xml
  src/main/java/com/hedera/configLoader/ConfigLoader.java
  src/main/java/com/hedera/downloader/AccountBalancesDownloader.java
  src/main/java/com/hedera/downloader/Downloader.java
  src/main/resources/banner.txt
  src/main/resources/db/migration/V1.11.1__remove_deprecated.sql
  src/test/resources/config.json
Labels: P3, enhancement

#215 Troubleshooting guide
  README.md
  docs/operations.md
  docs/troubleshooting.md
Labels: P1, documentation, ops

#234 Fix record file mismatch race condition
  src/main/java/com/hedera/downloader/RecordFileDownloader.java
  src/test/java/com/hedera/downloader/RecordFileDownloaderTestV1.java
  src/test/java/com/hedera/downloader/RecordFileDownloaderTestV2.java
Labels: P1, bug

#236 Fix /transactions query performance
  config/flyway.conf.sample
  rest-api/__tests__/transactionsTest.test.js
  rest-api/accounts.js
  rest-api/transactions.js
  src/main/java/com/hedera/parser/RecordFileParser.java
  src/main/java/com/hedera/recordFileLogger/RecordFileLogger.java
  src/main/resources/db/migration/V1.11.2__transactions_pk.sql
Labels: P1, bug

#239 CryptoCreate initial balance transfer not visible in REST API
  src/main/java/com/hedera/recordFileLogger/RecordFileLogger.java
Labels: P1, bug

#241 Fix record file mismatch race condition (master)
  src/main/java/com/hedera/downloader/RecordFileDownloader.java
  src/test/java/com/hedera/downloader/RecordFileDownloaderTest.java
Labels: P1, bug

#242 Only update entities, via the record stream, if the transaction was successful
  src/main/java/com/hedera/recordFileLogger/RecordFileLogger.java
Labels: P1, bug

#258 Fix table name on insert to be t_livehashes
  src/main/java/com/hedera/recordFileLogger/RecordFileLogger.java
Labels: P1, bug

#252 Improve download performance [master]
  README.md
  src/main/java/com/hedera/configLoader/ConfigLoader.java
  src/main/java/com/hedera/downloader/AccountBalancesDownloader.java
  src/main/java/com/hedera/downloader/Downloader.java
  src/main/java/com/hedera/downloader/EventStreamFileDownloader.java
  src/main/java/com/hedera/downloader/PendingDownload.java
  src/main/java/com/hedera/downloader/RecordFileDownloader.java
  src/main/java/com/hedera/mirror/config/BalanceProperties.java
  src/main/java/com/hedera/mirror/config/CommonDownloaderProperties.java
  src/main/java/com/hedera/mirror/config/DownloaderProperties.java
  src/main/java/com/hedera/mirror/config/EventProperties.java
  src/main/java/com/hedera/mirror/config/RecordProperties.java
  src/test/java/com/hedera/downloader/AccountBalancesDownloaderTest.java
  src/test/java/com/hedera/downloader/RecordFileDownloaderTest.java
Labels: P1, bug

#262 Bug/livehashes sql on 0.1 release
  pom.xml
  src/main/java/com/hedera/recordFileLogger/RecordFileLogger.java
Labels: P1, bug

#261 Corrected the queries to include accounts and smart contracts
  rest-api/__tests__/transactionsTest.test.js
  rest-api/accounts.js
  rest-api/balances.js
  rest-api/server.js
  rest-api/transactions.js
  rest-api/utils.js
Labels: P1, api

#264 Fix duplicate entities
  src/main/java/com/hedera/recordFileLogger/Entities.java
  src/main/resources/db/migration/V1.11.4__duplicate_entities.sql
Labels: P1, bug, database

#265 Update pom for v0.2.0-rc2
  pom.xml
Labels: P1

#266 Remove fk_type_id uniqueness check in f_entity_create.
  src/main/resources/db/migration/V1.11.5__entity_create.sql
Labels: P1

#267 Fix record parser continuing to next file after exception
  src/main/java/com/hedera/parser/RecordFileParser.java
  src/main/java/com/hedera/recordFileLogger/RecordFileLogger.java
Labels: P1, bug

#268 Bug/livehashes2
  pom.xml
  src/main/java/com/hedera/recordFileLogger/RecordFileLogger.java
Labels: P1, bug

#272 Fixed the SQL query for /balances?account.publickey api
  rest-api/__tests__/accounts.test.js
  rest-api/__tests__/balances.test.js
  rest-api/balances.js
Labels: P1, api, bug

#280 Set pom version to 0.3-SNAPSHOT
  pom.xml
Labels: P1

#283 Java Integration tests
  README.md
  config/config.json.sample
  pom.xml
  src/main/java/com/hedera/MirrorNodeApplication.java
  src/main/java/com/hedera/configLoader/ConfigLoader.java
  src/main/java/com/hedera/databaseUtilities/ApplicationStatus.java
  src/main/java/com/hedera/databaseUtilities/DatabaseUtilities.java
  src/main/java/com/hedera/downloader/AccountBalancesDownloader.java
  src/main/java/com/hedera/downloader/Downloader.java
  src/main/java/com/hedera/downloader/EventStreamFileDownloader.java
  src/main/java/com/hedera/downloader/RecordFileDownloader.java
  src/main/java/com/hedera/mirror/CacheConfiguration.java
  src/main/java/com/hedera/mirror/domain/ApplicationStatus.java
  src/main/java/com/hedera/mirror/domain/ApplicationStatusCode.java
  src/main/java/com/hedera/mirror/repository/ApplicationStatusRepository.java
  src/main/java/com/hedera/parser/EventStreamFileParser.java
  src/main/java/com/hedera/parser/FileParser.java
  src/main/java/com/hedera/parser/RecordFileParser.java
  src/main/resources/application.yml
  src/test/java/com/hedera/IntegrationTest.java
  src/test/java/com/hedera/downloader/AccountBalancesDownloaderTest.java
  src/test/java/com/hedera/downloader/RecordFileDownloaderTest.java
  src/test/java/com/hedera/mirror/repository/ApplicationStatusRepositoryTest.java
  src/test/resources/config.json
Labels: P1, database, enhancement, test

#270 269 parameter checking
  rest-api/__tests__/accounts.test.js
  rest-api/__tests__/balances.test.js
  rest-api/__tests__/testutils.js
  rest-api/__tests__/transactions.test.js
  rest-api/accounts.js
  rest-api/balances.js
  rest-api/cacher.js
  rest-api/transactions.js
  rest-api/utils.js
Labels: P2, api, bug

#284 Switch to codecov.io
  .circleci/config.yml
  README.md
  codecov.yml
  pom.xml
Labels: P2, enhancement

#279 Add rest-api npm install-test to CI.
  .circleci/config.yml
  rest-api/.gitignore
  rest-api/.npmignore
  rest-api/Dockerfile
  rest-api/package-lock.json
  rest-api/package.json
Labels: api, test

#286 Fix S3 not logging some errors
  src/main/java/com/hedera/configLoader/ConfigLoader.java
  src/main/java/com/hedera/downloader/Downloader.java
Labels: P1, bug

#285 Fix circleCI Test Summary
  .circleci/config.yml
  pom.xml
  rest-api/package-lock.json
  rest-api/package.json
Labels: process

#293 Fix java integration tests not running in CircleCI
  .circleci/config.yml
  pom.xml
  src/test/java/com/hedera/IntegrationTest.java
  src/test/java/com/hedera/mirror/repository/ApplicationStatusRepositoryTest.java
  src/test/java/com/hedera/parser/RecordFileParserTest.java
Labels: bug, test

#292 rest-api/db integration test using flyway (sql-only, no java)
  .circleci/config.yml
  rest-api/.dockerignore
  rest-api/.gitignore
  rest-api/.node-flywaydb.integration.conf
  rest-api/.npmignore
  rest-api/__tests__/integration.test.js
  rest-api/__tests__/specs/accounts-01-no-args.spec.json
  rest-api/__tests__/specs/balances-01-no-args.spec.json
  rest-api/__tests__/specs/transactions-01-no-args.spec.json
  rest-api/flyway.conf.integration
  rest-api/package-lock.json
  rest-api/package.json
  rest-api/transactions.js
  rest-api/utils.js
Labels: P1

#291 244 rest api unit tests new
  rest-api/__tests__/accounts.test.js
  rest-api/__tests__/balances.test.js
  rest-api/__tests__/mockpool.js
  rest-api/__tests__/transactions.test.js
Labels: api, test

#290 mirror-node-acceptance-tests
  README.md
  rest-api/__acceptancetests__/acceptancetest_utils.js
  rest-api/__acceptancetests__/acceptancetests
  rest-api/__acceptancetests__/accounts.test.js
  rest-api/__acceptancetests__/balances.test.js
  rest-api/__acceptancetests__/transactions.test.js
  rest-api/config.js
  rest-api/monitoring/monitor_apis/accounts.monitor.js
  rest-api/monitoring/monitor_apis/balances.monitor.js
  rest-api/monitoring/monitor_apis/common.js
  rest-api/monitoring/monitor_apis/monitor.js
  rest-api/monitoring/monitor_apis/package.json
  rest-api/monitoring/monitor_apis/server.js
  rest-api/monitoring/monitor_apis/transactions.monitor.js
  rest-api/monitoring/monitor_dashboard/js/main.js
  rest-api/package.json
Labels: P2, api, bug, test
