Repository hiero-ledger/hiero-mirror-node, pull requests merged in 2019-08, with the labels that each got.

#146 Fix README and add -DlogDir
  README.md
  src/main/resources/log4j2.xml
Labels: bug

#152 Proxy: Remove HAPI proxying functionality
  README.md
  pom.xml
  src/main/java/com/hedera/configLoader/ConfigLoader.java
  src/main/java/com/hedera/mirrorNodeProxy/MirrorNodeProxy.java
  src/main/java/com/hedera/mirrorservice/CryptoServiceMirror.java
  src/main/java/com/hedera/mirrorservice/FileServiceMirror.java
  src/main/java/com/hedera/mirrorservice/FreezeServiceMirror.java
  src/main/java/com/hedera/mirrorservice/ServiceAgent.java
  src/main/java/com/hedera/mirrorservice/SmartContractServiceMirror.java
Labels: P1, technical debt

#153 Fix CircleCI caching
  .circleci/config.yml
Labels: bug

#155 Update bug report and contributing
  .github/ISSUE_TEMPLATE/1-bug-report.md
  CONTRIBUTING.md
Labels: documentation

#156 Added license shield and removed CI API key
  README.md
Labels: documentation

#166 Updates support for protobuf to match pending network upgrades
  pom.xml
  src/main/java/com/hedera/recordFileLogger/RecordFileLogger.java
  src/main/resources/db/migration/V1.10.2__response_codes.sql
Labels: OABlocker, bug

#170 Add record downloader tests
  pom.xml
  src/main/java/com/hedera/configLoader/ConfigLoader.java
  src/main/java/com/hedera/downloader/DownloadAndParseRecordFiles.java
  src/main/java/com/hedera/downloader/Downloader.java
  src/main/java/com/hedera/downloader/RecordFileDownloader.java
  src/main/java/com/hedera/signatureVerifier/NodeSignatureVerifier.java
  src/main/java/com/hedera/utilities/Utility.java
  src/test/java/com/hedera/FileCopier.java
  src/test/java/com/hedera/UtilityTest.java
  src/test/java/com/hedera/downloader/RecordFileDownloaderTest.java
  src/test/java/com/hedera/utilities/UtilityTest.java
  src/test/resources/config.json
  src/test/resources/data/recordstreams/record0.0.3/2019-07-01T14:13:00.317763Z.rcd
  src/test/resources/data/recordstreams/record0.0.3/2019-07-01T14:13:00.317763Z.rcd_sig
  src/test/resources/data/recordstreams/record0.0.3/2019-07-01T14:29:00.302068Z.rcd
  src/test/resources/data/recordstreams/record0.0.3/2019-07-01T14:29:00.302068Z.rcd_sig
  src/test/resources/data/recordstreams/record0.0.4/2019-07-01T14:13:00.317763Z.rcd
  src/test/resources/data/recordstreams/record0.0.4/2019-07-01T14:13:00.317763Z.rcd_sig
  src/test/resources/data/recordstreams/record0.0.4/2019-07-01T14:29:00.302068Z.rcd
  src/test/resources/data/recordstreams/record0.0.4/2019-07-01T14:29:00.302068Z.rcd_sig
  src/test/resources/data/recordstreams/record0.0.5/2019-07-01T14:13:00.317763Z.rcd
  src/test/resources/data/recordstreams/record0.0.5/2019-07-01T14:13:00.317763Z.rcd_sig
  src/test/resources/data/recordstreams/record0.0.5/2019-07-01T14:29:00.302068Z.rcd
  src/test/resources/data/recordstreams/record0.0.5/2019-07-01T14:29:00.302068Z.rcd_sig
  src/test/resources/data/recordstreams/record0.0.6/2019-07-01T14:13:00.317763Z.rcd
  src/test/resources/data/recordstreams/record0.0.6/2019-07-01T14:13:00.317763Z.rcd_sig
  src/test/resources/data/recordstreams/record0.0.6/2019-07-01T14:29:00.302068Z.rcd
  src/test/resources/data/recordstreams/record0.0.6/2019-07-01T14:29:00.302068Z.rcd_sig
  src/test/resources/log4j2-test.xml
Labels: enhancement, test
