Repository hiero-ledger/hiero-mirror-node, pull requests merged in 2020-11, with the labels that each got.

#1204 Add redis sentinel configuration for importer
  charts/hedera-mirror-importer/templates/statefulset.yaml
  charts/hedera-mirror-importer/values.yaml
  charts/hedera-mirror/values.yaml
Labels: P2, bug

#1222 Fix mainnet bucket name
  application.yml
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/MirrorProperties.java
  hedera-mirror-rest/constants.js
Labels: P1, bug

#1224 Bump versions for 0.21.0
  charts/hedera-mirror-common/Chart.yaml
  charts/hedera-mirror-grpc/Chart.yaml
  charts/hedera-mirror-importer/Chart.yaml
  charts/hedera-mirror-rest/Chart.yaml
  charts/hedera-mirror/Chart.yaml
  docker-compose.yml
  hedera-mirror-coverage/pom.xml
  hedera-mirror-datagenerator/pom.xml
  hedera-mirror-grpc/pom.xml
  hedera-mirror-importer/pom.xml
  hedera-mirror-protobuf/pom.xml
  hedera-mirror-rest/monitoring/monitor_apis/package-lock.json
  hedera-mirror-rest/monitoring/monitor_apis/package.json
  hedera-mirror-rest/package-lock.json
  hedera-mirror-rest/package.json
  hedera-mirror-rest/pom.xml
  hedera-mirror-test/pom.xml
  hedera-mirror-test/src/test/resources/k8s/hcs-perf-message-submit.yml
  hedera-mirror-test/src/test/resources/k8s/hcs-perf-publish-test.yml
  hedera-mirror-test/src/test/resources/k8s/hcs-perf-subscribe-test.yml
  hedera-mirror-test/src/test/resources/k8s/hts-perf-batch-publish-batch-validate.yml
  hedera-mirror-test/src/test/resources/k8s/hts-perf-publish-and-retrieve.yml
  pom.xml
Labels: enhancement, process

#1202 Increase importer and rest container resource limit
  charts/hedera-mirror-importer/values.yaml
  charts/hedera-mirror-rest/values.yaml
Labels: P2, enhancement, test

#1225 Bump versions for v0.22.0-rc1
  charts/hedera-mirror-common/Chart.yaml
  charts/hedera-mirror-grpc/Chart.yaml
  charts/hedera-mirror-importer/Chart.yaml
  charts/hedera-mirror-rest/Chart.yaml
  charts/hedera-mirror/Chart.yaml
  charts/hedera-mirror/requirements.lock
  docker-compose.yml
  hedera-mirror-coverage/pom.xml
  hedera-mirror-datagenerator/pom.xml
  hedera-mirror-grpc/pom.xml
  hedera-mirror-importer/pom.xml
  hedera-mirror-monitor/pom.xml
  hedera-mirror-protobuf/pom.xml
  hedera-mirror-rest/monitoring/monitor_apis/package-lock.json
  hedera-mirror-rest/monitoring/monitor_apis/package.json
  hedera-mirror-rest/package-lock.json
  hedera-mirror-rest/package.json
  hedera-mirror-rest/pom.xml
  hedera-mirror-test/pom.xml
  hedera-mirror-test/src/test/resources/k8s/hcs-perf-message-submit.yml
  hedera-mirror-test/src/test/resources/k8s/hcs-perf-publish-test.yml
  hedera-mirror-test/src/test/resources/k8s/hcs-perf-subscribe-test.yml
  hedera-mirror-test/src/test/resources/k8s/hts-perf-batch-publish-batch-validate.yml
  hedera-mirror-test/src/test/resources/k8s/hts-perf-publish-and-retrieve.yml
  pom.xml
Labels: enhancement, process

#1223 Increase gRPC server keepalive
  docs/configuration.md
  hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/config/GrpcConfiguration.java
  hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/config/NettyProperties.java
  hedera-mirror-grpc/src/main/resources/application.yml
  hedera-mirror-grpc/src/test/resources/config/application.yml
Labels: P3, enhancement, grpc

#1226 Cache current address book
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java
Labels: P3, database, enhancement

#1232 Fix gRPC performance bottleneck
  hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/listener/NotifyingTopicListener.java
  hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/listener/RedisTopicListener.java
  hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/listener/SharedPollingTopicListener.java
  hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/listener/SharedTopicListener.java
Labels: P2, bug, grpc, performance

#1230 Enable SonarCloud code scanning
  .github/workflows/code-scan.yml
  hedera-mirror-grpc/pom.xml
  hedera-mirror-monitor/pom.xml
  hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/generator/CompositeTransactionGeneratorTest.java
  hedera-mirror-rest/monitoring/monitor_apis/package-lock.json
  hedera-mirror-rest/monitoring/monitor_apis/package.json
  hedera-mirror-rest/package-lock.json
  hedera-mirror-rest/package.json
  hedera-mirror-rest/pom.xml
  pom.xml
Labels: P1, enhancement, security

#1234 Upgrade Spring Boot to 2.3.5 to fix pgpool connection issue
  pom.xml
Labels: P2, bug, database

#1233 Rosetta Individual Postgres User
  docker-compose.yml
  docs/configuration.md
  docs/installation.md
  hedera-mirror-importer/src/main/resources/db/scripts/init.sql
  hedera-mirror-rosetta/build/Dockerfile
  hedera-mirror-rosetta/config/application.yml
Labels: enhancement, rosetta

#1228 Ensure entities are inserted only on create
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/AbstractEntityRecordItemListenerTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerContractTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerCryptoTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerFileTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerTopicTest.java
Labels: P1, bug, parser

#1249 Bump version 0.22.0
  charts/hedera-mirror-common/Chart.yaml
  charts/hedera-mirror-grpc/Chart.yaml
  charts/hedera-mirror-importer/Chart.yaml
  charts/hedera-mirror-rest/Chart.yaml
  charts/hedera-mirror/Chart.yaml
  charts/hedera-mirror/requirements.lock
  docker-compose.yml
  hedera-mirror-coverage/pom.xml
  hedera-mirror-datagenerator/pom.xml
  hedera-mirror-grpc/pom.xml
  hedera-mirror-importer/pom.xml
  hedera-mirror-monitor/pom.xml
  hedera-mirror-protobuf/pom.xml
  hedera-mirror-rest/monitoring/monitor_apis/package-lock.json
  hedera-mirror-rest/monitoring/monitor_apis/package.json
  hedera-mirror-rest/package-lock.json
  hedera-mirror-rest/package.json
  hedera-mirror-rest/pom.xml
  hedera-mirror-test/pom.xml
  hedera-mirror-test/src/test/resources/k8s/hcs-perf-message-submit.yml
  hedera-mirror-test/src/test/resources/k8s/hcs-perf-publish-test.yml
  hedera-mirror-test/src/test/resources/k8s/hcs-perf-subscribe-test.yml
  hedera-mirror-test/src/test/resources/k8s/hts-perf-batch-publish-batch-validate.yml
  hedera-mirror-test/src/test/resources/k8s/hts-perf-publish-and-retrieve.yml
  pom.xml
Labels: enhancement, process

#1252 Fix NoSuchMethodError during hcs-perf-subscribe-test
  hedera-mirror-grpc/pom.xml
  hedera-mirror-protobuf/pom.xml
  hedera-mirror-test/pom.xml
  pom.xml
Labels: P3, bug, test

#1251 Add monitor charts
  application.yml
  charts/README.md
  charts/hedera-mirror-importer/templates/NOTES.txt
  charts/hedera-mirror-monitor/.helmignore
  charts/hedera-mirror-monitor/Chart.yaml
  charts/hedera-mirror-monitor/templates/NOTES.txt
  charts/hedera-mirror-monitor/templates/_helpers.tpl
  charts/hedera-mirror-monitor/templates/deployment.yaml
  charts/hedera-mirror-monitor/templates/podmonitor.yaml
  charts/hedera-mirror-monitor/templates/prometheusrule.yaml
  charts/hedera-mirror-monitor/templates/role.yaml
  charts/hedera-mirror-monitor/templates/rolebinding.yaml
  charts/hedera-mirror-monitor/templates/secret.yaml
  charts/hedera-mirror-monitor/templates/serviceaccount.yaml
  charts/hedera-mirror-monitor/values.yaml
  charts/hedera-mirror/requirements.lock
  charts/hedera-mirror/requirements.yaml
  charts/hedera-mirror/values-prod.yaml
  charts/hedera-mirror/values.yaml
  docker-compose.yml
Labels: P2, enhancement, monitor

#1253 Fix SonarCloud bugs
  .gitignore
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/V1_11_6__Missing_Entities.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/FileWatcher.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/RecordFileParser.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/balance/BalanceFileReaderImplV1.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/util/ShutdownHelper.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/util/Utility.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/downloader/AbstractDownloaderTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/downloader/balance/AccountBalancesDownloaderTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/downloader/event/EventFileDownloaderTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/downloader/record/RecordFileDownloaderTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/RecordFileParserIntegrationTest.java
  hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/TransactionPublisher.java
  hedera-mirror-rest/__tests__/config.test.js
  hedera-mirror-rest/__tests__/integrationS3Ops.js
  hedera-mirror-rest/__tests__/stateproof.test.js
  hedera-mirror-rest/monitoring/monitor_dashboard/css/main.css
  hedera-mirror-rest/monitoring/monitor_dashboard/index.html
  hedera-mirror-rest/monitoring/monitor_dashboard/js/main.js
  hedera-mirror-rest/server.js
  hedera-mirror-rest/utils.js
Labels: P1, bug, security

#1236 Fix address book update always updating 102 file
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/util/Utility.java
  hedera-mirror-importer/src/main/resources/db/migration/V1.31.0__fix_address_book_102.sql
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/V1_31_0_fix_address_book_102Test.java
  hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/PublishMetrics.java
Labels: P1, bug, database

#1258 Change token symbol size to 100
  hedera-mirror-importer/src/main/resources/db/migration/V1.31.1__token_symbol_size_100.sql
Labels: P1, database, enhancement, hts

#1235 Add version migrations to fix entity type mismatches in db
  hedera-mirror-importer/src/main/resources/db/migration/V1.31.2__remove_invalid_entities.sql
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/V_1_31_2__Remove_Invalid_EntitiesTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/AbstractEntityRecordItemListenerTest.java
Labels: P1, bug, parser

#1262 Fix SonarCloud security hotspots
  hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/common/TransactionGenerator.java
  hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/domain/generators/transaction/FileTransactionGenerator.java
  hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/domain/generators/transaction/TopicTransactionGenerator.java
  hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sampling/RandomDistributionFromRange.java
  hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/consensus/ConsensusSubmitMessageTransactionSupplier.java
  hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/domain/TopicMessageFilter.java
  hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/TransactionPublisher.java
  hedera-mirror-rest/__performancetests__/generateQuerySets.js
  hedera-mirror-rest/__performancetests__/perfTest.js
  hedera-mirror-rest/__tests__/integration.test.js
  hedera-mirror-rest/__tests__/specs/stateproof-01-success-result.spec.json
  hedera-mirror-rest/__tests__/specs/stateproof-07-alternative-success-result.spec.json
  hedera-mirror-rest/__tests__/specs/stateproof-08-success-result-with-address-book-history.spec.json
  hedera-mirror-rest/__tests__/testutils.js
  hedera-mirror-rest/monitoring/monitor_apis/server.js
Labels: P1, bug, security

#1263 Fix incorrect base64 encoding in stateproof
  hedera-mirror-rest/__tests__/stateproof.test.js
  hedera-mirror-rest/stateproof.js
Labels: P1, bug, rest

#1259 Fix state proof check failure on failed transaction check
  hedera-mirror-rest/monitoring/monitor_apis/stateproof_tests.js
Labels: P1, bug, monitor

#1254 Refactor importer to handle token transfers in crypto transfer
  docs/design/hts.md
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/TransactionTypeEnum.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenCreateTransactionsHandler.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenTransferTransactionsHandler.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenUpdateTransactionsHandler.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TransactionHandlerFactory.java
  hedera-mirror-importer/src/main/resources/db/migration/V1.31.3__delete_token_transfers_transaction_type.sql
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerTokenTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenCreateTransactionsHandlerTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenTransferTransactionsHandlerTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenUpdateTransactionsHandlerTest.java
  hedera-mirror-importer/src/test/resources/data/pubsub-messages.txt
  hedera-mirror-rest/__tests__/integrationDomainOps.js
  hedera-mirror-rest/__tests__/specs/accounts-14-account-transactions-transactiontype.spec.json
  hedera-mirror-rest/__tests__/specs/accounts-15-account-transactions-invalid-transactiontype.spec.json
  hedera-mirror-rest/__tests__/specs/token-info-01-no-args.spec.json
  hedera-mirror-rest/__tests__/specs/token-info-02-invalid-id.spec.json
  hedera-mirror-rest/__tests__/specs/token-info-03-not-found.spec.json
  hedera-mirror-rest/__tests__/specs/tokens-01-no-args.spec.json
  hedera-mirror-rest/__tests__/specs/tokens-02-none.spec.json
  hedera-mirror-rest/__tests__/specs/tokens-07-invalid-query-params.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-01-no-args.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-15-limit.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-16-specific-id-tokentransfer.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-17-transaction-type.spec.json
  hedera-mirror-rest/__tests__/utils.test.js
  hedera-mirror-rest/constants.js
  hedera-mirror-rest/transactions.js
  pom.xml
Labels: P1, enhancement, hts

#1260 Bump sdk and update token and crypto transfer transactions
  hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/TransactionType.java
  hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/account/CryptoTransferTransactionSupplier.java
  hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/token/TokenTransferTransactionSupplier.java
  hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/jmeter/handler/SDKClientHandler.java
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AccountClient.java
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
  pom.xml
Labels: P1, enhancement, hts

#1275 Bump versions for 0.23.0-rc1
  README.md
  charts/hedera-mirror-common/Chart.yaml
  charts/hedera-mirror-grpc/Chart.yaml
  charts/hedera-mirror-importer/Chart.yaml
  charts/hedera-mirror-monitor/Chart.yaml
  charts/hedera-mirror-rest/Chart.yaml
  charts/hedera-mirror/Chart.yaml
  charts/hedera-mirror/requirements.lock
  docker-compose.yml
  hedera-mirror-coverage/pom.xml
  hedera-mirror-datagenerator/pom.xml
  hedera-mirror-grpc/pom.xml
  hedera-mirror-importer/pom.xml
  hedera-mirror-monitor/pom.xml
  hedera-mirror-protobuf/pom.xml
  hedera-mirror-rest/monitoring/monitor_apis/package-lock.json
  hedera-mirror-rest/monitoring/monitor_apis/package.json
  hedera-mirror-rest/package-lock.json
  hedera-mirror-rest/package.json
  hedera-mirror-rest/pom.xml
  hedera-mirror-test/pom.xml
  hedera-mirror-test/src/test/resources/k8s/hcs-perf-message-submit.yml
  hedera-mirror-test/src/test/resources/k8s/hcs-perf-publish-test.yml
  hedera-mirror-test/src/test/resources/k8s/hcs-perf-subscribe-test.yml
  hedera-mirror-test/src/test/resources/k8s/hts-perf-batch-publish-batch-validate.yml
  hedera-mirror-test/src/test/resources/k8s/hts-perf-publish-and-retrieve.yml
  pom.xml
Labels: enhancement, process

#1276 Bump monitor dashboard dependencies
  hedera-mirror-rest/monitoring/monitor_dashboard/index.html
Labels: P1, bug, monitor, security

#1280 Bump version for 0.23.0
  charts/hedera-mirror-common/Chart.yaml
  charts/hedera-mirror-grpc/Chart.yaml
  charts/hedera-mirror-importer/Chart.yaml
  charts/hedera-mirror-monitor/Chart.yaml
  charts/hedera-mirror-rest/Chart.yaml
  charts/hedera-mirror/Chart.yaml
  charts/hedera-mirror/requirements.lock
  docker-compose.yml
  hedera-mirror-coverage/pom.xml
  hedera-mirror-datagenerator/pom.xml
  hedera-mirror-grpc/pom.xml
  hedera-mirror-importer/pom.xml
  hedera-mirror-monitor/pom.xml
  hedera-mirror-protobuf/pom.xml
  hedera-mirror-rest/monitoring/monitor_apis/package-lock.json
  hedera-mirror-rest/monitoring/monitor_apis/package.json
  hedera-mirror-rest/package-lock.json
  hedera-mirror-rest/package.json
  hedera-mirror-rest/pom.xml
  hedera-mirror-test/pom.xml
  hedera-mirror-test/src/test/resources/k8s/hcs-perf-message-submit.yml
  hedera-mirror-test/src/test/resources/k8s/hcs-perf-publish-test.yml
  hedera-mirror-test/src/test/resources/k8s/hcs-perf-subscribe-test.yml
  hedera-mirror-test/src/test/resources/k8s/hts-perf-batch-publish-batch-validate.yml
  hedera-mirror-test/src/test/resources/k8s/hts-perf-publish-and-retrieve.yml
  pom.xml
Labels: P1, enhancement, process

#1277 gRPC service performance optimization
  charts/hedera-mirror-grpc/values.yaml
  docs/configuration.md
  hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/controller/ConsensusController.java
  hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/domain/TopicMessage.java
  hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/exception/ClientTimeoutException.java
  hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/listener/ListenerProperties.java
  hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/listener/SharedPollingTopicListener.java
  hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/listener/SharedTopicListener.java
  hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/service/TopicMessageServiceImpl.java
  hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/controller/ConsensusControllerTest.java
  hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/listener/AbstractSharedTopicListenerTest.java
  hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/generator/CompositeTransactionGeneratorTest.java
Labels: P2, enhancement, grpc

#1279 Enable log alerts and normalize log statements
  charts/hedera-mirror-common/requirements.lock
  charts/hedera-mirror-common/requirements.yaml
  charts/hedera-mirror-common/templates/prometheusrule.yaml
  charts/hedera-mirror-common/values.yaml
  charts/hedera-mirror-grpc/values.yaml
  charts/hedera-mirror-importer/values.yaml
  charts/hedera-mirror-monitor/values.yaml
  charts/hedera-mirror-rest/values.yaml
  charts/hedera-mirror/requirements.lock
  charts/hedera-mirror/requirements.yaml
  charts/hedera-mirror/values.yaml
  charts/marketplace/gcp/release.sh
  charts/marketplace/gcp/values.yaml
  docs/configuration.md
  hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/controller/ConsensusController.java
  hedera-mirror-grpc/src/main/resources/log4j2.xml
  hedera-mirror-grpc/src/test/resources/log4j2-test.xml
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/PendingDownload.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/RecordFilePoller.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/util/Utility.java
  hedera-mirror-importer/src/main/resources/log4j2.xml
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/util/UtilityTest.java
  hedera-mirror-importer/src/test/resources/db/scripts/cleanup_V1.28.1.sql
  hedera-mirror-importer/src/test/resources/log4j2-test.xml
  hedera-mirror-monitor/src/main/resources/log4j2.xml
  hedera-mirror-monitor/src/test/resources/log4j2-test.xml
  hedera-mirror-rest/middleware/httpErrorHandler.js
  hedera-mirror-rest/server.js
  hedera-mirror-rest/transactionId.js
  hedera-mirror-test/src/test/conf/log4j2.xml
  hedera-mirror-test/src/test/resources/log4j2.xml
Labels: P2, enhancement

#1278 Add OpenAPI 3.0 Support
  docs/configuration.md
  docs/operations.md
  hedera-mirror-rest/api/v1/openapi.yml
  hedera-mirror-rest/config/application.yml
  hedera-mirror-rest/middleware/httpErrorHandler.js
  hedera-mirror-rest/middleware/metricsHandler.js
  hedera-mirror-rest/middleware/openapiHandler.js
  hedera-mirror-rest/middleware/responseHandler.js
  hedera-mirror-rest/package-lock.json
  hedera-mirror-rest/package.json
  hedera-mirror-rest/server.js
  pom.xml
Labels: P2, documentation, enhancement, rest

#1284 Update sdk to 1.3.3 to support hts changes
  charts/hedera-mirror-common/Chart.yaml
  charts/hedera-mirror-grpc/Chart.yaml
  charts/hedera-mirror-importer/Chart.yaml
  charts/hedera-mirror-monitor/Chart.yaml
  charts/hedera-mirror-rest/Chart.yaml
  charts/hedera-mirror/Chart.yaml
  charts/hedera-mirror/requirements.lock
  docker-compose.yml
  hedera-mirror-coverage/pom.xml
  hedera-mirror-datagenerator/pom.xml
  hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/token/TokenUpdateTransactionSupplier.java
  hedera-mirror-grpc/pom.xml
  hedera-mirror-importer/pom.xml
  hedera-mirror-monitor/pom.xml
  hedera-mirror-protobuf/pom.xml
  hedera-mirror-rest/monitoring/monitor_apis/package-lock.json
  hedera-mirror-rest/monitoring/monitor_apis/package.json
  hedera-mirror-rest/package-lock.json
  hedera-mirror-rest/package.json
  hedera-mirror-rest/pom.xml
  hedera-mirror-test/pom.xml
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
  hedera-mirror-test/src/test/resources/k8s/hcs-perf-message-submit.yml
  hedera-mirror-test/src/test/resources/k8s/hcs-perf-publish-test.yml
  hedera-mirror-test/src/test/resources/k8s/hcs-perf-subscribe-test.yml
  hedera-mirror-test/src/test/resources/k8s/hts-perf-batch-publish-batch-validate.yml
  hedera-mirror-test/src/test/resources/k8s/hts-perf-publish-and-retrieve.yml
  pom.xml
Labels: P1, enhancement

#1292 Remove two no longer applicable HTS acceptance tests
  hedera-mirror-test/src/test/resources/features/hts/hts.feature
Labels: P1, bug, test

#1282 Improve gRPC missing message handling in TopicMessageService
  docs/configuration.md
  hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/retriever/PollingTopicMessageRetriever.java
  hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/retriever/RetrieverProperties.java
  hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/retriever/TopicMessageRetriever.java
  hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/service/TopicMessageServiceImpl.java
  hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/listener/AbstractSharedTopicListenerTest.java
  hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/retriever/PollingTopicMessageRetrieverTest.java
  hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/service/TopicMessageServiceTest.java
Labels: P2, bug, grpc

#1293 Update SDK to 1.3.3 to support HTS changes
  hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/token/TokenUpdateTransactionSupplier.java
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
  hedera-mirror-test/src/test/resources/features/hts/hts.feature
  pom.xml
Labels: P1, bug, test

#1296 Fix error in Crypto Transfer Transaction Supplier
  hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/account/CryptoTransferTransactionSupplier.java
Labels: P2, bug, test

#1281 Support Default Credentials Provider for AWS
  charts/marketplace/gcp/schema.yaml
  docs/configuration.md
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/MirrorProperties.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/CredentialsProviderConfiguration.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/condition/AwsAssumeRoleCondition.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/condition/StaticCredentialsCondition.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/CommonDownloaderProperties.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/config/condition/AwsAssumeRoleConditionTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/config/condition/StaticCredentialsConditionTest.java
Labels: P2, downloader, enhancement
