Repository hiero-ledger/hiero-mirror-node, pull requests merged in 2021-12, with the labels that each got.

#2922 Fix importer tests failure
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/PubSubMessageTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/RecordFileParserPerformanceTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerContractTest.java
  hedera-mirror-importer/src/test/resources/data/pubsub-messages.txt
Labels: bug, P1

#2878 Rosetta bdd client
  .github/workflows/rosetta-api.yml
  hedera-mirror-rosetta/app/errors/errors.go
  hedera-mirror-rosetta/app/interfaces/transaction.go
  hedera-mirror-rosetta/app/interfaces/transaction_repository.go
  hedera-mirror-rosetta/app/persistence/transaction.go
  hedera-mirror-rosetta/app/persistence/transaction_test.go
  hedera-mirror-rosetta/app/services/account_service.go
  hedera-mirror-rosetta/app/services/account_service_test.go
  hedera-mirror-rosetta/app/services/base_service.go
  hedera-mirror-rosetta/app/services/base_service_test.go
  hedera-mirror-rosetta/app/services/block_service.go
  hedera-mirror-rosetta/app/services/block_service_test.go
  hedera-mirror-rosetta/app/services/construction/token_update_transaction_constructor_test.go
  hedera-mirror-rosetta/app/services/construction_service.go
  hedera-mirror-rosetta/app/services/construction_service_test.go
  hedera-mirror-rosetta/app/services/network_service.go
  hedera-mirror-rosetta/app/services/network_service_test.go
  hedera-mirror-rosetta/go.mod
  hedera-mirror-rosetta/go.sum
  hedera-mirror-rosetta/main.go
  hedera-mirror-rosetta/pom.xml
  hedera-mirror-rosetta/scripts/validation/demo/validation.json
  hedera-mirror-rosetta/scripts/validation/run-validation.sh
  hedera-mirror-rosetta/scripts/validation/testnet/validate-construction.json
  hedera-mirror-rosetta/scripts/validation/testnet/validation.json
  hedera-mirror-rosetta/test/bdd-client/README.md
  hedera-mirror-rosetta/test/bdd-client/client/client.go
  hedera-mirror-rosetta/test/bdd-client/client/config.go
  hedera-mirror-rosetta/test/bdd-client/config.go
  hedera-mirror-rosetta/test/bdd-client/features/crypto.feature
  hedera-mirror-rosetta/test/bdd-client/features/token.feature
  hedera-mirror-rosetta/test/bdd-client/main_test.go
  hedera-mirror-rosetta/test/bdd-client/scenario/asserter.go
  hedera-mirror-rosetta/test/bdd-client/scenario/common.go
  hedera-mirror-rosetta/test/bdd-client/scenario/crypto.go
  hedera-mirror-rosetta/test/bdd-client/scenario/token.go
  hedera-mirror-rosetta/test/mocks/transaction_repository.go
Labels: enhancement, P1, rosetta

#2931 Add support for HTS precompiles
  docs/operations.md
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Transaction.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
  hedera-mirror-importer/src/main/resources/db/migration/v1/V1.50.2__hts_precompiles.sql
  hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.0__create_tables.sql
  hedera-mirror-importer/src/main/resources/db/scripts/v2/alterSchema.sql
  hedera-mirror-importer/src/main/resources/db/scripts/v2/csvBackupTables.sql
  hedera-mirror-importer/src/main/resources/db/scripts/v2/csvRestoreTables.sql
  hedera-mirror-importer/src/main/resources/db/scripts/v2/migration.config
  hedera-mirror-importer/src/main/resources/db/scripts/v2/migration.sh
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/TransferTransactionPayerMigrationTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/batch/BatchInserterTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerContractTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/repository/TransactionRepositoryTest.java
  hedera-mirror-rest/model/transaction.js
  hedera-mirror-rest/model/transactionResult.js
  hedera-mirror-rosetta/app/domain/types/constants.go
  hedera-mirror-rosetta/app/persistence/domain/transaction.go
  hedera-mirror-rosetta/app/persistence/testmain_test.go
Labels: enhancement, P1, parser

#2958 Fix image build failures after adding common module
  hedera-mirror-rosetta/build/Dockerfile
  hedera-mirror-test/src/main/resources/Dockerfile
Labels: bug, P1, test

#2923 Add Contract Results by timestamp and transactionId REST API
  docs/design/smart-contracts.md
  hedera-mirror-rest/__tests__/controllers/contractController.test.js
  hedera-mirror-rest/__tests__/integrationDomainOps.js
  hedera-mirror-rest/__tests__/service/contractService.test.js
  hedera-mirror-rest/__tests__/service/recordFileService.test.js
  hedera-mirror-rest/__tests__/service/transactionService.test.js
  hedera-mirror-rest/__tests__/specs/contracts-result-details-01-timestamp.spec.json
  hedera-mirror-rest/__tests__/specs/contracts-result-details-02-timestamp-not-found.spec.json
  hedera-mirror-rest/__tests__/specs/contracts-result-details-03-invalid-timestamp.spec.json
  hedera-mirror-rest/__tests__/specs/contracts-result-details-04-transactionid.spec.json
  hedera-mirror-rest/__tests__/specs/contracts-result-details-05-transactionid-result-not-found.spec.json
  hedera-mirror-rest/__tests__/specs/contracts-result-details-06-transactionid-transaction-not-found.spec.json
  hedera-mirror-rest/__tests__/specs/contracts-result-details-07-invalid-transactionid.spec.json
  hedera-mirror-rest/__tests__/specs/contracts-results-01-specific-id.spec.json
  hedera-mirror-rest/__tests__/specs/contracts-results-02-from.spec.json
  hedera-mirror-rest/__tests__/specs/contracts-results-03-timestamp.spec.json
  hedera-mirror-rest/__tests__/specs/contracts-results-05-order.spec.json
  hedera-mirror-rest/__tests__/specs/contracts-results-06-limit.spec.json
  hedera-mirror-rest/__tests__/specs/contracts-results-07-all-params.spec.json
  hedera-mirror-rest/__tests__/specs/contracts-results-08-from-address.spec.json
  hedera-mirror-rest/api/v1/openapi.yml
  hedera-mirror-rest/controllers/contractController.js
  hedera-mirror-rest/model/index.js
  hedera-mirror-rest/model/recordFile.js
  hedera-mirror-rest/model/transaction.js
  hedera-mirror-rest/routes/contractRoute.js
  hedera-mirror-rest/service/baseService.js
  hedera-mirror-rest/service/contractService.js
  hedera-mirror-rest/service/index.js
  hedera-mirror-rest/service/recordFileService.js
  hedera-mirror-rest/service/transactionService.js
  hedera-mirror-rest/utils.js
  hedera-mirror-rest/viewmodel/contractResultViewModel.js
Labels: enhancement, P1, rest

#2957 Rosetta HTS bdd tests
  .github/workflows/rosetta-api.yml
  hedera-mirror-rosetta/app/domain/types/amount.go
  hedera-mirror-rosetta/app/domain/types/amount_test.go
  hedera-mirror-rosetta/app/domain/types/constants_test.go
  hedera-mirror-rosetta/app/errors/errors.go
  hedera-mirror-rosetta/app/errors/errors_test.go
  hedera-mirror-rosetta/app/services/construction/common.go
  hedera-mirror-rosetta/app/services/construction/common_test.go
  hedera-mirror-rosetta/app/services/construction/crypto_transfer_transaction_constructor_test.go
  hedera-mirror-rosetta/app/services/construction/token_burn_mint_transaction_constructor.go
  hedera-mirror-rosetta/app/services/construction/token_burn_mint_transaction_constructor_test.go
  hedera-mirror-rosetta/app/services/construction/token_create_transaction_constructor.go
  hedera-mirror-rosetta/app/services/construction/token_create_transaction_constructor_test.go
  hedera-mirror-rosetta/app/services/construction/token_update_transaction_constructor.go
  hedera-mirror-rosetta/app/services/construction_service.go
  hedera-mirror-rosetta/go.mod
  hedera-mirror-rosetta/go.sum
  hedera-mirror-rosetta/scripts/validation/testnet/validation.json
  hedera-mirror-rosetta/test/bdd-client/README.md
  hedera-mirror-rosetta/test/bdd-client/client/client.go
  hedera-mirror-rosetta/test/bdd-client/client/config.go
  hedera-mirror-rosetta/test/bdd-client/config.go
  hedera-mirror-rosetta/test/bdd-client/features/crypto.feature
  hedera-mirror-rosetta/test/bdd-client/features/token.feature
  hedera-mirror-rosetta/test/bdd-client/scenario/asserter.go
  hedera-mirror-rosetta/test/bdd-client/scenario/base.go
  hedera-mirror-rosetta/test/bdd-client/scenario/common.go
  hedera-mirror-rosetta/test/bdd-client/scenario/crypto.go
  hedera-mirror-rosetta/test/bdd-client/scenario/token.go
Labels: enhancement, P1, rosetta

#2963 Fix failing pubsub tests
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/PubSubMessageTest.java
  hedera-mirror-importer/src/test/resources/data/pubsub-messages.txt
  pom.xml
Labels: bug, P1, parser

#2965 Fix rosetta-cli configuration typo
  hedera-mirror-rosetta/scripts/validation/demo/validation.json
  hedera-mirror-rosetta/scripts/validation/testnet/validation.json
  hedera-mirror-rosetta/test/bdd-client/README.md
  hedera-mirror-rosetta/test/bdd-client/config.go
Labels: bug, P1, rosetta

#2971 Fix artifact name clash in rosetta-api.yml
  .github/workflows/rosetta-api.yml
Labels: bug, P1, rosetta

#2972 Fix artifact name clash in rosetta-api.yml (0.46)
  .github/workflows/rosetta-api.yml
Labels: bug, P1, rosetta

#2973 Timeout chart workflow
  .github/ct.yaml
  .github/workflows/auto-release.yml
  .github/workflows/charts.yml
  .github/workflows/grpc-api.yml
  .github/workflows/importer.yml
  .github/workflows/monitor.yml
  .github/workflows/release-integration.yml
  .github/workflows/release-production.yml
  .github/workflows/security.yml
  .github/workflows/windows.yml
Labels: bug, P1, process

#2976 Bump log4j2 to 2.15.0
  pom.xml
Labels: P1, dependencies

#2975 Bump Log4j2 to 2.15.0 (0.45)
  pom.xml
Labels: P1, dependencies

#2977 Bump log4j2 to 2.15.0 (0.46)
  pom.xml
Labels: P1, dependencies

#2978 Bump log4j2 to 2.15.0 (0.44)
  pom.xml
Labels: P1, dependencies

#2979 Bump log4j2 to 2.15.0 (0.43)
  hedera-mirror-grpc/src/main/resources/log4j2.xml
  hedera-mirror-grpc/src/test/resources/log4j2-test.xml
  hedera-mirror-importer/src/main/resources/log4j2.xml
  hedera-mirror-importer/src/test/resources/log4j2-test.xml
  hedera-mirror-monitor/src/main/resources/log4j2.xml
  hedera-mirror-monitor/src/test/resources/log4j2-test.xml
  hedera-mirror-test/src/test/resources/log4j2.xml
  pom.xml
Labels: P1, dependencies

#2980 Disable log4j2 message lookups
  hedera-mirror-grpc/src/main/resources/log4j2.xml
  hedera-mirror-grpc/src/test/resources/log4j2-test.xml
  hedera-mirror-importer/src/main/resources/log4j2.xml
  hedera-mirror-importer/src/test/resources/log4j2-test.xml
  hedera-mirror-monitor/src/main/resources/log4j2.xml
  hedera-mirror-monitor/src/test/resources/log4j2-test.xml
  hedera-mirror-test/src/test/resources/log4j2.xml
Labels: P1, dependencies

#2974 List contracts in descending order by default
  hedera-mirror-rest/__tests__/controllers/contractController.test.js
  hedera-mirror-rest/__tests__/specs/contracts-09-no-args.spec.json
  hedera-mirror-rest/__tests__/specs/contracts-10-order-asc.spec.json
  hedera-mirror-rest/__tests__/specs/contracts-11-limit.spec.json
  hedera-mirror-rest/__tests__/specs/contracts-13-multiple-contract-ids.spec.json
  hedera-mirror-rest/api/v1/openapi.yml
  hedera-mirror-rest/controllers/contractController.js
Labels: enhancement, P2, rest

#2998 Update GCP Marketplace release with log4j2 fix (0.42)
  charts/marketplace/gcp/schema.yaml
  hedera-mirror-grpc/src/main/resources/log4j2.xml
  hedera-mirror-grpc/src/test/resources/log4j2-test.xml
  hedera-mirror-importer/src/main/resources/log4j2.xml
  hedera-mirror-importer/src/test/resources/log4j2-test.xml
  hedera-mirror-monitor/src/main/resources/log4j2.xml
  hedera-mirror-monitor/src/test/resources/log4j2-test.xml
  hedera-mirror-test/src/test/resources/log4j2.xml
  pom.xml
Labels: P1, dependencies

#3000 Fix account balance file ingestion performance issue
  hedera-mirror-importer/src/main/resources/db/migration/v1/V1.51.0__drop_account_balance_index.sql
  hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.3__index_init.sql
  hedera-mirror-rest/accounts.js
Labels: bug, P1, parser, database

#3001 Fix account balance file ingestion performance issue (0.46)
  hedera-mirror-importer/src/main/resources/db/migration/v1/V1.51.0__drop_account_balance_index.sql
  hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.3__index_init.sql
  hedera-mirror-rest/accounts.js
Labels: bug, P1, performance, parser, database

#2944 Add root_contract_id to contract_log migration
  hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/contract/ContractLog.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/AbstractContractCallTransactionHandler.java
  hedera-mirror-importer/src/main/resources/db/migration/v1/V1.51.1__contract_logs_root_id.sql
  hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.0__create_tables.sql
  hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.3__index_init.sql
  hedera-mirror-importer/src/main/resources/db/scripts/v2/csvRestoreTables.sql
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/AddRootContractIdMigrationTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerContractTest.java
Labels: P3, parser, database

#3004 Bump log4j2 from 2.15.0 to 2.16.0
  hedera-mirror-grpc/src/main/resources/log4j2.xml
  hedera-mirror-grpc/src/test/resources/log4j2-test.xml
  hedera-mirror-importer/src/main/resources/log4j2.xml
  hedera-mirror-importer/src/test/resources/log4j2-test.xml
  hedera-mirror-monitor/src/main/resources/log4j2.xml
  hedera-mirror-monitor/src/test/resources/log4j2-test.xml
  hedera-mirror-test/src/test/resources/log4j2.xml
  pom.xml
Labels: P1, dependencies

#3002 Convert contract_log topics from string to bytea
  docs/design/smart-contracts.md
  hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/contract/ContractLog.java
  hedera-mirror-common/src/test/java/com/hedera/mirror/common/util/DomainUtilsTest.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/ContractResultMigration.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/util/Utility.java
  hedera-mirror-importer/src/main/resources/db/migration/v1/V1.51.2__contract_logs_convert_topics_to_bytes.sql
  hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.0__create_tables.sql
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/domain/DomainBuilder.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/ContractLogsConvertTopicsToBytesMigrationTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/util/UtilityTest.java
Labels: P2, parser, database

#3005 Update GCP marketplace to match deployed images
  charts/marketplace/gcp/open-source-compliance/mirror-java-licenses.txt
  charts/marketplace/gcp/open-source-compliance/mirror-java-sources.txt
  charts/marketplace/gcp/values.yaml
Labels: enhancement, P3, marketplace

#3003 Add contract results support to acceptance tests
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/MirrorNodeClient.java
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/props/MirrorContractResult.java
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/response/MirrorContractResultResponse.java
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/response/MirrorContractResultsResponse.java
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ContractFeature.java
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/util/FeatureInputHandler.java
  hedera-mirror-test/src/test/resources/features/contract/contract.feature
  hedera-mirror-test/src/test/resources/solidity/README.md
  hedera-mirror-test/src/test/resources/solidity/artifacts/contracts/Parent.sol/Child.json
  hedera-mirror-test/src/test/resources/solidity/artifacts/contracts/Parent.sol/Parent.json
  hedera-mirror-test/src/test/resources/solidity/contracts/Parent.sol
  hedera-mirror-test/src/test/resources/solidity/test/parent-child-test.js
Labels: enhancement, P1, test

#3008 Update REST models to use getFullName
  hedera-mirror-rest/model/assessedCustomFee.js
  hedera-mirror-rest/model/cryptoTransfer.js
  hedera-mirror-rest/model/customFee.js
  hedera-mirror-rest/model/nft.js
  hedera-mirror-rest/model/nftTransfer.js
  hedera-mirror-rest/model/tokenTransfer.js
  hedera-mirror-rest/model/transaction.js
  hedera-mirror-rest/tokens.js
  hedera-mirror-rest/transactions.js
Labels: enhancement, P3, rest

#3009 Add contract results support to acceptance tests (0.46)
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/MirrorNodeClient.java
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/props/MirrorContractResult.java
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/response/MirrorContractResultResponse.java
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/response/MirrorContractResultsResponse.java
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ContractFeature.java
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/util/FeatureInputHandler.java
  hedera-mirror-test/src/test/resources/features/contract/contract.feature
  hedera-mirror-test/src/test/resources/solidity/README.md
  hedera-mirror-test/src/test/resources/solidity/artifacts/contracts/Parent.sol/Child.json
  hedera-mirror-test/src/test/resources/solidity/artifacts/contracts/Parent.sol/Parent.json
  hedera-mirror-test/src/test/resources/solidity/contracts/Parent.sol
  hedera-mirror-test/src/test/resources/solidity/test/parent-child-test.js
Labels: enhancement, P2, test

#3016 Bump swagger-ui-express from 4.2.0 to 4.3.0
  hedera-mirror-rest/package-lock.json
  hedera-mirror-rest/package.json
Labels: dependencies

#3017 Bump swagger-ui-express from 4.2.0 to 4.3.0 (0.46)
  hedera-mirror-rest/package-lock.json
  hedera-mirror-rest/package.json
Labels: dependencies

#3019 Bump json-schema from 0.2.3 to 0.4.0
  hedera-mirror-rest/package-lock.json
  hedera-mirror-rest/package.json
Labels: dependencies

#3020 Bump json-schema from 0.2.3 to 0.4.0 (0.46)
  hedera-mirror-rest/package-lock.json
  hedera-mirror-rest/package.json
Labels: dependencies

#3018 Fix accounts query with balance only query param performance regression
  hedera-mirror-rest/accounts.js
  hedera-mirror-rest/api/v1/openapi.yml
Labels: bug, P1, performance, regression, rest

#3023 Fix accounts query with balance only query param performance regression (0.46)
  hedera-mirror-rest/accounts.js
  hedera-mirror-rest/api/v1/openapi.yml
Labels: bug, P1, performance, regression, rest

#3021 Increase wait time in rosetta-api github workflow
  .github/workflows/rosetta-api.yml
Labels: enhancement, P3, test, rosetta

#3026 Bump log4j2 from 2.16.0 to 2.17.0
  pom.xml
Labels: dependencies

#3051 Fix test image build
  hedera-mirror-test/src/main/resources/Dockerfile
Labels: bug, P1, process

#3054 Downgrade flyway from 8.0.4 to 7.15.0 for PostgreSQL 9.6 compatibility
  hedera-mirror-grpc/src/test/resources/config/bootstrap.yml
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/MirrorBaseJavaMigration.java
  hedera-mirror-importer/src/test/resources/config/bootstrap.yml
  hedera-mirror-rest/__tests__/integrationDbOps.js
  hedera-mirror-rosetta/test/db/db.go
  hedera-mirror-web3/src/test/resources/bootstrap.yml
  pom.xml
Labels: bug, P1, parser

#3055 Default maven to --also-make
  .github/workflows/charts.yml
  .github/workflows/grpc-api.yml
  .github/workflows/importer.yml
  .github/workflows/monitor.yml
  .github/workflows/rest-api.yml
  .github/workflows/rosetta-api.yml
  .github/workflows/web3.yml
  .mvn/maven.config
  .mvn/wrapper/maven-wrapper.properties
  hedera-mirror-rosetta/build/Dockerfile
  hedera-mirror-test/src/main/resources/Dockerfile
Labels: enhancement, P3, process

#3057 Fix auto created account alias not cached
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/CacheConfiguration.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/AbstractEntityRecordItemListenerTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerCryptoTest.java
  pom.xml
  suppressions.xml
Labels: bug, P1, parser

#3060 Fix auto created account alias not cached (0.46)
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/CacheConfiguration.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/AbstractEntityRecordItemListenerTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerCryptoTest.java
  pom.xml
  suppressions.xml
Labels: bug, P1, parser

#3059 Fix auto created account alias not cached (0.47)
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/CacheConfiguration.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/AbstractEntityRecordItemListenerTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerCryptoTest.java
  pom.xml
  suppressions.xml
Labels: bug, P1, parser

#3058 Downgrade Flyway from 8.0.4 to 7.15.0 for PostgreSQL 9.6 compatibility (0.47)
  hedera-mirror-grpc/src/test/resources/config/bootstrap.yml
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/MirrorBaseJavaMigration.java
  hedera-mirror-importer/src/test/resources/config/bootstrap.yml
  hedera-mirror-rest/__tests__/integrationDbOps.js
  hedera-mirror-rosetta/test/db/db.go
  hedera-mirror-web3/src/test/resources/bootstrap.yml
  pom.xml
Labels: bug, P1, parser

#3063 Add parent_consensus_timestamp to REST API
  hedera-mirror-rest/__tests__/integrationDomainOps.js
  hedera-mirror-rest/__tests__/specs/accounts-10-account-transactions.spec.json
  hedera-mirror-rest/__tests__/specs/accounts-14-account-transactions-transactiontype.spec.json
  hedera-mirror-rest/__tests__/specs/accounts-18-account-transactions-no-balances.spec.json
  hedera-mirror-rest/__tests__/specs/accounts-19-account-transactions-timestamp.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-01-no-args.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-02-specific-id.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-04-timestamp.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-05-success-result.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-06-fail-result.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-07-credit-type.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-08-debit-type.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-09-account-id.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-10-all-params.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-15-limit.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-16-specific-id-tokentransfer.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-17-transaction-type.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-18-specific-id-no-transfers.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-19-timestamp-no-transfers.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-20-specific-id-scheduled-true.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-22-specific-id-scheduled-false.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-24-specific-id-repeated-valid-params-schedule-false.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-25-specific-id-repeated-valid-params-schedule-true.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-27-multiple-account-ids.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-28-account-id-only-token-transfers.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-29-tokenwipe.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-30-specific-id-tokenwipe.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-31-credit-type-only-token-transfers.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-32-debit-type-only-token-transfers.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-33-credit-type-crypto-and-token-transfers.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-34-debit-type-crypto-and-token-transfers.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-35-duplicate-token-transfers-bug.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-36-nft-transfers.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-37-specific-id-nft-transfers.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-38-nft-transfers-multiple-tokens.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-39-specific-id-assessed-custom-fees.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-40-specific-id-assessed-custom-fees-with-effective-payer-account-ids.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-41-unknown-result.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-42-specific-id-return-multiple-nonce.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-43-specific-id-nonce.spec.json
  hedera-mirror-rest/__tests__/transactions.test.js
  hedera-mirror-rest/api/v1/openapi.yml
  hedera-mirror-rest/transactions.js
Labels: enhancement, P2, rest

#3085 Bump log4j2 to 2.17.1 (0.47)
  pom.xml
Labels: dependencies

#3084 Bump log4j2 to 2.17.1
  pom.xml
Labels: dependencies
