Repository hiero-ledger/hiero-mirror-node, pull requests merged in 2021-04, with the labels that each got.

#1778 Backport monitor multi scenario
  docs/configuration.md
  hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/config/MonitorConfiguration.java
  hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/generator/CompositeTransactionGenerator.java
  hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/generator/ConfigurableTransactionGenerator.java
  hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/generator/ScenarioProperties.java
  hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/generator/TransactionGenerator.java
  hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/PublishMetrics.java
  hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/PublishProperties.java
  hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/generator/CompositeTransactionGeneratorTest.java
  hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/generator/ConfigurableTransactionGeneratorTest.java
Labels: P2, bug, monitor

#1791 Expose entity_id in transactions REST API
  hedera-mirror-rest/__tests__/integrationDomainOps.js
  hedera-mirror-rest/__tests__/mockpool.js
  hedera-mirror-rest/__tests__/specs/accounts-10-account-transactions.spec.json
  hedera-mirror-rest/__tests__/specs/accounts-14-account-transactions-transactiontype.spec.json
  hedera-mirror-rest/__tests__/specs/accounts-18-account-transactions-no-balances.spec.json
  hedera-mirror-rest/__tests__/specs/accounts-19-account-transactions-timestamp.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-01-no-args.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-02-specific-id.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-04-timestamp.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-05-success-result.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-06-fail-result.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-07-credit-type.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-08-debit-type.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-09-account-id.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-10-all-params.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-11-not-found.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-14-repeated-valid-params.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-15-limit.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-16-specific-id-tokentransfer.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-17-transaction-type.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-18-specific-id-no-transfers.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-19-timestamp-no-transfers.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-20-specific-id-scheduled-true.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-21-specific-id-scheduled-true-not-found.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-22-specific-id-scheduled-false.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-24-specific-id-repeated-valid-params-schedule-false.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-25-specific-id-repeated-valid-params-schedule-true.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-27-multiple-account-ids.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-28-account-id-only-token-transfers.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-29-tokenwipe.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-30-specific-id-tokenwipe.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-31-credit-type-only-token-transfers.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-32-debit-type-only-token-transfers.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-33-credit-type-crypyo-and-token-transfers.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-34-debit-type-crypyo-and-token-transfers.spec.json
  hedera-mirror-rest/__tests__/transactions.test.js
  hedera-mirror-rest/transactions.js
Labels: P2, enhancement, javascript, rest

#1808 Bump versions for v0.30.0
  charts/hedera-mirror-common/Chart.yaml
  charts/hedera-mirror-grpc/Chart.yaml
  charts/hedera-mirror-importer/Chart.yaml
  charts/hedera-mirror-monitor/Chart.yaml
  charts/hedera-mirror-rest/Chart.yaml
  charts/hedera-mirror/Chart.yaml
  charts/hedera-mirror/requirements.lock
  docker-compose.yml
  hedera-mirror-rest/api/v1/openapi.yml
  hedera-mirror-rest/monitoring/monitor_apis/package-lock.json
  hedera-mirror-rest/monitoring/monitor_apis/package.json
  hedera-mirror-rest/package-lock.json
  hedera-mirror-rest/package.json
  hedera-mirror-rosetta/config/application.yml
  hedera-mirror-test/src/test/resources/k8s/hcs-perf-message-submit.yml
  hedera-mirror-test/src/test/resources/k8s/hcs-perf-publish-test.yml
  hedera-mirror-test/src/test/resources/k8s/hcs-perf-subscribe-test.yml
  hedera-mirror-test/src/test/resources/k8s/hts-perf-batch-publish-batch-validate.yml
  hedera-mirror-test/src/test/resources/k8s/hts-perf-publish-and-retrieve.yml
  pom.xml
Labels: P1, enhancement, process

#1807 Port multi-scenario running longer fix
  hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/generator/CompositeTransactionGenerator.java
  hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/generator/ConfigurableTransactionGenerator.java
  hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/PublishMetrics.java
  hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/generator/CompositeTransactionGeneratorTest.java
Labels: P2, bug, monitor

#1797 Change importer to Deployment & bump dependencies
  charts/hedera-mirror-common/Chart.lock
  charts/hedera-mirror-common/Chart.yaml
  charts/hedera-mirror-common/values.yaml
  charts/hedera-mirror-importer/templates/deployment.yaml
  charts/hedera-mirror-importer/templates/service.yaml
  charts/hedera-mirror-importer/values.yaml
  charts/hedera-mirror-monitor/templates/deployment.yaml
  charts/hedera-mirror-monitor/values.yaml
  charts/hedera-mirror/Chart.lock
  charts/hedera-mirror/Chart.yaml
  charts/hedera-mirror/ci/timescaledb-values.yaml
  charts/hedera-mirror/values.yaml
  docker-compose.yml
  hedera-mirror-grpc/src/test/resources/config/bootstrap-v2.yml
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/MetricsConfiguration.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/db/DBProperties.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/HistoricalAccountInfoMigration.java
  hedera-mirror-importer/src/test/resources/config/bootstrap-v2.yml
  hedera-mirror-rest/__tests__/integrationDbOps.js
Labels: P2, enhancement

#1817 Fix REST API image
  hedera-mirror-rest/.maven-dockerignore
  hedera-mirror-rest/package.json
  pom.xml
Labels: P1, bug, process

#1798 Fixes to the timescale migration script
  hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.0__time_scale_init.sql
  hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.4__reference_table_inserts.sql
  hedera-mirror-importer/src/main/resources/db/scripts/timescaledb/csvBackupTables.sql
  hedera-mirror-importer/src/main/resources/db/scripts/timescaledb/csvRestoreTables.sql
  hedera-mirror-rest/__tests__/integrationDomainOps.js
Labels: P2, database, enhancement, process

#1818 Bump versions for v0.31.0-rc1
  charts/hedera-mirror-common/Chart.yaml
  charts/hedera-mirror-grpc/Chart.yaml
  charts/hedera-mirror-importer/Chart.yaml
  charts/hedera-mirror-monitor/Chart.yaml
  charts/hedera-mirror-rest/Chart.yaml
  charts/hedera-mirror/Chart.lock
  charts/hedera-mirror/Chart.yaml
  charts/hedera-mirror/ci/timescaledb-values.yaml
  docker-compose.yml
  hedera-mirror-rest/api/v1/openapi.yml
  hedera-mirror-rest/monitoring/monitor_apis/package-lock.json
  hedera-mirror-rest/monitoring/monitor_apis/package.json
  hedera-mirror-rest/package-lock.json
  hedera-mirror-rest/package.json
  hedera-mirror-rosetta/config/application.yml
  hedera-mirror-test/src/test/resources/k8s/hcs-perf-message-submit.yml
  hedera-mirror-test/src/test/resources/k8s/hcs-perf-publish-test.yml
  hedera-mirror-test/src/test/resources/k8s/hcs-perf-subscribe-test.yml
  hedera-mirror-test/src/test/resources/k8s/hts-perf-batch-publish-batch-validate.yml
  hedera-mirror-test/src/test/resources/k8s/hts-perf-publish-and-retrieve.yml
  pom.xml
Labels: P1, enhancement, process

#1826 fix test failure caused by timing precision
  hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/generator/CompositeTransactionGeneratorTest.java
Labels: bug, monitor, test

#1823 Expose transaction bytes in REST API
  hedera-mirror-rest/__tests__/integrationDomainOps.js
  hedera-mirror-rest/__tests__/mockpool.js
  hedera-mirror-rest/__tests__/specs/accounts-10-account-transactions.spec.json
  hedera-mirror-rest/__tests__/specs/accounts-14-account-transactions-transactiontype.spec.json
  hedera-mirror-rest/__tests__/specs/accounts-18-account-transactions-no-balances.spec.json
  hedera-mirror-rest/__tests__/specs/accounts-19-account-transactions-timestamp.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-01-no-args.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-02-specific-id.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-04-timestamp.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-05-success-result.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-06-fail-result.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-07-credit-type.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-08-debit-type.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-09-account-id.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-10-all-params.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-15-limit.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-16-specific-id-tokentransfer.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-17-transaction-type.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-18-specific-id-no-transfers.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-19-timestamp-no-transfers.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-20-specific-id-scheduled-true.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-22-specific-id-scheduled-false.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-24-specific-id-repeated-valid-params-schedule-false.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-25-specific-id-repeated-valid-params-schedule-true.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-27-multiple-account-ids.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-28-account-id-only-token-transfers.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-29-tokenwipe.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-30-specific-id-tokenwipe.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-31-credit-type-only-token-transfers.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-32-debit-type-only-token-transfers.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-33-credit-type-crypyo-and-token-transfers.spec.json
  hedera-mirror-rest/__tests__/specs/transactions-34-debit-type-crypyo-and-token-transfers.spec.json
  hedera-mirror-rest/transactions.js
Labels: P2, enhancement, rest

#1827 Fix dashboards and alerts
  .github/workflows/grpc-api.yml
  .github/workflows/importer.yml
  .github/workflows/monitor.yml
  .github/workflows/release-development.yml
  .github/workflows/rest-api.yml
  charts/hedera-mirror-common/dashboards/hedera-mirror-grpc.json
  charts/hedera-mirror-common/dashboards/hedera-mirror-importer.json
  charts/hedera-mirror-common/dashboards/hedera-mirror-monitor.json
  charts/hedera-mirror-common/dashboards/hedera-mirror-rest.json
  charts/hedera-mirror-common/values.yaml
  charts/hedera-mirror/templates/podmonitor-timescaledb.yaml
  charts/hedera-mirror/values-prod.yaml
  charts/hedera-mirror/values.yaml
Labels: P2, bug, ops

#1816 Improve monitor performance
  docs/configuration.md
  docs/monitor.md
  hedera-mirror-monitor/pom.xml
  hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/config/MonitorConfiguration.java
  hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/expression/ExpressionConverterImpl.java
  hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/generator/ConfigurableTransactionGenerator.java
  hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/generator/ScenarioProperties.java
  hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/PublishMetrics.java
  hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/PublishProperties.java
  hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/PublishRequest.java
  hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/TransactionPublisher.java
  hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/expression/ExpressionConverterImplTest.java
Labels: P1, bug, monitor, regression

#1843 Bump versions for v0.31.0
  charts/hedera-mirror-common/Chart.yaml
  charts/hedera-mirror-grpc/Chart.yaml
  charts/hedera-mirror-importer/Chart.yaml
  charts/hedera-mirror-monitor/Chart.yaml
  charts/hedera-mirror-rest/Chart.yaml
  charts/hedera-mirror/Chart.lock
  charts/hedera-mirror/Chart.yaml
  docker-compose.yml
  hedera-mirror-rest/api/v1/openapi.yml
  hedera-mirror-rest/monitoring/monitor_apis/package-lock.json
  hedera-mirror-rest/monitoring/monitor_apis/package.json
  hedera-mirror-rest/package-lock.json
  hedera-mirror-rest/package.json
  hedera-mirror-rosetta/config/application.yml
  hedera-mirror-test/src/test/resources/k8s/hcs-perf-message-submit.yml
  hedera-mirror-test/src/test/resources/k8s/hcs-perf-publish-test.yml
  hedera-mirror-test/src/test/resources/k8s/hcs-perf-subscribe-test.yml
  hedera-mirror-test/src/test/resources/k8s/hts-perf-batch-publish-batch-validate.yml
  hedera-mirror-test/src/test/resources/k8s/hts-perf-publish-and-retrieve.yml
  pom.xml
Labels: P1, enhancement, process

#1848 Add cloud storage metrics
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/config/MetricsExecutionInterceptor.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/PendingDownload.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/record/RecordFileDownloader.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/event/EventFileReaderV3.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/reader/event/EventFileReaderV3Test.java
Labels: P2, downloader, enhancement

#1846 Updated scheduled tests
  hedera-mirror-datagenerator/pom.xml
  hedera-mirror-datagenerator/src/main/java/com/hedera/datagenerator/sdk/supplier/schedule/ScheduleCreateTransactionSupplier.java
  hedera-mirror-monitor/pom.xml
  hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/TransactionPublisher.java
  hedera-mirror-test/pom.xml
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AbstractNetworkClient.java
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/ScheduleClient.java
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TopicClient.java
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/AccountFeature.java
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ScheduleFeature.java
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
  hedera-mirror-test/src/test/resources/features/schedule/schedule.feature
  hedera-mirror-test/src/test/resources/features/setup/setup.feature
Labels: P2, enhancement, process, test

#1825 Autovacuum crypto_transfer, token_transfer, and transaction
  charts/hedera-mirror/Chart.lock
  charts/hedera-mirror/Chart.yaml
  charts/hedera-mirror/values.yaml
  docker-compose.yml
  hedera-mirror-grpc/src/test/resources/config/application.yml
  hedera-mirror-grpc/src/test/resources/config/bootstrap-v2.yml
  hedera-mirror-importer/src/main/resources/application.yml
  hedera-mirror-importer/src/main/resources/db/migration/v1/R__autovacuum_insert_only_tables.sql
  hedera-mirror-importer/src/main/resources/db/migration/v2/R__autovacuum_insert_only_tables.sql
  hedera-mirror-importer/src/test/resources/config/bootstrap-v2.yml
  hedera-mirror-rest/__tests__/integrationDbOps.js
Labels: P1, bug, database, rest

#1853 Optimize resources for kubernetes deployment
  charts/hedera-mirror-common/Chart.lock
  charts/hedera-mirror-common/Chart.yaml
  charts/hedera-mirror-importer/values.yaml
  charts/hedera-mirror/Chart.lock
  docs/configuration.md
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/AbstractParserProperties.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/PgCopy.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/BalanceParserProperties.java
  pom.xml
Labels: P2, database, enhancement, parser

#1867 Bump versions for v0.32.0-rc1
  charts/hedera-mirror-common/Chart.yaml
  charts/hedera-mirror-grpc/Chart.yaml
  charts/hedera-mirror-importer/Chart.yaml
  charts/hedera-mirror-monitor/Chart.yaml
  charts/hedera-mirror-rest/Chart.yaml
  charts/hedera-mirror/Chart.lock
  charts/hedera-mirror/Chart.yaml
  docker-compose.yml
  hedera-mirror-rest/api/v1/openapi.yml
  hedera-mirror-rest/monitoring/monitor_apis/package-lock.json
  hedera-mirror-rest/monitoring/monitor_apis/package.json
  hedera-mirror-rest/package-lock.json
  hedera-mirror-rest/package.json
  hedera-mirror-rosetta/config/application.yml
  hedera-mirror-test/src/test/resources/k8s/hcs-perf-message-submit.yml
  hedera-mirror-test/src/test/resources/k8s/hcs-perf-publish-test.yml
  hedera-mirror-test/src/test/resources/k8s/hcs-perf-subscribe-test.yml
  hedera-mirror-test/src/test/resources/k8s/hts-perf-batch-publish-batch-validate.yml
  hedera-mirror-test/src/test/resources/k8s/hts-perf-publish-and-retrieve.yml
  pom.xml
Labels: P1, enhancement, process

#1868 Fix monitor chart's default mirror node hosts
  charts/hedera-mirror-monitor/values.yaml
  charts/hedera-mirror/values.yaml
Labels: P2, monitor

#1874 Exclude fee-free transactions in monitor check
  hedera-mirror-rest/monitoring/monitor_apis/transaction_tests.js
Labels: P2, bug, monitor

#1872 Separate chart version replacer
  pom.xml
Labels: bug, process, regression

#1877 Fix gRPC dashboard
  charts/hedera-mirror-common/dashboards/hedera-mirror-grpc.json
Labels: P3, bug

#1876 Disabled scheduled crypto create in acceptance tests
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
  hedera-mirror-test/src/test/resources/features/schedule/schedule.feature
Labels: P3, enhancement, process, test

#1878 Update js-sdk version and fix columns in entity updater
  hedera-mirror-rest/entity-info-updater/dbEntityService.js
  hedera-mirror-rest/entity-info-updater/package-lock.json
  hedera-mirror-rest/entity-info-updater/package.json
Labels: P1, enhancement, process

#1893 Change helm-gh-pages action to use GITHUB_TOKEN
  .github/workflows/release-production.yml
Labels: P1, enhancement, process

#1894 Fix deadlock due to not cleaning up PostgreSQL CopyIn when error
  charts/hedera-mirror-common/Chart.yaml
  charts/hedera-mirror-grpc/Chart.yaml
  charts/hedera-mirror-importer/Chart.yaml
  charts/hedera-mirror-monitor/Chart.yaml
  charts/hedera-mirror-rest/Chart.yaml
  charts/hedera-mirror/Chart.lock
  charts/hedera-mirror/Chart.yaml
  docker-compose.yml
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/PgCopy.java
  hedera-mirror-rest/api/v1/openapi.yml
  hedera-mirror-rest/monitoring/monitor_apis/package-lock.json
  hedera-mirror-rest/monitoring/monitor_apis/package.json
  hedera-mirror-rest/package-lock.json
  hedera-mirror-rest/package.json
  hedera-mirror-rosetta/config/application.yml
  hedera-mirror-test/src/test/resources/features/schedule/schedule.feature
  hedera-mirror-test/src/test/resources/k8s/hcs-perf-message-submit.yml
  hedera-mirror-test/src/test/resources/k8s/hcs-perf-publish-test.yml
  hedera-mirror-test/src/test/resources/k8s/hcs-perf-subscribe-test.yml
  hedera-mirror-test/src/test/resources/k8s/hts-perf-batch-publish-batch-validate.yml
  hedera-mirror-test/src/test/resources/k8s/hts-perf-publish-and-retrieve.yml
  pom.xml
Labels: P1, bug, parser, regression

#1885 Add a property to override every child chart's tag
  charts/hedera-mirror-grpc/templates/deployment.yaml
  charts/hedera-mirror-grpc/values.yaml
  charts/hedera-mirror-importer/templates/deployment.yaml
  charts/hedera-mirror-importer/values.yaml
  charts/hedera-mirror-monitor/templates/deployment.yaml
  charts/hedera-mirror-monitor/values.yaml
  charts/hedera-mirror-rest/templates/deployment.yaml
  charts/hedera-mirror-rest/templates/tests/configmap.yaml
  charts/hedera-mirror-rest/templates/tests/pod.yaml
  charts/hedera-mirror-rest/values.yaml
Labels: P2, enhancement, process

#1895 Fix deadlock due to not cleaning up PostgreSQL CopyIn when there's an error (master)
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/PgCopy.java
Labels: P1, bug, parser, regression

#1896 Ignore Sonar false positives
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
  hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/generator/ConfigurableTransactionGenerator.java
  hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/TransactionPublisher.java
  pom.xml
Labels: P2, enhancement, process

#1844 Update traefik service type
  charts/README.md
  charts/hedera-mirror-common/values.yaml
  charts/images/mirror_traffic_resource_architecture.png
  hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/config/NettyProperties.java
Labels: P2, enhancement, process

#1901 Bump versions for v0.33.0-alpha1
  charts/hedera-mirror-common/Chart.yaml
  charts/hedera-mirror-grpc/Chart.yaml
  charts/hedera-mirror-importer/Chart.yaml
  charts/hedera-mirror-monitor/Chart.yaml
  charts/hedera-mirror-rest/Chart.yaml
  charts/hedera-mirror/Chart.yaml
  docker-compose.yml
  hedera-mirror-rest/api/v1/openapi.yml
  hedera-mirror-rest/monitoring/monitor_apis/package-lock.json
  hedera-mirror-rest/monitoring/monitor_apis/package.json
  hedera-mirror-rest/package-lock.json
  hedera-mirror-rest/package.json
  hedera-mirror-rosetta/config/application.yml
  hedera-mirror-test/src/test/resources/k8s/hcs-perf-message-submit.yml
  hedera-mirror-test/src/test/resources/k8s/hcs-perf-publish-test.yml
  hedera-mirror-test/src/test/resources/k8s/hcs-perf-subscribe-test.yml
  hedera-mirror-test/src/test/resources/k8s/hts-perf-batch-publish-batch-validate.yml
  hedera-mirror-test/src/test/resources/k8s/hts-perf-publish-and-retrieve.yml
  pom.xml
Labels: P1, process

#1902 Bump versions for v0.32.0
  charts/hedera-mirror-common/Chart.yaml
  charts/hedera-mirror-grpc/Chart.yaml
  charts/hedera-mirror-importer/Chart.yaml
  charts/hedera-mirror-monitor/Chart.yaml
  charts/hedera-mirror-rest/Chart.yaml
  charts/hedera-mirror/Chart.lock
  charts/hedera-mirror/Chart.yaml
  docker-compose.yml
  hedera-mirror-rest/api/v1/openapi.yml
  hedera-mirror-rest/monitoring/monitor_apis/package-lock.json
  hedera-mirror-rest/monitoring/monitor_apis/package.json
  hedera-mirror-rest/package-lock.json
  hedera-mirror-rest/package.json
  hedera-mirror-rosetta/config/application.yml
  hedera-mirror-test/src/test/resources/k8s/hcs-perf-message-submit.yml
  hedera-mirror-test/src/test/resources/k8s/hcs-perf-publish-test.yml
  hedera-mirror-test/src/test/resources/k8s/hcs-perf-subscribe-test.yml
  hedera-mirror-test/src/test/resources/k8s/hts-perf-batch-publish-batch-validate.yml
  hedera-mirror-test/src/test/resources/k8s/hts-perf-publish-and-retrieve.yml
  pom.xml
Labels: P1, enhancement, process
