Repository hiero-ledger/hiero-mirror-node, pull requests merged in 2021-05, with the labels that each got.

#1900 Add multi node validation support to Acceptance tests
  hedera-mirror-datagenerator/pom.xml
  hedera-mirror-grpc/pom.xml
  hedera-mirror-monitor/pom.xml
  hedera-mirror-test/README.md
  hedera-mirror-test/pom.xml
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/SDKClient.java
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/ScheduleClient.java
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/config/AcceptanceTestProperties.java
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/config/ClientConfiguration.java
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/props/NodeProperties.java
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ScheduleFeature.java
  hedera-mirror-test/src/test/resources/application-default.yml
  pom.xml
Labels: P3, enhancement, process

#1870 Automate release process
  .github/release-notes.yml
  .github/workflows/auto-release.yml
  .gitignore
  pom.xml
Labels: P2, enhancement, process

#1922 Adjust timescaledb params
  charts/hedera-mirror/values.yaml
  hedera-mirror-importer/src/main/resources/application.yml
Labels: database, enhancement

#1928 Fix automated release workflow failure
  .github/workflows/auto-release.yml
Labels: P1, bug, process

#1930 Use PAT in automated release
  .github/workflows/auto-release.yml
Labels: P1, bug, process

#1932 Use PAT to create PR in automated release process
  .github/workflows/auto-release.yml
Labels: P2, bug, process

#1942 Fix rosetta docker build failure
  hedera-mirror-rosetta/build/Dockerfile
Labels: P1, bug, rosetta

#1948 Disable AccountBalanceFileParserTest & RecordFileParserIntegrationTest
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/balance/AccountBalanceFileParserTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/RecordFileParserIntegrationTest.java
Labels: P1, bug, regression, test

#1946 Improve rosetta Dockerfile and workflow
  .github/workflows/rosetta-api.yml
  hedera-mirror-rosetta/build/Dockerfile
Labels: P3, enhancement, process

#1938 Add transaction support to entity updater package
  hedera-mirror-rest/entity-info-updater/config.js
  hedera-mirror-rest/entity-info-updater/config/application.yml
  hedera-mirror-rest/entity-info-updater/dbEntityService.js
  hedera-mirror-rest/entity-info-updater/entityUpdateHandler.js
  hedera-mirror-rest/entity-info-updater/index.js
  hedera-mirror-rest/entity-info-updater/networkEntityService.js
  hedera-mirror-rest/entity-info-updater/package.json
  hedera-mirror-rest/entity-info-updater/sample/dbEntityCache.json.gz
  hedera-mirror-rest/entity-info-updater/sample/dbEntityCacheUpdated.json.gz
  hedera-mirror-rest/entity-info-updater/sample/keys.csv.gz
  hedera-mirror-rest/entity-info-updater/sample/networkEntityCache.json.gz
  hedera-mirror-rest/entity-info-updater/tests/entityInfoUpdater.test.js
  hedera-mirror-rest/entity-info-updater/utils.js
Labels: P1, bug, javascript, process

#1949 Bump hedera proto to 0.13.2
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/balance/AccountBalanceFileParserTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/RecordFileParserIntegrationTest.java
  hedera-mirror-rosetta/build/Dockerfile
  pom.xml
Labels: P1, process

#1944 Upgrade to hedera-sdk-go v2.1.5 in rosetta module
  .github/workflows/rosetta-api.yml
  hedera-mirror-rosetta/Dockerfile
  hedera-mirror-rosetta/app/errors/errors.go
  hedera-mirror-rosetta/app/persistence/addressbook/entry/entry.go
  hedera-mirror-rosetta/app/persistence/block/block.go
  hedera-mirror-rosetta/app/persistence/transaction/transaction.go
  hedera-mirror-rosetta/app/services/base/base_service.go
  hedera-mirror-rosetta/app/services/construction/construction_service.go
  hedera-mirror-rosetta/app/services/construction/construction_service_test.go
  hedera-mirror-rosetta/cmd/config.go
  hedera-mirror-rosetta/cmd/config_test.go
  hedera-mirror-rosetta/cmd/db.go
  hedera-mirror-rosetta/cmd/main.go
  hedera-mirror-rosetta/config/application.yml
  hedera-mirror-rosetta/go.mod
  hedera-mirror-rosetta/go.sum
  hedera-mirror-rosetta/scripts/wait-for-mirror-node.sh
  hedera-mirror-rosetta/types/config.go
  hedera-mirror-rosetta/types/config_test.go
Labels: P1, enhancement, go, rosetta

#1951 Bump hedera proto to 0.13.2
  pom.xml
Labels: P1, dependencies

#1967 Bump swagger-stats to 0.99.1 and add its peer dependency prom-client 13.1.0
  hedera-mirror-rest/package-lock.json
  hedera-mirror-rest/package.json
Labels: P3, dependencies

#1973 Fix hedera-mirror-test Dockerfile pointing to tag that does not exist
  hedera-mirror-test/src/main/resources/Dockerfile
Labels: P3, bug

#1977 Always create redis secret
  charts/hedera-mirror/templates/secret-redis.yaml
Labels: P1, bug, process

#1974 Fix service endpoint migration
  hedera-mirror-importer/src/main/resources/db/migration/v1/V1.37.1__add_address_book_service_endpoints.sql
  hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.0__time_scale_init.sql
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/AddAddressBookServiceEndpointsMigrationTest.java
Labels: P1, bug, database, parser

#1978 Port fix service endpoint migration (#1974)
  hedera-mirror-importer/src/main/resources/db/migration/v1/V1.37.1__add_address_book_service_endpoints.sql
  hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.0__time_scale_init.sql
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/AddAddressBookServiceEndpointsMigrationTest.java
Labels: P1, bug, database

#1950 Signature consensus ratio config
  docs/configuration.md
  docs/troubleshooting.md
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/FileStreamSignature.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/CommonDownloaderProperties.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/Downloader.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/NodeSignatureVerifier.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/downloader/AbstractDownloaderTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/downloader/NodeSignatureVerifierTest.java
Labels: P1, downloader, enhancement, ops

#1980 Fix using wrapper chart without redis chart enabled
  charts/hedera-mirror/Chart.yaml
  charts/hedera-mirror/templates/secret-passwords.yaml
  charts/hedera-mirror/templates/secret-redis.yaml
  charts/hedera-mirror/values-prod.yaml
  charts/hedera-mirror/values.yaml
  hedera-mirror-importer/src/main/resources/db/scripts/init_v1.sql
Labels: P1, bug, process

#1925 Add alertmanager inhibit rules
  charts/hedera-mirror-common/values.yaml
  charts/hedera-mirror-grpc/templates/alertmanagerconfig.yaml
  charts/hedera-mirror-grpc/values.yaml
  charts/hedera-mirror-importer/templates/alertmanagerconfig.yaml
  charts/hedera-mirror-importer/values.yaml
  charts/hedera-mirror-monitor/templates/alertmanagerconfig.yaml
  charts/hedera-mirror-monitor/values.yaml
  charts/hedera-mirror-rest/templates/alertmanagerconfig.yaml
  charts/hedera-mirror-rest/values.yaml
  charts/hedera-mirror/templates/alertmanagerconfig.yaml
  charts/hedera-mirror/values-prod.yaml
  charts/hedera-mirror/values.yaml
Labels: P2, enhancement, ops

#1981 Remove JMeter based performance tests
  docs/monitor.md
  hedera-mirror-grpc/pom.xml
  hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/jmeter/client/MultiTopicHCSClient.java
  hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/jmeter/client/SingleTopicHCSClient.java
  hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/jmeter/client/TopicMessageGeneratorClient.java
  hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/jmeter/client/TopicMessagePublishClient.java
  hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/jmeter/client/hts/TokenTransferPublishAndRetrieveClient.java
  hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/jmeter/client/hts/TokenTransferPublishClient.java
  hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/jmeter/client/hts/TokenTransferRESTBatchClient.java
  hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/jmeter/handler/ConnectionHandler.java
  hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/jmeter/handler/PropertiesHandler.java
  hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/jmeter/handler/SDKClientHandler.java
  hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/jmeter/props/MessageGenerator.java
  hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/jmeter/props/MessageListener.java
  hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/jmeter/props/NodeInfo.java
  hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/jmeter/props/TopicMessagePublishRequest.java
  hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/jmeter/props/TopicSubscription.java
  hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/jmeter/props/hts/PublishRequest.java
  hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/jmeter/props/hts/RESTGetByIdsRequest.java
  hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/jmeter/props/hts/RESTRequest.java
  hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/jmeter/props/hts/TokenTransferPublishAndRetrieveRequest.java
  hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/jmeter/props/hts/TokenTransferPublishRequest.java
  hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/jmeter/sampler/HCSDirectStubTopicSampler.java
  hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/jmeter/sampler/HCSMAPITopicSampler.java
  hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/jmeter/sampler/HCSTopicSampler.java
  hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/jmeter/sampler/PublishSampler.java
  hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/jmeter/sampler/TopicMessageGeneratorSampler.java
  hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/jmeter/sampler/TopicMessagesPublishSampler.java
  hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/jmeter/sampler/hts/TokenTransferRESTBatchSampler.java
  hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/jmeter/sampler/hts/TokenTransfersPublishAndRetrieveSampler.java
  hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/jmeter/sampler/hts/TokenTransfersPublishSampler.java
  hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/jmeter/sampler/result/HCSDirectStubSamplerResult.java
  hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/jmeter/sampler/result/HCSMAPISamplerResult.java
  hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/jmeter/sampler/result/HCSSamplerResult.java
  hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/jmeter/sampler/result/TransactionSubmissionResult.java
  hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/jmeter/sampler/result/hts/TokenTransferPublishAndRetrieveResult.java
  hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/util/Utility.java
  hedera-mirror-test/README.md
  hedera-mirror-test/pom.xml
  hedera-mirror-test/src/main/resources/Dockerfile
  hedera-mirror-test/src/main/resources/run-tests.sh
  hedera-mirror-test/src/test/conf/log4j2.xml
  hedera-mirror-test/src/test/jmeter/E2E_200_TPS_All_Messages.jmx
  hedera-mirror-test/src/test/jmeter/E2E_Multi_Client_Subscribe_Only.jmx
  hedera-mirror-test/src/test/jmeter/E2E_Multi_User_All_Messages.jmx
  hedera-mirror-test/src/test/jmeter/E2E_Multi_User_Heavy_Load_All_Messages.jmx
  hedera-mirror-test/src/test/jmeter/E2E_Single_User_All_Messages.jmx
  hedera-mirror-test/src/test/jmeter/E2E_Subscribe_Only.jmx
  hedera-mirror-test/src/test/jmeter/Netty_MaxConcurrentCallsPerConnection.jmx
  hedera-mirror-test/src/test/jmeter/Token_Transfer_Publish_And_Retrieve.jmx
  hedera-mirror-test/src/test/jmeter/Token_Transfer_Publish_Batch_Validate_Batch.jmx
  hedera-mirror-test/src/test/jmeter/Topic_Message_Publish_Only.jmx
  hedera-mirror-test/src/test/jmeter/user.properties
  hedera-mirror-test/src/test/resources/application.yml
  hedera-mirror-test/src/test/resources/k8s/hcs-perf-message-submit.yml
  hedera-mirror-test/src/test/resources/k8s/hcs-perf-publish-test.yml
  hedera-mirror-test/src/test/resources/k8s/hcs-perf-subscribe-test.yml
  hedera-mirror-test/src/test/resources/k8s/hts-perf-batch-publish-batch-validate.yml
  hedera-mirror-test/src/test/resources/k8s/hts-perf-publish-and-retrieve.yml
  pom.xml
Labels: P3, enhancement, performance, test

#1998 Fix pgpool admin password
  charts/hedera-mirror/values.yaml
Labels: P3, bug, process

#1845 Add NFT Design Doc
  docs/design/nft.md
Labels: P1, design, enhancement, nft

#1975 Upgrade to latest rosetta sdk
  .github/workflows/rosetta-api.yml
  .gitignore
  docs/configuration.md
  hedera-mirror-rosetta/app/domain/repositories/transaction.go
  hedera-mirror-rosetta/app/domain/types/account.go
  hedera-mirror-rosetta/app/domain/types/account_test.go
  hedera-mirror-rosetta/app/domain/types/operation.go
  hedera-mirror-rosetta/app/domain/types/operation_test.go
  hedera-mirror-rosetta/app/domain/types/transaction_test.go
  hedera-mirror-rosetta/app/errors/errors.go
  hedera-mirror-rosetta/app/persistence/account/account.go
  hedera-mirror-rosetta/app/persistence/account/account_test.go
  hedera-mirror-rosetta/app/persistence/addressbook/entry/entry.go
  hedera-mirror-rosetta/app/persistence/addressbook/entry/entry_test.go
  hedera-mirror-rosetta/app/persistence/block/block.go
  hedera-mirror-rosetta/app/persistence/block/block_test.go
  hedera-mirror-rosetta/app/persistence/common/common.go
  hedera-mirror-rosetta/app/persistence/common/common_test.go
  hedera-mirror-rosetta/app/persistence/transaction/transaction.go
  hedera-mirror-rosetta/app/persistence/transaction/transaction_test.go
  hedera-mirror-rosetta/app/services/account/account_service.go
  hedera-mirror-rosetta/app/services/account/account_service_test.go
  hedera-mirror-rosetta/app/services/base/base_service.go
  hedera-mirror-rosetta/app/services/base/base_service_test.go
  hedera-mirror-rosetta/app/services/block/block_service.go
  hedera-mirror-rosetta/app/services/block/block_service_test.go
  hedera-mirror-rosetta/app/services/construction/construction_service.go
  hedera-mirror-rosetta/app/services/construction/construction_service_test.go
  hedera-mirror-rosetta/app/services/mempool/mempool_service.go
  hedera-mirror-rosetta/app/services/mempool/mempool_service_test.go
  hedera-mirror-rosetta/app/services/network/network_service.go
  hedera-mirror-rosetta/app/services/network/network_service_test.go
  hedera-mirror-rosetta/build/Dockerfile
  hedera-mirror-rosetta/build/run_supervisord.sh
  hedera-mirror-rosetta/cmd/db.go
  hedera-mirror-rosetta/cmd/main.go
  hedera-mirror-rosetta/config/application.yml
  hedera-mirror-rosetta/go.mod
  hedera-mirror-rosetta/go.sum
  hedera-mirror-rosetta/scripts/validation/demo/data_genesis_balances.json
  hedera-mirror-rosetta/scripts/validation/demo/validate-data.json
  hedera-mirror-rosetta/scripts/validation/demo/validate-from-genesis.json
  hedera-mirror-rosetta/scripts/validation/get-genesis-balance.sh
  hedera-mirror-rosetta/scripts/validation/run-validation.sh
  hedera-mirror-rosetta/scripts/validation/testnet/data_genesis_balances.json
  hedera-mirror-rosetta/scripts/validation/testnet/testnet.ros
  hedera-mirror-rosetta/scripts/validation/testnet/validate-construction.json
  hedera-mirror-rosetta/scripts/validation/testnet/validate-data.json
  hedera-mirror-rosetta/test/mocks/mocks.go
  hedera-mirror-rosetta/test/mocks/repository/account_mock.go
  hedera-mirror-rosetta/test/mocks/repository/transaction_mock.go
  hedera-mirror-rosetta/tools/maphelper/maphelper.go
  hedera-mirror-rosetta/tools/maphelper/maphelper_test.go
  hedera-mirror-rosetta/tools/validator/validator.go
  hedera-mirror-rosetta/tools/validator/validator_test.go
  hedera-mirror-rosetta/types/config.go
Labels: P2, enhancement, rosetta

#2000 Workaround lack of TLS support in SDK & acceptance test cleanup
  hedera-mirror-monitor/src/main/java/com/hedera/hashgraph/sdk/ManagedNode.java
  hedera-mirror-test/README.md
  hedera-mirror-test/pom.xml
  hedera-mirror-test/src/test/java/com/hedera/hashgraph/sdk/ManagedNode.java
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AbstractNetworkClient.java
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AccountClient.java
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/MirrorNodeClient.java
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/SDKClient.java
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/ScheduleClient.java
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TopicClient.java
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/config/AcceptanceTestProperties.java
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/config/ClientConfiguration.java
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/props/NodeProperties.java
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/AccountFeature.java
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ScheduleFeature.java
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TopicFeature.java
Labels: P1, bug, test

#2005 Fix TopicMessageServiceTest.startTimeAfterNow
  hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/service/TopicMessageServiceTest.java
Labels: P3, bug, test

#2003 Improve automated release process
  .github/workflows/auto-release.yml
Labels: P2, enhancement, process

#2002 Helm acceptance tests
  charts/README.md
  charts/hedera-mirror/templates/tests/pod.yaml
  charts/hedera-mirror/templates/tests/secret.yaml
  charts/hedera-mirror/values.yaml
Labels: P2, enhancement, process

#2016 Simplify NodeSignatureVerifier statusMap
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/NodeSignatureVerifier.java
Labels: enhancement, parser

#2022 Show rosetta container log when validation fails
  .github/workflows/rosetta-api.yml
Labels: enhancement, process, rosetta

#2026 Fix accounts REST API with DER encoded public key
  hedera-mirror-rest/__tests__/ed25519.test.js
  hedera-mirror-rest/__tests__/specs/accounts-05-publickey.spec.json
  hedera-mirror-rest/__tests__/utils.test.js
  hedera-mirror-rest/ed25519.js
Labels: P1, bug, rest
