Repository hiero-ledger/hiero-mirror-node, pull requests merged in 2021-10, with the labels that each got.

#2602 HIP 24 Token Pause Support
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Token.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/TokenPauseStatusEnum.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/TransactionTypeEnum.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/AbstractEntityListener.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/upsert/TokenUpsertQueryGenerator.java
  hedera-mirror-importer/src/main/resources/db/migration/v1/V1.45.1__token_pause.sql
  hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.0__time_scale_init.sql
  hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.4__reference_table_inserts.sql
  hedera-mirror-importer/src/main/resources/db/scripts/timescaledb/csvRestoreTables.sql
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/AddMissingTokenAccountAssociationMigrationTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/SupportDeletedTokenDissociateMigrationTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerTokenTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/repository/RepositoryEntityListenerTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/UpsertPgCopyTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/repository/TokenRepositoryTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/repository/TokenTransferRepositoryTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/repository/upsert/TokenUpsertQueryGeneratorTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/repository/upsert/TokenUpsertQueryGeneratorV2Test.java
  hedera-mirror-rest/__tests__/integrationDomainOps.js
  hedera-mirror-rest/__tests__/specs/token-info-01-no-args.spec.json
  hedera-mirror-rest/__tests__/specs/token-info-04-non-fungible-unique-token-types.spec.json
  hedera-mirror-rest/__tests__/specs/token-info-05-custom-fees.spec.json
  hedera-mirror-rest/__tests__/specs/token-info-06-historical-custom-fees.spec.json
  hedera-mirror-rest/__tests__/specs/token-info-09-nft-custom-fees.spec.json
  hedera-mirror-rest/__tests__/tokens.test.js
  hedera-mirror-rest/api/v1/openapi.yml
  hedera-mirror-rest/model/token.js
  hedera-mirror-rest/tokens.js
  pom.xml
Labels: enhancement, P1, parser

#2639 Remove the 'Mirror' milestone prefix
  .github/workflows/auto-release.yml
Labels: enhancement, P2, process

#2637 Add recommended importer configuration for historical data ingestion
  docs/operations.md
Labels: documentation, enhancement, parser

#2643 Upgrade rosetta PostgreSQL
  .github/workflows/rosetta-api.yml
  hedera-mirror-rosetta/build/.dockerignore
  hedera-mirror-rosetta/build/Dockerfile
  hedera-mirror-rosetta/build/pg_hba.conf
  hedera-mirror-rosetta/build/postgresql.conf
  hedera-mirror-rosetta/build/supervisord-offline.conf
  hedera-mirror-rosetta/build/supervisord.conf
  hedera-mirror-rosetta/pom.xml
Labels: enhancement, P2, rosetta

#2673 Fix notes bug in helm template
  charts/hedera-mirror/templates/application.yaml
Labels: bug, P3

#2690 [0.42] Fix notes bug in helm template
  charts/hedera-mirror/templates/application.yaml
Labels: bug, P3

#2693 Improve transaction REST API query performance
  docs/design/images/state-proof-alpha-sequence.svg
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/Transaction.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
  hedera-mirror-importer/src/main/resources/db/migration/v1/V1.46.6__rename_consensus_ns.sql
  hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.0__time_scale_init.sql
  hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.1__hyper_tables.sql
  hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.2__time_scale_index_init.sql
  hedera-mirror-importer/src/main/resources/db/scripts/timescaledb/csvRestoreTables.sql
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/CleanupEntityMigrationTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/EntityTimestampMigrationTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/EntityTimestampMigrationV1_46_0Test.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/RemoveInvalidEntityMigrationTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/SupportDeletedTokenDissociateMigrationTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/RecordFileParserIntegrationTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerCryptoTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/PgCopyTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/repository/TransactionRepositoryTest.java
  hedera-mirror-rest/__tests__/accounts.test.js
  hedera-mirror-rest/__tests__/data/db/stateproof/transaction.sql
  hedera-mirror-rest/__tests__/data/db/stateproof/transaction_v5.sql
  hedera-mirror-rest/__tests__/integration.test.js
  hedera-mirror-rest/__tests__/integrationDomainOps.js
  hedera-mirror-rest/__tests__/mockpool.js
  hedera-mirror-rest/__tests__/stateproof.test.js
  hedera-mirror-rest/__tests__/testutils.js
  hedera-mirror-rest/__tests__/tokens.test.js
  hedera-mirror-rest/__tests__/transactions.test.js
  hedera-mirror-rest/accounts.js
  hedera-mirror-rest/model/cryptoTransfer.js
  hedera-mirror-rest/model/index.js
  hedera-mirror-rest/model/tokenTransfer.js
  hedera-mirror-rest/model/transaction.js
  hedera-mirror-rest/stateproof.js
  hedera-mirror-rest/tokens.js
  hedera-mirror-rest/transactions.js
  hedera-mirror-rest/utils.js
  hedera-mirror-rosetta/app/persistence/domain/transaction.go
  hedera-mirror-rosetta/app/persistence/testmain_test.go
  hedera-mirror-rosetta/app/persistence/transaction.go
Labels: enhancement, P2, performance, rest

#2723 Fix feedback for token pause monitor and acceptance test support
  hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/token/TokenPauseTransactionSupplierTest.java
  hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/transaction/token/TokenUnpauseTransactionSupplierTest.java
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/response/MirrorTokenResponse.java
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
  hedera-mirror-test/src/test/resources/features/hts/hts.feature
Labels: P3, test, monitor

#2758 Convert v2 flyway migration to use CItus
  charts/hedera-mirror/ci/timescaledb-values.yaml
  hedera-mirror-grpc/src/test/resources/cleanup.sql
  hedera-mirror-grpc/src/test/resources/config/bootstrap-v2.yml
  hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.0__create_tables.sql
  hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.1__distribution.sql
  hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.1__hyper_tables.sql
  hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.2__partitioning.sql
  hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.3__index_init.sql
  hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.3__time_scale_compression.sql
  hedera-mirror-importer/src/main/resources/db/scripts/cleanup.sql
  hedera-mirror-importer/src/test/resources/config/bootstrap-v2.yml
  hedera-mirror-rest/__tests__/integrationDbOps.js
Labels: enhancement, P2, database
