Repository hiero-ledger/hiero-mirror-node, pull requests merged in 2022-12, with the labels that each got.

#4979 Fix NoClassDefFoundError in RecordFileParser
  charts/hedera-mirror-importer/values.yaml
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/AbstractStreamFileParser.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/RecordFileParser.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/IntegrationTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/config/IntegrationTestConfiguration.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/AbstractStreamFileParserTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/RecordFileParserIntegrationTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/RecordFileParserTest.java
  hedera-mirror-importer/src/test/resources/config/application.yml
Labels: bug, parser

#4980 Fix NoClassDefFoundError in RecordFileParser (0.70)
  charts/hedera-mirror-importer/values.yaml
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/AbstractStreamFileParser.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/RecordFileParser.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/IntegrationTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/config/IntegrationTestConfiguration.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/AbstractStreamFileParserTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/RecordFileParserIntegrationTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/RecordFileParserTest.java
  hedera-mirror-importer/src/test/resources/config/application.yml
Labels: bug, parser

#4981 Fix NoClassDefFoundError in RecordFileParser (0.69)
  charts/hedera-mirror-importer/values.yaml
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/AbstractStreamFileParser.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/RecordFileParser.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/IntegrationTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/config/IntegrationTestConfiguration.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/AbstractStreamFileParserTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/RecordFileParserIntegrationTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/RecordFileParserTest.java
  hedera-mirror-importer/src/test/resources/config/application.yml
Labels: bug, parser

#4799 Adding citus time based partitioning.
  charts/hedera-mirror/ci/citus-values.yaml
  charts/hedera-mirror/templates/configmap-init.yaml
  charts/hedera-mirror/values.yaml
  docker-compose.yml
  docs/importer/README.md
  hedera-mirror-grpc/src/test/resources/config/application.yml
  hedera-mirror-grpc/src/test/resources/config/bootstrap-v2.yml
  hedera-mirror-grpc/src/test/resources/config/bootstrap.yml
  hedera-mirror-grpc/src/test/resources/db/scripts/init-v2.sql
  hedera-mirror-importer/src/main/resources/application.yml
  hedera-mirror-importer/src/main/resources/db/migration/v2/R__autovacuum_insert_only_tables.sql
  hedera-mirror-importer/src/main/resources/db/migration/v2/R__create_partitions.sql
  hedera-mirror-importer/src/main/resources/db/migration/v2/R__maintain_partitions.sql
  hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.0__create_tables.sql
  hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.1__distribution.sql
  hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.2__partitioning.sql
  hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.2__static_partitioning.sql
  hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.3__index_init.sql
  hedera-mirror-importer/src/main/resources/db/scripts/init.sh
  hedera-mirror-importer/src/main/resources/db/scripts/v2/docker/alpine/001-create-citus-extension.sql
  hedera-mirror-importer/src/main/resources/db/scripts/v2/docker/alpine/Dockerfile
  hedera-mirror-importer/src/main/resources/db/scripts/v2/docker/alpine/pg_healthcheck
  hedera-mirror-importer/src/main/resources/db/scripts/v2/docker/debian/Dockerfile
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/IntegrationTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/config/IntegrationTestConfiguration.java
  hedera-mirror-importer/src/test/resources/config/application.yml
  hedera-mirror-importer/src/test/resources/config/bootstrap-v2.yml
  hedera-mirror-importer/src/test/resources/db/scripts/init-v2.sql
  hedera-mirror-rest/__tests__/globalSetup.js
  hedera-mirror-rest/__tests__/integrationDbOps.js
  hedera-mirror-web3/src/test/resources/application.yml
  hedera-mirror-web3/src/test/resources/bootstrap-v2.yml
  hedera-mirror-web3/src/test/resources/bootstrap.yml
  hedera-mirror-web3/src/test/resources/db/scripts/init-v2.sql
Labels: enhancement, database

#4986 Add a dependency-check-gradle plugin
  .github/workflows/gradle.yml
  .github/workflows/security.yml
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/common-conventions.gradle.kts
  buildSrc/src/main/kotlin/go-conventions.gradle.kts
  buildSrc/src/main/kotlin/java-conventions.gradle.kts
  buildSrc/src/main/kotlin/javascript-conventions.gradle.kts
  buildSrc/src/main/resources/hooks/pre-commit
  buildSrc/src/main/resources/suppressions.xml
  gradle.properties
  hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/service/AddressBookProperties.java
  hedera-mirror-importer/build.gradle.kts
  hedera-mirror-importer/pom.xml
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerEthereumTest.java
  hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/subscribe/rest/RestSubscriber.java
  hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/subscribe/rest/RestSubscriberTest.java
  hedera-mirror-rest/check-state-proof/build.gradle.kts
  pom.xml
Labels: enhancement, process

#5006 Return evm address as address in logs on /contracts/results
  hedera-mirror-rest/__tests__/specs/contracts/results/{id}/transactionid-or-hash.json
  hedera-mirror-rest/__tests__/specs/contracts/{id}/results/{id}/non-populated-eth-data.json
  hedera-mirror-rest/__tests__/specs/contracts/{id}/results/{id}/populated-eth-data-func-params-from-filedata.json
  hedera-mirror-rest/__tests__/specs/contracts/{id}/results/{id}/populated-eth-data.json
  hedera-mirror-rest/__tests__/specs/contracts/{id}/results/{id}/timestamp-no-state-change.json
  hedera-mirror-rest/__tests__/specs/contracts/{id}/results/{id}/timestamp.json
  hedera-mirror-rest/service/contractService.js
Labels: enhancement, rest, limechain

#5009 Change acceptance tests to use Gradle
  buildSrc/src/main/kotlin/docker-conventions.gradle.kts
  buildSrc/src/main/kotlin/java-conventions.gradle.kts
  charts/hedera-mirror/templates/tests/pod.yaml
  charts/hedera-mirror/templates/tests/secret.yaml
  charts/hedera-mirror/values.yaml
  gradle.properties
  hedera-mirror-test/README.md
  hedera-mirror-test/build.gradle.kts
  pom.xml
Labels: enhancement, process

#5008 Add a helm release health indicator to monitor
  build.gradle.kts
  charts/hedera-mirror-monitor/templates/role.yaml
  docs/configuration.md
  hedera-mirror-monitor/build.gradle.kts
  hedera-mirror-monitor/pom.xml
  hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/health/ClusterHealthIndicator.java
  hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/health/ReleaseHealthIndicator.java
  hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/health/ReleaseHealthProperties.java
  hedera-mirror-monitor/src/main/resources/application.yml
  hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/health/ClusterHealthIndicatorTest.java
  hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/health/ReleaseHealthIndicatorTest.java
Labels: bug, regression, monitor

#5017 Add contract call route to web3 ingress
  charts/hedera-mirror-web3/values.yaml
  hedera-mirror-web3/postman.json
Labels: enhancement, web3

#4976 Real Time Token Balances with the Balances REST API
  hedera-mirror-rest/__tests__/specs/balances/balance-range.json
  hedera-mirror-rest/__tests__/specs/balances/no-params.json
  hedera-mirror-rest/__tests__/specs/balances/specific-id.json
  hedera-mirror-rest/balances.js
Labels: enhancement, rest

#5018 Real Time Token Balances with the Accounts REST API
  hedera-mirror-rest/__tests__/specs/accounts/accounts-range.json
  hedera-mirror-rest/__tests__/specs/accounts/all-params.json
  hedera-mirror-rest/__tests__/specs/accounts/balance-range.json
  hedera-mirror-rest/__tests__/specs/accounts/limit-capped-at-max.json
  hedera-mirror-rest/__tests__/specs/accounts/limit.json
  hedera-mirror-rest/__tests__/specs/accounts/multiple-ids.json
  hedera-mirror-rest/__tests__/specs/accounts/no-balances.json
  hedera-mirror-rest/__tests__/specs/accounts/no-params.json
  hedera-mirror-rest/__tests__/specs/accounts/publickey.json
  hedera-mirror-rest/__tests__/specs/accounts/specific-id.json
  hedera-mirror-rest/__tests__/specs/accounts/{id}/no-params.json
  hedera-mirror-rest/__tests__/specs/accounts/{id}/timestamp.json
  hedera-mirror-rest/__tests__/specs/accounts/{id}/token-balance-limit.json
  hedera-mirror-rest/__tests__/specs/accounts/{id}/transactiontype.json
  hedera-mirror-rest/accounts.js
Labels: enhancement, rest

#5007 Add Alias support for HIP-583 CryptoCreate Transactions
  build.gradle.kts
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/EntityIdServiceImpl.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/CryptoCreateTransactionHandler.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/PubSubMessageTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/CryptoCreateTransactionHandlerTest.java
  hedera-mirror-importer/src/test/resources/data/pubsub-messages.txt
  pom.xml
Labels: enhancement, parser

#5022 Improve REST API auto-scaler
  charts/hedera-mirror-common/values.yaml
  charts/hedera-mirror-rest/values.yaml
Labels: enhancement, rest

#5034 Move dependency check to separate workflow
  .github/dependabot.yml
  .github/workflows/rosetta.yml
  .github/workflows/security.yml
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/common-conventions.gradle.kts
  buildSrc/src/main/kotlin/go-conventions.gradle.kts
  buildSrc/src/main/kotlin/java-conventions.gradle.kts
  buildSrc/src/main/kotlin/javascript-conventions.gradle.kts
  buildSrc/src/main/kotlin/plugin/go/GoSetup.kt
  hedera-mirror-common/src/test/java/com/hedera/mirror/common/domain/entity/EntityTest.java
  hedera-mirror-common/src/test/java/com/hedera/mirror/common/util/DomainUtilsTest.java
  hedera-mirror-rest/check-state-proof/package-lock.json
  hedera-mirror-rest/check-state-proof/package.json
  hedera-mirror-rest/monitoring/monitor_apis/package-lock.json
  hedera-mirror-rest/monitoring/monitor_apis/package.json
  hedera-mirror-rest/package-lock.json
  hedera-mirror-rest/package.json
  hedera-mirror-rosetta/container/Dockerfile
Labels: bug, regression, process

#5042 Fix Acceptance Test transfer race condition
  hedera-mirror-test/src/test/resources/features/account/allowances/cryptoAllowance.feature
Labels: bug, test

#5035 Add integration-docker deployment
  clusters/preprod/flux-system/alert-slack.yaml
  clusters/preprod/integration-docker/helmrelease.yaml
  clusters/preprod/integration-docker/helmrepository.yaml
  clusters/preprod/integration-docker/namespace.yaml
  clusters/preprod/integration-docker/sealed-secret.yaml
Labels: enhancement, process

#5053 Write k6 test report.md to custom directory
  hedera-mirror-test/k6/src/lib/common.js
  hedera-mirror-test/k6/src/rest/apis.js
  hedera-mirror-test/k6/src/rosetta/apis.js
  hedera-mirror-test/k6/src/web3/apis.js
Labels: enhancement, performance, test

#5055 Adding citus helm release.
  clusters/preprod/citus/helmrelease.yaml
  clusters/preprod/citus/helmrepository.yaml
  clusters/preprod/citus/namespace.yaml
  clusters/preprod/flux-system/alert-slack.yaml
Labels: enhancement, database

#5058 05043 fix citus helm release
  clusters/preprod/citus/helmrelease.yaml
Labels: enhancement, database

#5077 Revert to hedera-sdk-java 2.18.0 to workaround regression
  hedera-mirror-monitor/build.gradle.kts
Labels: bug, monitor

#5063 Add runtime_bytecode to OpenAPI
  .editorconfig
  .github/workflows/rosetta.yml
  hedera-mirror-rest/api/v1/openapi.yml
Labels: bug, rest

#5081 Revert to hedera-sdk-java 2.18.0 to workaround regression (0.70)
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/downloader/provider/AbstractStreamFileProviderTest.java
  hedera-mirror-monitor/build.gradle.kts
Labels: bug, regression, monitor

#5083 Changing the type for expiry_timestamp back to a number
  hedera-mirror-rest/__tests__/specs/tokens/{id}/custom-fees.json
  hedera-mirror-rest/__tests__/specs/tokens/{id}/no-params.json
  hedera-mirror-rest/__tests__/tokens.test.js
  hedera-mirror-rest/__tests__/utils.test.js
  hedera-mirror-rest/accounts.js
  hedera-mirror-rest/api/v1/openapi.yml
  hedera-mirror-rest/utils.js
  hedera-mirror-rest/viewmodel/contractViewModel.js
Labels: bug, rest, hts

#5089 Fix monitor service catalog watch error
  hedera-mirror-monitor/src/main/resources/application.yml
Labels: bug, monitor

#5086 Retry stateproof request in js monitor check
  hedera-mirror-rest/monitoring/monitor_apis/config/default.serverlist.json
  hedera-mirror-rest/monitoring/monitor_apis/package-lock.json
  hedera-mirror-rest/monitoring/monitor_apis/package.json
  hedera-mirror-rest/monitoring/monitor_apis/stateproof_tests.js
Labels: bug, monitor

#5090 Changing the type for expiry_timestamp back to a number (#5083)
  hedera-mirror-rest/__tests__/specs/tokens/{id}/custom-fees.json
  hedera-mirror-rest/__tests__/specs/tokens/{id}/no-params.json
  hedera-mirror-rest/__tests__/tokens.test.js
  hedera-mirror-rest/__tests__/utils.test.js
  hedera-mirror-rest/accounts.js
  hedera-mirror-rest/api/v1/openapi.yml
  hedera-mirror-rest/utils.js
  hedera-mirror-rest/viewmodel/contractViewModel.js
Labels: bug, rest, hts

#5094 Disable git pre-commit hook
  buildSrc/src/main/resources/hooks/pre-commit
Labels: bug, process

#5095 Fix release related github workflows
  .github/workflows/release-automation.yml
  .github/workflows/release-production.yml
Labels: bug, regression, process

#5096 Disable git pre-commit hook (0.71)
  buildSrc/src/main/resources/hooks/pre-commit
  charts/hedera-mirror-common/Chart.yaml
  charts/hedera-mirror-grpc/Chart.yaml
  charts/hedera-mirror-importer/Chart.yaml
  charts/hedera-mirror-monitor/Chart.yaml
  charts/hedera-mirror-rest/Chart.yaml
  charts/hedera-mirror-rosetta/Chart.yaml
  charts/hedera-mirror-web3/Chart.yaml
  charts/hedera-mirror/Chart.yaml
  gradle.properties
  hedera-mirror-rest/api/v1/openapi.yml
  hedera-mirror-rest/check-state-proof/package-lock.json
  hedera-mirror-rest/check-state-proof/package.json
  hedera-mirror-rest/monitoring/monitor_apis/package-lock.json
  hedera-mirror-rest/monitoring/monitor_apis/package.json
  hedera-mirror-rest/package-lock.json
  hedera-mirror-rest/package.json
Labels: bug, process

#5098 Fix release related github workflows (0.71)
  .github/workflows/release-automation.yml
  .github/workflows/release-production.yml
Labels: bug, regression, process

#5102 Fix upload artifact error in gradle github workflow
  .github/workflows/gradle.yml
Labels: bug, process

#5107 Fix github token permission issue in release production workflow
  .github/workflows/release-production.yml
Labels: bug, process

#5109 Fix upload artifact error in gradle github workflow (0.71)
  .github/workflows/gradle.yml
Labels: bug, process

#5110 Fix github token permission issue in release production workflow (0.71)
  .github/workflows/release-production.yml
Labels: bug, process

#5100 Add back the old automated release workflow with maven
  .github/workflows/auto-release.yml
Labels: bug, process

#5114 Revert to hedera-sdk-java 2.18.0 in pom
  hedera-mirror-monitor/pom.xml
  hedera-mirror-test/pom.xml
Labels: bug, regression, monitor

#5115 Bump up hedera-sdk-java to 2.19.0 for hedera-mirror-test
  hedera-mirror-test/pom.xml
Labels: bug, regression

#5117 Fix automated release workflow unable to install JDK
  .github/workflows/auto-release.yml
Labels: bug, regression, process

#5121 Install missing wget in rest and rosetta Dockerfile
  hedera-mirror-rest/Dockerfile
  hedera-mirror-rosetta/Dockerfile
Labels: bug, regression

#5122 Install missing wget in rest and rosetta Dockerfile (0.71)
  hedera-mirror-rest/Dockerfile
  hedera-mirror-rosetta/Dockerfile
Labels: bug, regression

#5099 Remove JSON-RPC code
  .github/workflows/charts.yml
  charts/README.md
  charts/hedera-mirror-web3/templates/tests/pod.yaml
  charts/hedera-mirror-web3/values.yaml
  charts/hedera-mirror/templates/NOTES.txt
  docs/installation.md
  hedera-mirror-web3/postman.json
  hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/controller/JsonRpcErrorCode.java
  hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/controller/JsonRpcErrorResponse.java
  hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/controller/JsonRpcRequest.java
  hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/controller/JsonRpcResponse.java
  hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/controller/JsonRpcSuccessResponse.java
  hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/controller/Web3Controller.java
  hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/Web3Service.java
  hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/Web3ServiceFactory.java
  hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/eth/EthBlockNumberService.java
  hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/eth/EthService.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/controller/Web3ControllerTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/eth/EthBlockNumberServiceTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/eth/Web3ServiceFactoryTest.java
Labels: enhancement, web3

#5123 Fix gradle release and affected github workflows
  .github/workflows/charts.yml
  .github/workflows/rosetta.yml
  build.gradle.kts
  charts/hedera-mirror-rosetta/postman.json
  charts/hedera-mirror-rosetta/templates/tests/configmap.yaml
  charts/hedera-mirror-rosetta/templates/tests/pod.yaml
  charts/hedera-mirror-rosetta/values.yaml
  charts/hedera-mirror-web3/postman.json
  charts/hedera-mirror-web3/templates/tests/configmap.yaml
  charts/hedera-mirror-web3/templates/tests/pod.yaml
  charts/hedera-mirror-web3/values.yaml
  docs/rosetta/README.md
  docs/web3/README.md
Labels: bug, process

#5136 Fix gradle release and affected github workflows (0.71)
  .github/workflows/charts.yml
  .github/workflows/rosetta.yml
  build.gradle.kts
  charts/hedera-mirror-rosetta/postman.json
  charts/hedera-mirror-rosetta/templates/tests/configmap.yaml
  charts/hedera-mirror-rosetta/templates/tests/pod.yaml
  charts/hedera-mirror-rosetta/values.yaml
  charts/hedera-mirror-web3/postman.json
  charts/hedera-mirror-web3/templates/tests/configmap.yaml
  charts/hedera-mirror-web3/templates/tests/pod.yaml
  charts/hedera-mirror-web3/values.yaml
  docker-compose.yml
  docs/rosetta/README.md
  docs/web3/README.md
Labels: bug, process

#5097 Update README.md
  docs/monitor/README.md
Labels: bug, documentation
