Repository hiero-ledger/hiero-mirror-node, pull requests merged in 2024-08, with the labels that each got.

#8915 Deploy 0.109.1 to mainnet-na.
  clusters/mainnet-na/common/helmrelease.yaml
  clusters/mainnet-na/mainnet/helmrelease.yaml
Labels: deploy

#8899 Setup a mirrornode for staging-council
  clusters/preprod/flux-system/alert-slack.yaml
  clusters/preprod/staging-council/helmrelease.yaml
  clusters/preprod/staging-council/helmrepository.yaml
  clusters/preprod/staging-council/namespace.yaml
  clusters/preprod/staging-council/sealed-secret.yaml
Labels: deploy

#8920 Fix addressBook format in the sealed-secret
  clusters/preprod/staging-council/sealed-secret.yaml
Labels: deploy

#8862 Add acceptance tests for TokenReject transaction
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
  hedera-mirror-test/src/test/resources/features/token/token.feature
Labels: enhancement, test

#8797 Add additional validations for call against system account
  hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/config/EvmConfiguration.java
  hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/AbstractEvmMessageCallProcessor.java
  hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/MirrorEvmMessageCallProcessor.java
  hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/MirrorEvmMessageCallProcessorV30.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/contracts/execution/MirrorEvmMessageCallProcessorTest.java
Labels: bug, web3

#8923 Safely retry in TokenReject acceptance test
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
  hedera-mirror-test/src/test/resources/features/token/token.feature
Labels: test

#8876 Handling timeout exception for monitor UNKNOWN error
  hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/health/ClusterHealthIndicator.java
  hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/health/ClusterHealthIndicatorTest.java
Labels: bug, monitor

#8924 Enable persisting transaciton hash in testnet-na
  clusters/testnet-na/testnet/helmrelease.yaml
Labels: deploy

#8912 Refactor ContractCallDynamicCallsTest
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/AbstractContractCallServiceTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallDynamicCallsTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallTestSetup.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractDebugServiceTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/OpcodeServiceTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/utils/ContractCallTestUtil.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/web3j/TestWeb3jService.java
  hedera-mirror-web3/src/test/solidity/DynamicEthCalls.sol
Labels: enhancement, test, web3

#8948 Filter transaction hash for ethereum transaction with empty hash (0.110)
  charts/hedera-mirror/values-v2.yml
  docs/configuration.md
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/BackfillTransactionHashMigration.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityProperties.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/BackfillTransactionHashMigrationTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java
  hedera-mirror-rosetta/container/supervisord.conf
Labels: bug, parser

#8908 HIP-869 Adding admin_key for the dynamic address book
  hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/entity/AbstractNode.java
  hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/entity/Node.java
  hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/entity/NodeHistory.java
  hedera-mirror-common/src/test/java/com/hedera/mirror/common/domain/DomainBuilder.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/CompositeEntityListener.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityListener.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/NodeCreateTransactionHandler.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/NodeDeleteTransactionHandler.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/NodeUpdateTransactionHandler.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/NodeHistoryRepository.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/NodeRepository.java
  hedera-mirror-importer/src/main/resources/db/migration/common/R__01_temp_tables.sql
  hedera-mirror-importer/src/main/resources/db/migration/v1/V1.99.0__add_node.sql
  hedera-mirror-importer/src/main/resources/db/migration/v2/V2.4.0__add_node.sql
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/batch/BatchUpserterTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerNodeTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/NodeCreateTransactionHandlerTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/NodeDeleteTransactionHandlerTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/NodeUpdateTransactionHandlerTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/repository/NodeHistoryRepositoryTest.java
Labels: enhancement, parser

#8950 Increase testnet acceptance test operator balance
  clusters/testnet-na/testnet/helmrelease.yaml
Labels: deploy

#8914 Refactor ContractCallEvmCodesTest
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallAddressThisTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallEvmCodesHistoricalTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallEvmCodesTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServiceTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallTestSetup.java
  hedera-mirror-web3/src/test/solidity/EthCall.sol
  hedera-mirror-web3/src/test/solidity/EvmCodes.sol
Labels: enhancement, test, web3, limechain

#8954 chore: migrate actions to step-security maintained versions
  .github/workflows/release-automation.yml
  .github/workflows/release-production.yml
Labels: github_actions

#8957 Calculate acceptance test operator balance from USD
  hedera-mirror-test/README.md
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/SDKClient.java
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/StartupProbe.java
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/config/AcceptanceTestProperties.java
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/config/FeatureProperties.java
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ContractFeature.java
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/util/ContractCallResponseWrapper.java
Labels: enhancement, test

#8958 Calculate acceptance test operator balance from USD (0.111)
  hedera-mirror-test/README.md
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/SDKClient.java
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/StartupProbe.java
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/config/AcceptanceTestProperties.java
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/config/FeatureProperties.java
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ContractFeature.java
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/util/ContractCallResponseWrapper.java
Labels: enhancement, test

#8961 Deploy 0.111.0-rc2 to performance and mainnet-staging
  clusters/mainnet-staging-na/common/helmrelease.yaml
  clusters/mainnet-staging-na/mainnet-citus/helmrelease.yaml
  clusters/mainnet-staging-na/mainnet/helmrelease.yaml
  clusters/preprod/common/helmrelease.yaml
  clusters/preprod/performance-citus/helmrelease.yaml
  clusters/preprod/performance/helmrelease.yaml
Labels: deploy

#8964 Enable cluster state reconciliation in testnet-eu
  clusters/testnet-eu/common/helmrelease.yaml
  clusters/testnet-eu/testnet-citus/helmrelease.yaml
  clusters/testnet-eu/testnet/helmrelease.yaml
Labels: deploy

#8963 Deploy 0.110.1 to mainnet-na
  clusters/mainnet-na/common/helmrelease.yaml
  clusters/mainnet-na/mainnet/helmrelease.yaml
Labels: deploy

#8966 Enable cluster state reconciliation in testnet-na
  clusters/testnet-na/common/helmrelease.yaml
  clusters/testnet-na/testnet/helmrelease.yaml
Labels: deploy

#8969 Increase loki volume size in mainnet-na
  clusters/mainnet-na/common/helmrelease.yaml
Labels: deploy

#8972 Fix accounts REST API error with some query params
  hedera-mirror-rest/__tests__/specs/accounts/balance-false.json
  hedera-mirror-rest/accounts.js
Labels: bug, regression, rest

#8968 Fix exchange rate rounding issue in acceptance tests
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/SDKClient.java
Labels: bug, test, regression

#8973 Fix accounts REST API error with some query params (0.111)
  hedera-mirror-rest/__tests__/specs/accounts/balance-false.json
  hedera-mirror-rest/accounts.js
Labels: bug, regression, rest

#8974 Fix exchange rate rounding issue in acceptance tests (0.111)
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/SDKClient.java
Labels: bug, test, regression

#8975 Fix accounts REST API error with some query params (0.110)
  hedera-mirror-rest/__tests__/specs/accounts/balance-false.json
  hedera-mirror-rest/accounts.js
Labels: bug, regression, rest

#8978 Upgrade mainnet-na to v0.110.2
  clusters/mainnet-na/common/helmrelease.yaml
  clusters/mainnet-na/mainnet/helmrelease.yaml
Labels: deploy

#8981 Update non Production Environments for 0.111.0-rc3
  clusters/mainnet-staging-na/common/helmrelease.yaml
  clusters/mainnet-staging-na/mainnet-citus/helmrelease.yaml
  clusters/mainnet-staging-na/mainnet/helmrelease.yaml
  clusters/preprod/common/helmrelease.yaml
  clusters/preprod/dev/helmrelease.yaml
  clusters/preprod/performance-citus/helmrelease.yaml
  clusters/preprod/performance/helmrelease.yaml
  clusters/preprod/staging-council/helmrelease.yaml
Labels: deploy

#8986 Disable NFT Acceptance Tests for Mainnet Staging In V1 and V2
  clusters/mainnet-staging-na/mainnet-citus/helmrelease.yaml
  clusters/mainnet-staging-na/mainnet/helmrelease.yaml
Labels: deploy

#8988 Fix case sensitive array query parameters
  hedera-mirror-rest/__tests__/requestHandler.test.js
  hedera-mirror-rest/__tests__/specs/transactions/all-params.json
  hedera-mirror-rest/middleware/requestHandler.js
Labels: bug, rest

#8943 Remove `ContractReadFunctions` enum from `ContractCallServicePrecompileTest`
  hedera-mirror-rest/middleware/httpErrorHandler.js
  hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/TokenDatabaseAccessor.java
  hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/token/TokenAccessorImpl.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/AbstractContractCallServiceTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallAddressThisTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallDynamicCallsTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallEvmCodesTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallNestedCallsTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServiceERCTokenTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServicePrecompileTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServiceTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallSystemPrecompileTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallTestSetup.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/utils/ContractCallTestUtil.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/web3j/TestWeb3jService.java
  hedera-mirror-web3/src/test/solidity/EthCall.sol
  hedera-mirror-web3/src/test/solidity/ModificationPrecompileTestContract.sol
Labels: technical debt, test, web3

#9008 Bump github.com/ory/dockertest/v3 from 3.10.0 to 3.11.0
  hedera-mirror-rosetta/go.mod
  hedera-mirror-rosetta/go.sum
Labels: security, dependencies, go

#8985 Refactor `ContractCallServiceERCTokenTest`
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServiceERCTokenReadOnlyFunctionsTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServiceERCTokenTest.java
  hedera-mirror-web3/src/test/solidity/ERCTestContract.sol
Labels: enhancement, technical debt, test, web3

#8955 Refactor ContractCallNestedCallsTest
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/AbstractContractCallServiceTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallNestedCallsHistoricalTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallNestedCallsTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServicePrecompileTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractDebugServiceTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/OpcodeServiceTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/utils/ContractCallTestUtil.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/web3j/TestWeb3jService.java
  hedera-mirror-web3/src/test/solidity/NestedCallsTestContract.sol
Labels: enhancement, test, web3

#8799 Port REST specs to Java, phase 1
  hedera-mirror-common/src/test/java/com/hedera/mirror/common/config/CommonTestConfiguration.java
  hedera-mirror-rest-java/build.gradle.kts
  hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/converter/EntityIdFromLongConverter.java
  hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/converter/EntityIdFromStringConverter.java
  hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/converter/EntityIdFromLongConverterTest.java
  hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/converter/EntityIdFromStringConverterTest.java
  hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/RestSpecTest.java
  hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/builder/AbstractEntityBuilder.java
  hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/builder/AccountBuilder.java
  hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/builder/CompositeSpecDomainBuilder.java
  hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/builder/SpecDomainBuilder.java
  hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/builder/TokenAccountBuilder.java
  hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/config/SpecTestConfig.java
  hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/converter/JsonAsStringDeserializer.java
  hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/model/RestSpec.java
  hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/model/RestSpecNormalized.java
  hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/model/SpecSetup.java
  hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/model/SpecTest.java
  hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/spec/model/SpecTestNormalized.java
Labels: enhancement, rest-java

#9020 Improve transaction hash v2 performance (0.111)
  hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/TransactionHash.java
  hedera-mirror-common/src/test/java/com/hedera/mirror/common/domain/transaction/TransactionHashTest.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/BackfillTransactionHashMigration.java
  hedera-mirror-importer/src/main/resources/db/migration/v1/V1.99.1__add_transaction_hash_distribution_id.sql
  hedera-mirror-importer/src/main/resources/db/migration/v2/V2.4.1__change_transaction_hash_distribution.sql
  hedera-mirror-importer/src/main/resources/db/migration/v2/V2.4.2__get_transaction_info_by_hash.sql
  hedera-mirror-importer/src/main/resources/db/scripts/v2/migration.config
  hedera-mirror-importer/src/main/resources/db/scripts/v2/migration.sh
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/TestUtils.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/BackfillTransactionHashMigrationTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/ChangeTransactionHashDistributionMigrationTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/repository/TransactionHashRepositoryTest.java
  hedera-mirror-rest/__tests__/integration/transactionHash.test.js
  hedera-mirror-rest/__tests__/integrationDomainOps.js
  hedera-mirror-rest/errors/index.js
  hedera-mirror-rest/model/transactionHash.js
  hedera-mirror-rest/server.js
  hedera-mirror-rest/transactionHash.js
Labels: bug, regression, rest

#9025 bump staging and performance envs to 0.111.0-rc4
  clusters/mainnet-staging-na/common/helmrelease.yaml
  clusters/mainnet-staging-na/mainnet-citus/helmrelease.yaml
  clusters/mainnet-staging-na/mainnet/helmrelease.yaml
  clusters/preprod/common/helmrelease.yaml
  clusters/preprod/performance-citus/helmrelease.yaml
  clusters/preprod/performance/helmrelease.yaml
Labels: deploy

#9029 remove operator balance override for testnet-na
  clusters/testnet-na/testnet/helmrelease.yaml
Labels: deploy

#9021 Add a RecordFileDownloaderPerformanceTest
  buildSrc/src/main/kotlin/java-conventions.gradle.kts
  charts/hedera-mirror-common/dashboards/hedera-mirror-importer.json
  charts/marketplace/gcp/README.md
  docs/configuration.md
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/ImporterProperties.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/downloader/record/RecordFileDownloaderPerformanceTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/downloader/record/StreamFileWriter.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/balance/AccountBalanceFileParserPerformanceTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordFileBuilder.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/RecordFileParserPerformanceTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/test/performance/PerformanceProperties.java
  hedera-mirror-importer/src/test/resources/config/application.yml
Labels: enhancement, performance, test, downloader

#9013 Initial historical integrations tests setup
  .gitignore
  hedera-mirror-web3/build.gradle.kts
  hedera-mirror-web3/src/main/resources/scripts/compile_solidity.sh
  hedera-mirror-web3/src/main/resources/scripts/install_solc_select.sh
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/web3j/TestWeb3jService.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/web3j/TestWeb3jServiceState.java
  hedera-mirror-web3/src/test/solidity_historical/DynamicEthCallsHistorical.sol
  hedera-mirror-web3/src/test/solidity_historical/EthCallHistorical.sol
  hedera-mirror-web3/src/test/solidity_historical/EvmCodesHistorical.sol
  hedera-mirror-web3/src/test/solidity_historical/HederaResponseCodes.sol
  hedera-mirror-web3/src/test/solidity_historical/HederaTokenService.sol
  hedera-mirror-web3/src/test/solidity_historical/IHederaTokenService.sol
Labels: test, web3

#9009 Handling numeric values for EntityId query parameters
  hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/EntityIdRangeParameter.java
  hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/common/EntityIdRangeParameterTest.java
  hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/controller/AllowancesControllerTest.java
Labels: enhancement, rest-java

#9035 remove operator balance override
  clusters/testnet-eu/testnet-citus/helmrelease.yaml
  clusters/testnet-eu/testnet/helmrelease.yaml
Labels: deploy

#9027 feat: Refactor selfDestruct integration tests
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/contracts/operations/SelfDestructOperationTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/AbstractContractCallServiceTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallTestSetup.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/web3j/TestWeb3jService.java
  hedera-mirror-web3/src/test/resources/contracts/SelfDestructContract/SelfDestructContract.bin
  hedera-mirror-web3/src/test/resources/contracts/SelfDestructContract/SelfDestructContract.json
  hedera-mirror-web3/src/test/solidity/SelfDestructContract.sol
Labels: enhancement, technical debt, web3

#9028 Refactor ContractCallSystemPrecompileTest
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/AbstractContractCallServiceTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallSystemPrecompileHistoricalTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallSystemPrecompileTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/OpcodeServiceTest.java
  hedera-mirror-web3/src/test/solidity/ExchangeRatePrecompile.sol
  hedera-mirror-web3/src/test/solidity/IPrngSystemContract.sol
  hedera-mirror-web3/src/test/solidity/PrngSystemContract.sol
Labels: enhancement, technical debt, web3, limechain

#9044 Update previewnet-citus connection config
  clusters/previewnet/previewnet-citus/helmrelease.yaml
Labels: deploy

#9045 Update testnet-citus connection config
  clusters/testnet-eu/testnet-citus/helmrelease.yaml
Labels: deploy

#9030 Rosetta return generic unknown operation type for future transaction types
  hedera-mirror-rosetta/app/domain/types/constants.go
  hedera-mirror-rosetta/app/domain/types/constants_test.go
  hedera-mirror-rosetta/app/persistence/transaction.go
  hedera-mirror-rosetta/app/persistence/transaction_test.go
  hedera-mirror-rosetta/app/services/block_service_test.go
  hedera-mirror-rosetta/app/services/network_service.go
  hedera-mirror-rosetta/app/services/network_service_test.go
  hedera-mirror-rosetta/go.mod
  hedera-mirror-rosetta/go.sum
  hedera-mirror-rosetta/test/domain/transaction_builder.go
Labels: enhancement, rosetta

#9043 Set start timestamp for backfill transaction hash migration in staging mainnet-citus
  clusters/mainnet-staging-na/mainnet-citus/helmrelease.yaml
Labels: deploy

#9050 increase storage size for shard 2
  clusters/mainnet-staging-na/mainnet-citus/helmrelease.yaml
Labels: deploy

#9019 Fill ethereum hash when missing in record
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/BackfillEthereumTransactionHashMigration.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/ethereum/AbstractEthereumTransactionParser.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/ethereum/CompositeEthereumTransactionParser.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/ethereum/Eip1559EthereumTransactionParser.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/ethereum/Eip2930EthereumTransactionParser.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/ethereum/EthereumTransactionParser.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/ethereum/LegacyEthereumTransactionParser.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/EthereumTransactionHandler.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/repository/FileDataRepository.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/BackfillEthereumTransactionHashMigrationTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/AbstractEntityRecordItemListenerTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerEthereumTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/ethereum/AbstractEthereumTransactionParserTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/ethereum/CompositeEthereumTransactionParserTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/ethereum/Eip1559EthereumTransactionParserTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/ethereum/Eip2930EthereumTransactionParserTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/ethereum/EthereumTransactionTestUtility.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/ethereum/LegacyEthereumTransactionParserTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/EthereumTransactionHandlerTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/repository/FileDataRepositoryTest.java
  hedera-mirror-importer/src/test/resources/data/ethereumTransaction/ethereum_transaction.json
  hedera-mirror-importer/src/test/resources/data/ethereumTransaction/file_data.sql
Labels: bug, parser

#9046 Fix disabled opcode endpoint not returning 404
  hedera-mirror-web3/build.gradle.kts
  hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/config/LoggingFilter.java
  hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/controller/GenericControllerAdvice.java
  hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/controller/ValidationErrorParser.java
  hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/DatabaseBackedStateFrame.java
  hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/viewmodel/GenericErrorResponse.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/config/LoggingFilterTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/controller/ContractControllerTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/controller/OpcodesControllerTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallEvmCodesTest.java
Labels: bug, web3

#9051 increase storage size for shard 1
  clusters/mainnet-eu/mainnet-citus/helmrelease.yaml
Labels: deploy

#9064 Fix web3 helm test
  charts/hedera-mirror-web3/postman.json
Labels: bug, regression, web3

#9063 Fixing admin_key rest example in the design
  docs/design/dynamic-addressbook.md
Labels: documentation

#9069 Deploy 0.112.0-rc1 to performance and mainnet-staging.
  clusters/mainnet-staging-na/common/helmrelease.yaml
  clusters/mainnet-staging-na/mainnet-citus/helmrelease.yaml
  clusters/mainnet-staging-na/mainnet/helmrelease.yaml
  clusters/preprod/common/helmrelease.yaml
  clusters/preprod/performance-citus/helmrelease.yaml
  clusters/preprod/performance/helmrelease.yaml
Labels: deploy

#9078 Route testnet eu traffic to citus
  clusters/testnet-eu/testnet-citus/helmrelease.yaml
  clusters/testnet-eu/testnet/helmrelease.yaml
Labels: deploy

#9075 Extract the revert tests from `ContractCallServiceTest`
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServiceTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallTestSetup.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/RevertTest.java
  hedera-mirror-web3/src/test/resources/contracts/Reverter/Reverter.bin
  hedera-mirror-web3/src/test/resources/contracts/Reverter/Reverter.json
  hedera-mirror-web3/src/test/solidity/Reverter.sol
Labels: enhancement, test, web3

#9076 Extract the internal calls tests from `ContractCallServiceTest`
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServiceTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallTestSetup.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/InternalCallsTest.java
  hedera-mirror-web3/src/test/resources/contracts/InternalCaller/InternalCaller.bin
  hedera-mirror-web3/src/test/resources/contracts/InternalCaller/InternalCaller.json
  hedera-mirror-web3/src/test/solidity/InternalCaller.sol
Labels: enhancement, test, web3

#9080 Use owner in backfill ethereum transaction hash migration
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/BackfillEthereumTransactionHashMigration.java
Labels: bug, parser

#9081 Use owner in backfill ethereum transaction hash migration (0.112)
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/BackfillEthereumTransactionHashMigration.java
Labels: bug, parser

#9085 Deploy 0.112.0-rc2 to performance and mainnet-staging
  clusters/mainnet-staging-na/common/helmrelease.yaml
  clusters/mainnet-staging-na/mainnet-citus/helmrelease.yaml
  clusters/mainnet-staging-na/mainnet/helmrelease.yaml
  clusters/preprod/common/helmrelease.yaml
  clusters/preprod/performance-citus/helmrelease.yaml
  clusters/preprod/performance/helmrelease.yaml
Labels: deploy

#9084 prepare mainnet-na for 0.111.0
  clusters/mainnet-na/common/helmrelease.yaml
  clusters/mainnet-na/mainnet/helmrelease.yaml
Labels: deploy

#9088 disable importer for mainnet-citus in eu
  clusters/mainnet-eu/mainnet-citus/helmrelease.yaml
Labels: deploy

#9089 Enable Importer mainnet-citus EU
  clusters/mainnet-eu/mainnet-citus/helmrelease.yaml
Labels: deploy

#9091 Enable ZFS In NA Cluster
  clusters/mainnet-na/common/helmrelease.yaml
  clusters/mainnet-na/common/sealed-secret.yaml
Labels: deploy

#9097 Route Traffic to Citus in EU
  clusters/mainnet-eu/common/helmrelease.yaml
  clusters/mainnet-eu/flux-system/alert-slack.yaml
  clusters/mainnet-eu/mainnet-citus/helmrelease.yaml
Labels: deploy

#9100 Enable topic message lookup in rest api for v2
  charts/hedera-mirror/values-v2.yml
Labels: bug, performance, rest

#9105 Enable topic message lookup in rest api for v2 (0.111)
  charts/hedera-mirror/values-v2.yml
Labels: bug, performance, rest

#9104 Enable topic message lookup in rest api for v2 (0.112)
  charts/hedera-mirror/values-v2.yml
Labels: bug, performance, rest

#9095 Create Mainnet Citus in NA Cluster
  clusters/mainnet-na/flux-system/alert-slack.yaml
  clusters/mainnet-na/mainnet-citus/helmrelease.yaml
  clusters/mainnet-na/mainnet-citus/helmrepository.yaml
  clusters/mainnet-na/mainnet-citus/namespace.yaml
  clusters/mainnet-na/mainnet-citus/sealed-secret.yaml
Labels: deploy

#9106 Enable Stackgres Mainnet NA
  clusters/mainnet-na/common/helmrelease.yaml
Labels: deploy

#9110 Disable Postgres Node Exporter
  clusters/mainnet-eu/mainnet-citus/helmrelease.yaml
Labels: deploy

#9102 Turn Traffic Off to EU Cluster
  clusters/mainnet-eu/mainnet-citus/helmrelease.yaml
Labels: deploy

#9112 Enable Ingresses in Citus EU
  clusters/mainnet-eu/mainnet-citus/helmrelease.yaml
Labels: deploy

#9115 Retain existing allowance (spender) columns when updating NFT metadata
  hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/entity/EntityId.java
  hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/token/AbstractNft.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenUpdateNftsTransactionHandler.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerTokenTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenUpdateNftsTransactionHandlerTest.java
Labels: bug, regression, parser, nft

#9116 Use customized stackgres-operator 1.9.0 image in staging
  clusters/mainnet-staging-na/common/helmrelease.yaml
Labels: deploy

#9101 Re-enable testnet-na monitor in preparation of 0.111.1 upgrade
  clusters/testnet-na/testnet/helmrelease.yaml
Labels: deploy

#9117 Retain existing allowance (spender) columns when updating NFT metadata (0.111)
  hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/entity/EntityId.java
  hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/token/AbstractNft.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenUpdateNftsTransactionHandler.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerTokenTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenUpdateNftsTransactionHandlerTest.java
Labels: bug, regression, parser, nft

#9118 Fix stackgres operator image syntax in mainnet staging
  clusters/mainnet-staging-na/common/helmrelease.yaml
Labels: deploy

#9120 Disable stackgres metrics exporter in testnet-eu
  clusters/testnet-eu/testnet-citus/helmrelease.yaml
Labels: deploy

#9121 Adjust some stackgres charts configs
  charts/hedera-mirror/values-prod.yaml
  charts/hedera-mirror/values.yaml
Labels: enhancement

#9119 Retain existing allowance (spender) columns when updating NFT metadata (0.112)
  hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/entity/EntityId.java
  hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/token/AbstractNft.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenUpdateNftsTransactionHandler.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerTokenTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenUpdateNftsTransactionHandlerTest.java
Labels: bug, regression, parser, nft

#9122 Adjust some stackgres charts configs (0.112)
  charts/hedera-mirror/values-prod.yaml
  charts/hedera-mirror/values.yaml
Labels: enhancement

#9123 Adjust some stackgres charts configs (0.111)
  charts/hedera-mirror/values-prod.yaml
  charts/hedera-mirror/values.yaml
Labels: enhancement

#9126 bump to 0.111.1 for mainnet NA
  clusters/mainnet-na/common/helmrelease.yaml
  clusters/mainnet-na/mainnet/helmrelease.yaml
Labels: deploy

#9127 Deploy 0.112.0-rc3 to mainnet-staging
  clusters/mainnet-staging-na/common/helmrelease.yaml
  clusters/mainnet-staging-na/mainnet-citus/helmrelease.yaml
  clusters/mainnet-staging-na/mainnet/helmrelease.yaml
Labels: deploy

#9128 Fix previewnet reset behavior
  clusters/previewnet/previewnet/helmrelease.yaml
Labels: deploy

#9132 Suppress drift detection for SGScript in mainnet
  clusters/mainnet-eu/mainnet-citus/helmrelease.yaml
  clusters/mainnet-na/mainnet-citus/helmrelease.yaml
Labels: deploy

#9131 Fix previewnet-citus reset behavior
  clusters/previewnet/previewnet-citus/helmrelease.yaml
Labels: deploy

#9092 Refactor `ContractCallServiceTest`
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/AbstractContractCallServiceTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServiceTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallTestSetup.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/utils/ContractCallTestUtil.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/web3j/TestWeb3jService.java
  hedera-mirror-web3/src/test/resources/contracts/EthCall/EthCall.bin
  hedera-mirror-web3/src/test/resources/contracts/EthCall/EthCall.json
  hedera-mirror-web3/src/test/resources/contracts/EthCall/EthCall.sol
  hedera-mirror-web3/src/test/resources/contracts/EthCall/EthCallInit.bin
  hedera-mirror-web3/src/test/resources/contracts/EthCall/State.bin
  hedera-mirror-web3/src/test/resources/contracts/TestContractAddress/TestAddressThis.bin
  hedera-mirror-web3/src/test/resources/contracts/TestContractAddress/TestAddressThis.json
  hedera-mirror-web3/src/test/resources/contracts/TestContractAddress/TestAddressThisInit.bin
Labels: enhancement, test, web3

#9134 Refactor ContractCallEvmCodesHistoricalTests to use the web3j
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallEvmCodesHistoricalTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/utils/ContractCallTestUtil.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/web3j/TestWeb3jService.java
  hedera-mirror-web3/src/test/solidity_historical/EvmCodesHistorical.sol
Labels: enhancement, technical debt, web3, limechain

#9114 Standardize rest-java error response
  hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/config/LoggingFilter.java
  hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/controller/GenericControllerAdvice.java
  hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/config/LoggingFilterTest.java
  hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/controller/AllowancesControllerTest.java
  hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/controller/ControllerTest.java
  hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/controller/TopicControllerTest.java
  hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/config/LoggingFilter.java
Labels: enhancement, rest-java

#9040 Refactor `ContractCallServiceERCTokenTest` modification functions
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServiceERCTokenModificationFunctionsTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServiceERCTokenTest.java
Labels: enhancement, technical debt, test, web3

#9140 Turn on Importer and Turn Off Drift Detection
  clusters/mainnet-na/mainnet-citus/helmrelease.yaml
Labels: deploy

#9145 temporarily set coordinator instances to 1
  clusters/mainnet-na/mainnet-citus/helmrelease.yaml
Labels: deploy

#9142 enable importer mainnet-citus NA
  clusters/mainnet-na/mainnet-citus/helmrelease.yaml
Labels: deploy

#9165 Change testnet-eu citus helmrelease drift protection to warn
  clusters/testnet-eu/testnet-citus/helmrelease.yaml
Labels: deploy

#9163 Refactor `ContractCallServiceERCTokenTest` delegate transfer
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServiceERCTokenModificationFunctionsTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServiceERCTokenTest.java
Labels: enhancement, technical debt, test, web3

#9137 Refactor `ContractCallServiceERCTokenTest` negative scenarios
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServiceERCTokenReadOnlyFunctionsTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServiceERCTokenTest.java
Labels: enhancement, technical debt, test, web3

#9164 feat: Refactor ContractCallNestedCallsHistoricalTest
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallNestedCallsHistoricalTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/web3j/TestWeb3jService.java
  hedera-mirror-web3/src/test/solidity_historical/NestedCallsHistorical.sol
Labels: enhancement, technical debt, web3, limechain

#9170 prepare traffic for mainnet-citus in EU
  clusters/mainnet-eu/mainnet-citus/helmrelease.yaml
Labels: deploy

#9171 Turn off public traffic to testnet-na
  clusters/testnet-na/testnet/helmrelease.yaml
Labels: deploy

#9082 Upgrade Stackgres to 1.11.0
  .github/workflows/charts.yml
  charts/hedera-mirror-common/Chart.yaml
  docs/runbook/increase-pvc-size-for-statefulset.md
  docs/runbook/perform-stackgres-security-upgrade.md
Labels: dependencies

#9144 Disable postgres SSL to fix random query timeout
  charts/hedera-mirror-common/templates/test-rest-java.yaml
  charts/hedera-mirror-common/templates/test-rest.yaml
  charts/hedera-mirror-common/templates/test-web3.yaml
  charts/hedera-mirror/templates/stackgres/stackgres-cluster.yaml
  charts/hedera-mirror/values.yaml
Labels: bug, enhancement, performance, database

#9178 Disable postgres SSL to fix random query timeout (0.112)
  charts/hedera-mirror-common/templates/test-rest-java.yaml
  charts/hedera-mirror-common/templates/test-rest.yaml
  charts/hedera-mirror-common/templates/test-web3.yaml
  charts/hedera-mirror/templates/stackgres/stackgres-cluster.yaml
  charts/hedera-mirror/values.yaml
Labels: bug, performance, database

#9177 Enable testnet-na monitor in preparation of 112 upgrade
  clusters/testnet-na/testnet/helmrelease.yaml
Labels: deploy

#9186 Clean up stackgres config in testnet-eu
  clusters/testnet-eu/common/helmrelease.yaml
  clusters/testnet-eu/testnet-citus/helmrelease.yaml
Labels: deploy

#9182 Update the web3j-cli download task to use the official release
  hedera-mirror-web3/build.gradle.kts
  hedera-mirror-web3/src/main/resources/scripts/compile_solidity.sh
Labels: enhancement, technical debt, test, web3

#9175 Refactor ContractDebugServiceTest modification precompile functions
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/AbstractContractCallServiceTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServicePrecompileTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractDebugServiceTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/utils/ContractFunctionProviderRecord.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/utils/OpcodeTracerUtil.java
Labels: enhancement, technical debt, web3, limechain

#9187 Deploy 0.112.0 to mainnet-na and mainnet-na-citus.
  clusters/mainnet-na/common/helmrelease.yaml
  clusters/mainnet-na/mainnet-citus/helmrelease.yaml
  clusters/mainnet-na/mainnet/helmrelease.yaml
  clusters/mainnet-na/mainnet/sealed-secret.yaml
Labels: deploy

#9193 Deploying 0.112.0 on mainnet-eu for V1 and V2.
  clusters/mainnet-eu/common/helmrelease.yaml
  clusters/mainnet-eu/mainnet-citus/helmrelease.yaml
  clusters/mainnet-eu/mainnet/helmrelease.yaml
  clusters/mainnet-eu/mainnet/sealed-secret.yaml
Labels: deploy

#9194 Enabling ingress for mainnet-eu-citus
  clusters/mainnet-eu/mainnet-citus/helmrelease.yaml
Labels: deploy

#9189 Return 501 NOT_SUPPORTED error response for unsupported precompiles
  hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/controller/GenericControllerAdvice.java
  hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/exception/PrecompileNotSupportedException.java
  hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/AbiConstants.java
  hedera-mirror-web3/src/main/java/com/hedera/services/store/contracts/precompile/HTSPrecompiledContract.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/controller/ContractControllerTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/store/contract/precompile/HTSPrecompiledContractTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServicePrecompileTest.java
  hedera-mirror-web3/src/test/solidity/PrecompileTestContract.sol
Labels: enhancement, web3

#9185 Refactor ContractCallSystemPrecompileHistoricalTest
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallSystemPrecompileHistoricalTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallTestSetup.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/OpcodeServiceTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/utils/ContractCallTestUtil.java
  hedera-mirror-web3/src/test/solidity_historical/ExchangeRatePrecompileHistorical.sol
  hedera-mirror-web3/src/test/solidity_historical/IPrngSystemContractHistorical.sol
  hedera-mirror-web3/src/test/solidity_historical/PrngSystemContractHistorical.sol
Labels: enhancement, technical debt, web3, limechain

#9179 Refactor ContractDebugServiceTest dynamic calls, nested calls enum
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/AbstractContractCallServiceOpcodeTracerTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallDynamicCallsTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallNestedCallsHistoricalTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallNestedCallsTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServicePrecompileTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractDebugServiceTest.java
Labels: enhancement, technical debt, web3, limechain

#9197 Optimize stackgres connection pooling
  charts/hedera-mirror-common/values.yaml
  charts/hedera-mirror/templates/stackgres/stackgres-cluster.yaml
  charts/hedera-mirror/templates/stackgres/stackgres-pooling-config-coordinator.yaml
  charts/hedera-mirror/templates/stackgres/stackgres-pooling-config-worker.yaml
  charts/hedera-mirror/values.yaml
  hedera-mirror-test/k6/src/rest/test/contractsResult.js
Labels: enhancement, database

#9198 Optimize stackgres connection pooling (0.112)
  charts/hedera-mirror-common/values.yaml
  charts/hedera-mirror/templates/stackgres/stackgres-cluster.yaml
  charts/hedera-mirror/templates/stackgres/stackgres-pooling-config-coordinator.yaml
  charts/hedera-mirror/templates/stackgres/stackgres-pooling-config-worker.yaml
  charts/hedera-mirror/values.yaml
  hedera-mirror-test/k6/src/rest/test/contractsResult.js
Labels: enhancement, database

#9202 Deploy 0.112.1-rc1 to staging
  clusters/mainnet-staging-na/common/helmrelease.yaml
  clusters/mainnet-staging-na/mainnet-citus/helmrelease.yaml
  clusters/mainnet-staging-na/mainnet/helmrelease.yaml
Labels: deploy
