Repository hiero-ledger/hiero-mirror-node, pull requests merged in 2024-10, with the labels that each got.

#9486 feat: Use official web3j gradle plugin
  build.gradle.kts
  buildSrc/build.gradle.kts
Labels: dependencies, java, web3

#9487 Add response codes for protobuf 0.54.0
  hedera-mirror-rest/model/transactionResult.js
Labels: enhancement, rest

#9490 Upgrade mainnet-staging to 0.115.0-beta1
  clusters/mainnet-staging-na/common/helmrelease.yaml
  clusters/mainnet-staging-na/mainnet-citus/helmrelease.yaml
  clusters/mainnet-staging-na/mainnet/helmrelease.yaml
Labels: deploy

#9491 Upgrade performance to 0.115.0-beta1
  clusters/preprod/common/helmrelease.yaml
  clusters/preprod/performance-citus/helmrelease.yaml
  clusters/preprod/performance/helmrelease.yaml
Labels: deploy

#9414 Add implementation for AccountReadableKVState
  hedera-mirror-web3/src/main/java/com/hedera/hapi/node/state/token/Account.java
  hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/common/ContractCallContext.java
  hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/service/ContractDebugService.java
  hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/AccountReadableKVState.java
  hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/CommonEntityAccessor.java
  hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/Utils.java
  hedera-mirror-web3/src/main/java/com/hedera/services/utils/EntityIdUtils.java
  hedera-mirror-web3/src/test/java/com/hedera/hapi/node/state/token/AccountApprovalForAllAllowanceTest.java
  hedera-mirror-web3/src/test/java/com/hedera/hapi/node/state/token/AccountCryptoAllowanceTest.java
  hedera-mirror-web3/src/test/java/com/hedera/hapi/node/state/token/AccountFungibleTokenAllowanceTest.java
  hedera-mirror-web3/src/test/java/com/hedera/hapi/node/state/token/AccountIDTest.java
  hedera-mirror-web3/src/test/java/com/hedera/hapi/node/state/token/AccountTest.java
  hedera-mirror-web3/src/test/java/com/hedera/hapi/node/state/token/ContractIDTest.java
  hedera-mirror-web3/src/test/java/com/hedera/hapi/node/state/token/KeyTest.java
  hedera-mirror-web3/src/test/java/com/hedera/hapi/node/state/token/NftIDTest.java
  hedera-mirror-web3/src/test/java/com/hedera/hapi/node/state/token/PendingAirdropIdTest.java
  hedera-mirror-web3/src/test/java/com/hedera/hapi/node/state/token/TokenIDTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/state/AccountReadableKVStateTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/state/CommonEntityAccessorTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/state/UtilsTest.java
  hedera-mirror-web3/src/test/java/com/hedera/services/utils/EntityIdUtilsTest.java
Labels: enhancement, web3

#9492 Remove jetbrains annotation dependency
  build.gradle.kts
  buildSrc/src/main/kotlin/java-conventions.gradle.kts
  hedera-mirror-common/build.gradle.kts
  hedera-mirror-graphql/src/main/java/com/hedera/mirror/graphql/scalar/GraphQlDuration.java
  hedera-mirror-graphql/src/main/java/com/hedera/mirror/graphql/scalar/GraphQlTimestamp.java
  hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/controller/GenericControllerAdvice.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/controller/OpcodesControllerTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/utils/RuntimeBytecodeExtractor.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/utils/TransactionProviderEnum.java
Labels: enhancement, technical debt

#9450 Implement `ContractStorageReadableKVState`
  hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/ContractStorageReadableKVState.java
  hedera-mirror-web3/src/main/java/com/hedera/services/utils/EntityIdUtils.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/state/ContractStorageReadableKVStateTest.java
  hedera-mirror-web3/src/test/java/com/hedera/services/utils/EntityIdUtilsTest.java
Labels: enhancement, web3

#9494 Delete mainnet-staging/mainnet deployment
  clusters/mainnet-staging-na/flux-system/alert-github-dispatch.yaml
  clusters/mainnet-staging-na/flux-system/alert-slack.yaml
  clusters/mainnet-staging-na/mainnet-citus/helmrelease.yaml
  clusters/mainnet-staging-na/mainnet/helmrelease.yaml
  clusters/mainnet-staging-na/mainnet/helmrepository.yaml
  clusters/mainnet-staging-na/mainnet/namespace.yaml
  clusters/mainnet-staging-na/mainnet/sealed-secret.yaml
Labels: deploy

#9499 Remove Github Dispatch Resource
  clusters/mainnet-staging-na/flux-system/kustomization.yaml
Labels: deploy

#9496 Reduce Worker Memory For Citus and Delete Mainnet Deployment in Mainnet NA
  clusters/mainnet-na/flux-system/alert-github-dispatch.yaml
  clusters/mainnet-na/flux-system/alert-slack.yaml
  clusters/mainnet-na/mainnet-citus/helmrelease.yaml
  clusters/mainnet-na/mainnet/helmrelease.yaml
  clusters/mainnet-na/mainnet/helmrepository.yaml
  clusters/mainnet-na/mainnet/namespace.yaml
  clusters/mainnet-na/mainnet/sealed-secret.yaml
Labels: deploy

#9497 Reduce Worker Memory For Citus and Delete Mainnet Deployment in Mainnet EU
  clusters/mainnet-eu/flux-system/alert-slack.yaml
  clusters/mainnet-eu/mainnet-citus/helmrelease.yaml
  clusters/mainnet-eu/mainnet/helmrelease.yaml
  clusters/mainnet-eu/mainnet/helmrepository.yaml
  clusters/mainnet-eu/mainnet/namespace.yaml
  clusters/mainnet-eu/mainnet/sealed-secret.yaml
Labels: deploy

#9493 Fix equals() and hashCode() for AccountReadableKVState
  hedera-mirror-web3/src/main/java/com/hedera/hapi/node/state/token/Account.java
  hedera-mirror-web3/src/test/java/com/hedera/hapi/node/state/token/AccountTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/state/AccountReadableKVStateTest.java
Labels: enhancement, web3

#9531 Add node metrics to monitor metrics
  buildSrc/src/main/kotlin/common-conventions.gradle.kts
  buildSrc/src/main/kotlin/go-conventions.gradle.kts
  buildSrc/src/main/kotlin/java-conventions.gradle.kts
  hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/NodeProperties.java
  hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/NodeSupplier.java
  hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/PublishMetrics.java
  hedera-mirror-monitor/src/main/resources/application.yml
  hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/NodeSupplierTest.java
  hedera-mirror-monitor/src/test/java/com/hedera/mirror/monitor/publish/PublishMetricsTest.java
Labels: enhancement, monitor

#9452 Implement `ContractBytecodeReadableKVState`
  hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/CommonEntityAccessor.java
  hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/ContractBytecodeReadableKVState.java
  hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/Utils.java
  hedera-mirror-web3/src/main/java/com/hedera/services/utils/EntityIdUtils.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/state/ContractBytecodeReadableKVStateTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/state/UtilsTest.java
  hedera-mirror-web3/src/test/java/com/hedera/services/utils/EntityIdUtilsTest.java
Labels: enhancement, web3

#9424 Update jooq repository to improve reusability
  hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/EntityIdRangeParameter.java
  hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/RangeOperator.java
  hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/RangeParameter.java
  hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/controller/AllowancesController.java
  hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/controller/TokenAirdropsController.java
  hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/dto/NftAllowanceRequest.java
  hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/dto/TokenAirdropRequest.java
  hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/repository/JooqRepository.java
  hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/repository/NftAllowanceRepositoryCustomImpl.java
  hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/repository/TokenAirdropRepositoryCustomImpl.java
  hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/Bound.java
  hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/NftAllowanceServiceImpl.java
  hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/RestJavaIntegrationTest.java
  hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/controller/TokenAirdropsControllerTest.java
  hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/repository/JooqRepositoryTest.java
  hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/repository/NftAllowanceRepositoryTest.java
  hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/repository/TokenAirdropRepositoryTest.java
  hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/service/NftAllowanceServiceTest.java
Labels: enhancement, rest-java

#9483 Add NFTs to airdrop REST APIs
  docs/database/README.md
  docs/database/bootstrap.md
  hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/controller/TokenAirdropsController.java
  hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/controller/TokenAirdropsControllerTest.java
  hedera-mirror-rest/api/v1/openapi.yml
Labels: enhancement, rest-java

#9535 Update jooq repository to improve reusability (0.115.0)
  hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/EntityIdRangeParameter.java
  hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/RangeOperator.java
  hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/RangeParameter.java
  hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/controller/AllowancesController.java
  hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/controller/TokenAirdropsController.java
  hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/dto/NftAllowanceRequest.java
  hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/dto/TokenAirdropRequest.java
  hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/repository/JooqRepository.java
  hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/repository/NftAllowanceRepositoryCustomImpl.java
  hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/repository/TokenAirdropRepositoryCustomImpl.java
  hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/Bound.java
  hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/NftAllowanceServiceImpl.java
  hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/RestJavaIntegrationTest.java
  hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/controller/TokenAirdropsControllerTest.java
  hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/repository/JooqRepositoryTest.java
  hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/repository/NftAllowanceRepositoryTest.java
  hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/repository/TokenAirdropRepositoryTest.java
  hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/service/NftAllowanceServiceTest.java
Labels: enhancement, rest-java

#9536 Add NFTs to airdrop REST APIs (0.115.0)
  docs/database/README.md
  docs/database/bootstrap.md
  hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/controller/TokenAirdropsController.java
  hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/controller/TokenAirdropsControllerTest.java
  hedera-mirror-rest/api/v1/openapi.yml
Labels: enhancement, rest-java

#9537 Bump express from 4.2.0 to 4.2.1
  hedera-mirror-rest/monitoring/package-lock.json
  hedera-mirror-rest/monitoring/package.json
  hedera-mirror-rest/package-lock.json
  hedera-mirror-rest/package.json
Labels: security, dependencies, javascript

#9503 Add HIP-991 design
  docs/design/topic-custom-fees.md
Labels: documentation

#9533 Add Citus to testnet-na
  clusters/testnet-na/common/helmrelease.yaml
  clusters/testnet-na/common/sealed-secret.yaml
  clusters/testnet-na/flux-system/alert-slack.yaml
  clusters/testnet-na/testnet-citus/helmrelease.yaml
  clusters/testnet-na/testnet-citus/helmrepository.yaml
  clusters/testnet-na/testnet-citus/namespace.yaml
  clusters/testnet-na/testnet-citus/sealed-secret.yaml
Labels: deploy, citus

#9500 Remove Previewnet Deployment
  clusters/previewnet/flux-system/alert-github-dispatch.yaml
  clusters/previewnet/flux-system/alert-slack.yaml
  clusters/previewnet/flux-system/kustomization.yaml
  clusters/previewnet/previewnet/helmrelease.yaml
  clusters/previewnet/previewnet/helmrepository.yaml
  clusters/previewnet/previewnet/namespace.yaml
  clusters/previewnet/previewnet/sealed-secret.yaml
Labels: deploy

#9547 Prepare Testnet NA For Citus Only
  clusters/testnet-na/flux-system/alert-github-dispatch.yaml
  clusters/testnet-na/flux-system/alert-slack.yaml
  clusters/testnet-na/testnet-citus/helmrelease.yaml
  clusters/testnet-na/testnet/helmrelease.yaml
  clusters/testnet-na/testnet/helmrepository.yaml
  clusters/testnet-na/testnet/namespace.yaml
  clusters/testnet-na/testnet/sealed-secret.yaml
Labels: deploy

#9532 Add tools and instructions for REST API traffic replay
  .github/dependabot.yml
  build.gradle.kts
  hedera-mirror-test/traffic-replay/README.md
  hedera-mirror-test/traffic-replay/log-downloader/converter.js
  hedera-mirror-test/traffic-replay/log-downloader/downloader.js
  hedera-mirror-test/traffic-replay/log-downloader/index.js
  hedera-mirror-test/traffic-replay/log-downloader/package-lock.json
  hedera-mirror-test/traffic-replay/log-downloader/package.json
Labels: enhancement, performance

#9542 Remove recoverable errors for inactive EVM addresses
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/domain/ContractResultServiceImplTest.java
Labels: bug, parser

#9534 Suppress INVALID_ALIAS_KEY and INVALID_NODE_ACCOUNT_ID recoverable errors
  hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/RecordItem.java
  hedera-mirror-common/src/test/java/com/hedera/mirror/common/domain/transaction/RecordItemTest.java
Labels: bug, parser

#9546 Remove Performance Deployment
  clusters/preprod/flux-system/alert-github-dispatch-performance.yaml
  clusters/preprod/flux-system/kustomization.yaml
  clusters/preprod/flux-system/sealed-secret-github-dispatch.yaml
  clusters/preprod/performance/helmrelease.yaml
  clusters/preprod/performance/helmrepository.yaml
  clusters/preprod/performance/namespace.yaml
  clusters/preprod/performance/sealed-secret.yaml
Labels: deploy

#9549 Remove testnet-eu v1 deploy
  clusters/testnet-eu/flux-system/alert-slack.yaml
  clusters/testnet-eu/testnet-citus/helmrelease.yaml
  clusters/testnet-eu/testnet/helmrelease.yaml
  clusters/testnet-eu/testnet/helmrepository.yaml
  clusters/testnet-eu/testnet/namespace.yaml
  clusters/testnet-eu/testnet/sealed-secret.yaml
Labels: deploy, citus

#9528 Add acceptance tests for fungible token airdrop
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/MirrorNodeClient.java
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
  hedera-mirror-test/src/test/resources/features/token/token.feature
Labels: enhancement, test

#9548 Add k6 tests for token airdrops
  hedera-mirror-test/k6/README.md
  hedera-mirror-test/k6/src/rest-java/libex/constants.js
  hedera-mirror-test/k6/src/rest-java/libex/parameters.js
  hedera-mirror-test/k6/src/rest-java/test/accountsOutstandingAirdrop.js
  hedera-mirror-test/k6/src/rest-java/test/accountsPendingAirdrop.js
  hedera-mirror-test/k6/src/rest-java/test/index.js
Labels: enhancement, performance, test

#9564 Migrate deprecated jest methods
  hedera-mirror-rest/__tests__/entityId.test.js
  hedera-mirror-rest/__tests__/middleware/responseHandler.test.js
  hedera-mirror-rest/__tests__/model/exchangeRate.test.js
  hedera-mirror-rest/__tests__/model/feeSchedule.test.js
  hedera-mirror-rest/__tests__/model/transactionType.test.js
  hedera-mirror-rest/__tests__/service/contractService.test.js
Labels: enhancement, technical debt, rest

#9527 Implement `AliasesReadableKVState `
  hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/config/EvmConfiguration.java
  hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/EntityRepository.java
  hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/AliasesReadableKVState.java
  hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/CommonEntityAccessor.java
  hedera-mirror-web3/src/main/java/com/hedera/services/utils/EntityIdUtils.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/repository/EntityRepositoryTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/state/AliasesReadableKVStateTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/state/CommonEntityAccessorTest.java
  hedera-mirror-web3/src/test/java/com/hedera/services/utils/EntityIdUtilsTest.java
Labels: enhancement, web3

#9572 Add Token readable kv state
  hedera-mirror-web3/src/main/java/com/hedera/hapi/node/state/token/Token.java
  hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/CommonEntityAccessor.java
  hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/TokenReadableKVState.java
  hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/utils/Suppliers.java
  hedera-mirror-web3/src/main/java/com/hedera/services/utils/EntityIdUtils.java
  hedera-mirror-web3/src/test/java/com/hedera/hapi/node/state/token/AbstractStateTest.java
  hedera-mirror-web3/src/test/java/com/hedera/hapi/node/state/token/TokenTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/state/CommonEntityAccessorTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/state/TokenReadableKVStateTest.java
  hedera-mirror-web3/src/test/java/com/hedera/services/utils/EntityIdUtilsTest.java
Labels: enhancement, web3

#9540 Add acceptance tests for NFT airdrop
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/MirrorNodeClient.java
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
  hedera-mirror-test/src/test/resources/features/token/token.feature
Labels: enhancement, test

#9570 Add FileReadableKVState
  hedera-mirror-web3/src/main/java/com/hedera/hapi/node/state/file/File.java
  hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/FileReadableKVState.java
  hedera-mirror-web3/src/main/java/com/hedera/services/utils/EntityIdUtils.java
  hedera-mirror-web3/src/test/java/com/hedera/hapi/node/state/file/FileTest.java
  hedera-mirror-web3/src/test/java/com/hedera/hapi/node/state/token/AbstractStateTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/state/FileReadableKVStateTest.java
  hedera-mirror-web3/src/test/java/com/hedera/services/utils/EntityIdUtilsTest.java
Labels: enhancement, web3

#9578 Fix recursive update exception in `EntityIdServiceImpl`
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/EntityIdServiceImpl.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/domain/EntityIdServiceImplTest.java
Labels: bug, parser

#9585 Deploy v0.115.0 to mainnet-na
  clusters/mainnet-na/common/helmrelease.yaml
  clusters/mainnet-na/mainnet-citus/helmrelease.yaml
Labels: deploy

#9541 Automated Backup For Citus
  charts/hedera-mirror-common/Chart.yaml
  charts/hedera-mirror-common/templates/zfs/volumesnaphotclass.yaml
  charts/hedera-mirror-common/values-v2.yaml
  charts/hedera-mirror-common/values.yaml
  charts/hedera-mirror/templates/stackgres/stackgres-backup-disruption-budget.yaml
  charts/hedera-mirror/templates/stackgres/stackgres-cluster.yaml
  charts/hedera-mirror/templates/stackgres/stackgres-objectstorage-secret.yaml
  charts/hedera-mirror/templates/stackgres/stackgres-objectstorage.yaml
  charts/hedera-mirror/values-prod.yaml
  charts/hedera-mirror/values.yaml
Labels: enhancement, database

#9590 Use Rest Java To Retrieve Airdrop Data
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/MirrorNodeClient.java
Labels: bug, test, rest-java

#9593 Comment Out Failing Acceptance Test Steps
  hedera-mirror-test/src/test/resources/features/contract/estimatePrecompile.feature
Labels: bug, test, regression

#9587 Prepare Previewnet For 116 Auto-deploy
  clusters/previewnet/common/helmrelease.yaml
Labels: deploy

#9597 Auto Deploy pre-release for Citus
  clusters/previewnet/previewnet-citus/helmrelease.yaml
Labels: deploy

#9594 Prepare Staging For 116 Release
  clusters/mainnet-staging-na/common/helmrelease.yaml
  clusters/mainnet-staging-na/mainnet-citus/helmrelease.yaml
Labels: deploy

#9595 Prepare Preprod For 116
  clusters/preprod/common/helmrelease.yaml
  clusters/preprod/performance-citus/helmrelease.yaml
Labels: deploy

#9600 Enable log retention in Loki and fix restjava routing
  charts/hedera-mirror-common/values.yaml
  charts/hedera-mirror-rest-java/values.yaml
  charts/hedera-mirror-web3/values.yaml
Labels: enhancement, process

#9601 Enable log retention in Loki and fix restjava routing
  charts/hedera-mirror-common/values.yaml
  charts/hedera-mirror-rest-java/values.yaml
  charts/hedera-mirror-web3/values.yaml
Labels: enhancement, process

#9603 Set delete_request_store for loki
  charts/hedera-mirror-common/values.yaml
Labels: enhancement, process

#9604 Set delete_request_store for loki (0.116)
  charts/hedera-mirror-common/values.yaml
Labels: enhancement, process

#9602 Prepare preprod For 116-rc2
  clusters/preprod/common/helmrelease.yaml
  clusters/preprod/performance-citus/helmrelease.yaml
Labels: deploy

#9607 Bump staging and integration-docker to v0.116.0-rc3
  clusters/mainnet-staging-na/common/helmrelease.yaml
  clusters/mainnet-staging-na/mainnet-citus/helmrelease.yaml
  clusters/preprod/integration-docker/helmrelease.yaml
Labels: deploy

#9608 Fix empty ipAddressV4 returning 127.0.0.1 in gRPC nodes API
  build.gradle.kts
  charts/hedera-mirror-common/values.yaml
  docs/checklist/release.md
  hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/controller/NetworkController.java
  hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/controller/NetworkControllerTest.java
Labels: bug, grpc

#9598 Implement `AirdropsReadableKVState`
  hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/config/EvmConfiguration.java
  hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenAirdropRepository.java
  hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/AirdropsReadableKVState.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/repository/TokenAirdropRepositoryTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/state/AirdropsReadableKVStateTest.java
Labels: enhancement, web3

#9625 Bump staging-lg to 0.116.0-rc3
  clusters/preprod/staging-lg/helmrelease.yaml
Labels: deploy

#9631 ci: Updating action to use step-security maintained version.
  .github/workflows/deploy.yaml
  .github/workflows/release-automation.yml
  .github/workflows/release-integration.yml
Labels: github_actions

#9633 Make clear millisecond is the implied unit for frequency configurations
  docs/configuration.md
Labels: documentation

#9638 Disable Automated Backup
  charts/hedera-mirror-common/values-v2.yaml
  charts/hedera-mirror/values-prod.yaml
Labels: enhancement, database

#9635 Fixing whitespace in configuration documentation
  docs/configuration.md
Labels: documentation

#9639 Disable Automated Backup Cherry-Pick
  build.gradle.kts
  charts/hedera-mirror-common/values-v2.yaml
  charts/hedera-mirror/values-prod.yaml
Labels: enhancement, database

#9640 Bump Spring Boot from 3.3.4 to 3.3.5
  build.gradle.kts
  buildSrc/build.gradle.kts
  docs/importer/README.md
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/downloader/record/StreamFileWriter.java
Labels: dependencies, java

#9641 Prepare testnet-na for v0.116.0
  clusters/testnet-na/common/helmrelease.yaml
Labels: deploy

#9670 Fix restjava topics info endpoint ingress path regex
  charts/hedera-mirror-rest-java/values.yaml
Labels: bug, regression, rest

#9622 Convert EVM properties to a map of configuration properties
  hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmProperties.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/properties/MirrorNodeEvmPropertiesIntegrationTest.java
  hedera-mirror-web3/src/test/resources/config/application.yml
Labels: enhancement, web3

#9671 Fix restjava topics info endpoint ingress path regex (0.116)
  charts/hedera-mirror-rest-java/values.yaml
Labels: bug, regression, rest

#9644 Auto Deploy Latest Release
  clusters/preprod/integration-docker/helmrelease.yaml
  clusters/preprod/staging-lg/helmrelease.yaml
Labels: deploy

#9591 Add REST API query normalization
  hedera-mirror-rest/__tests__/middleware/requestNormalizer.test.js
  hedera-mirror-rest/api/v1/openapi.yml
  hedera-mirror-rest/middleware/openapiHandler.js
  hedera-mirror-rest/middleware/requestNormalizer.js
  hedera-mirror-rest/server.js
Labels: enhancement, performance, rest

#9677 Update performance to v0.117.0-rc1
  clusters/preprod/common/helmrelease.yaml
  clusters/preprod/performance-citus/helmrelease.yaml
Labels: deploy

#9678 Update mainnet-staging to v0.117.0-rc1
  clusters/mainnet-staging-na/common/helmrelease.yaml
  clusters/mainnet-staging-na/mainnet-citus/helmrelease.yaml
Labels: deploy

#9398 Add Various Citus Runbooks
  charts/hedera-mirror-common/templates/zfs/configmap-init.yaml
  docs/runbook/change-citus-node-pool-machine-type.md
  docs/runbook/create-disk-snapshot-for-citus-cluster.md
  docs/runbook/increase-zfs-disksize.md
  docs/runbook/restore-citus-from-disk-snapshot.md
  docs/runbook/scripts/change-machine-type.sh
  docs/runbook/scripts/restore-volume-snapshot.sh
  docs/runbook/scripts/upgrade-k8s-version-citus.sh
  docs/runbook/scripts/utils.sh
  docs/runbook/scripts/volume-snapshot.sh
  docs/runbook/upgrade-k8s-version-citus-nodepool.md
Labels: documentation, enhancement

#9683 Deploy 0.116.1 To mainnet-na
  clusters/mainnet-na/common/helmrelease.yaml
  clusters/mainnet-na/mainnet-citus/helmrelease.yaml
Labels: deploy

#9681 Fix token.id Param Validation
  hedera-mirror-rest/__tests__/specs/accounts/{id}/tokens/invalid-params.json
  hedera-mirror-rest/utils.js
Labels: bug, good first issue, rest, good first issue candidate
