Repository hiero-ledger/hiero-mirror-node, pull requests merged in 2024-07, with the labels that each got.

#8666 Optimize web3 fungible token historical total supply query
  hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/utils/EvmTokenUtils.java
  hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/TokenRepository.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/Web3IntegrationTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/common/TransactionIdOrHashParameterTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/common/TransactionIdParameterTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/contracts/operations/SelfDestructOperationTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/pricing/RatesAndFeesLoaderIntegrationTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/token/TokenAccessorImplTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/utils/EvmTokenUtilsTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/repository/NftRepositoryTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/repository/TokenRepositoryTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallDynamicCallsTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallEvmCodesTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallNativePrecompileTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServiceTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallTestSetup.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractDebugServiceTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/OpcodeServiceTest.java
Labels: bug, performance, test, web3

#8679 Bump dependency-check-gradle from 9.2.0 to 10.0.1
  buildSrc/build.gradle.kts
Labels: dependencies

#8687 Re-enable transaction state proof in testnet-na
  clusters/testnet-na/testnet/helmrelease.yaml
Labels: enhancement, deploy

#8688 Disable rest monitor in testnet-na
  clusters/testnet-na/testnet/helmrelease.yaml
Labels: bug, monitor, deploy

#8692 Update Mainnet EU CItus to 108
  clusters/mainnet-eu/mainnet-citus/helmrelease.yaml
Labels: enhancement, deploy

#8684 Support unlimited max automatic token associations in web3
  hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/RecordFile.java
  hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/accessor/AccountDatabaseAccessor.java
  hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/store/contract/HederaEvmStackedWorldStateUpdater.java
  hedera-mirror-web3/src/main/java/com/hedera/services/fees/calculation/utils/OpUsageCtxHelper.java
  hedera-mirror-web3/src/main/java/com/hedera/services/store/models/Account.java
  hedera-mirror-web3/src/main/java/com/hedera/services/store/tokens/HederaTokenStore.java
  hedera-mirror-web3/src/main/java/com/hedera/services/txns/crypto/AbstractAutoCreationLogic.java
  hedera-mirror-web3/src/main/java/com/hedera/services/utils/BitPackUtils.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/store/accessor/AccountDatabaseAccessorTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/store/contract/HederaEvmWorldStateTest.java
  hedera-mirror-web3/src/test/java/com/hedera/services/fees/calculation/utils/OpUsageCtxHelperTest.java
  hedera-mirror-web3/src/test/java/com/hedera/services/ledger/TransferLogicTest.java
  hedera-mirror-web3/src/test/java/com/hedera/services/store/models/AccountTest.java
  hedera-mirror-web3/src/test/java/com/hedera/services/store/models/TokenRelationshipTest.java
  hedera-mirror-web3/src/test/java/com/hedera/services/store/models/TokenTest.java
  hedera-mirror-web3/src/test/java/com/hedera/services/store/tokens/HederaTokenStoreTest.java
  hedera-mirror-web3/src/test/java/com/hedera/services/txn/token/DissociateLogicTest.java
  hedera-mirror-web3/src/test/java/com/hedera/services/txns/crypto/AutoCreationLogicTest.java
  hedera-mirror-web3/src/test/java/com/hedera/services/utils/BitPackUtilsTest.java
Labels: enhancement, web3

#8722 Support multiple namespaces for auto deployment
  .github/workflows/deploy.yaml
  docs/checklist/release.md
Labels: bug, github_actions

#8723 Route testnet traffic to testnet-eu
  clusters/testnet-na/testnet/helmrelease.yaml
Labels: enhancement, deploy

#8683 Add support for TokenReject transaction
  build.gradle.kts
  buildSrc/src/main/kotlin/java-conventions.gradle.kts
  hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/TransactionType.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/NodeCreateTransactionHandler.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/NodeDeleteTransactionHandler.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/NodeUpdateTransactionHandler.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenRejectTransactionHandler.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/PubSubMessageTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerTokenTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenRejectTransactionHandlerTest.java
  hedera-mirror-importer/src/test/resources/data/pubsub-messages.txt
  hedera-mirror-rest/api/v1/openapi.yml
  hedera-mirror-rest/model/transactionResult.js
  hedera-mirror-rest/model/transactionType.js
  hedera-mirror-rosetta/app/domain/types/constants.go
  hedera-mirror-rosetta/go.mod
  hedera-mirror-rosetta/go.sum
Labels: enhancement, parser

#8727 Automate staging mainnet-citus deploy
  clusters/mainnet-eu/flux-system/alert-slack.yaml
  clusters/mainnet-eu/flux-system/kustomization.yaml
  clusters/mainnet-eu/flux-system/provider-slack.yaml
  clusters/mainnet-na/flux-system/alert-github-dispatch.yaml
  clusters/mainnet-na/flux-system/alert-slack.yaml
  clusters/mainnet-na/flux-system/kustomization.yaml
  clusters/mainnet-na/flux-system/provider-slack.yaml
  clusters/mainnet-staging-na/flux-system/alert-github-dispatch.yaml
  clusters/mainnet-staging-na/flux-system/alert-slack.yaml
  clusters/mainnet-staging-na/flux-system/kustomization.yaml
  clusters/mainnet-staging-na/flux-system/provider-github-dispatch.yaml
  clusters/mainnet-staging-na/flux-system/provider-slack.yaml
  clusters/mainnet-staging-na/flux-system/sealed-secret-github-dispatch.yaml
  clusters/preprod/flux-system/alert-github-dispatch-performance.yaml
  clusters/preprod/flux-system/kustomization.yaml
  clusters/previewnet/flux-system/alert-github-dispatch.yaml
  clusters/previewnet/flux-system/alert-slack.yaml
  clusters/previewnet/flux-system/kustomization.yaml
  clusters/previewnet/flux-system/provider-slack.yaml
  clusters/testnet-eu/flux-system/alert-slack.yaml
  clusters/testnet-eu/flux-system/kustomization.yaml
  clusters/testnet-eu/flux-system/provider-slack.yaml
  clusters/testnet-na/flux-system/alert-github-dispatch.yaml
  clusters/testnet-na/flux-system/alert-slack.yaml
  clusters/testnet-na/flux-system/kustomization.yaml
  clusters/testnet-na/flux-system/provider-slack.yaml
Labels: enhancement, deploy

#8729 Fix yq install in deploy workflow
  .github/workflows/deploy.yaml
Labels: bug, github_actions

#8731 Remove stateproof alpha from OpenAPI
  hedera-mirror-rest/api/v1/openapi.yml
Labels: enhancement, rest

#8732 Update protobuf to 0.52 GA version
  build.gradle.kts
  buildSrc/src/main/kotlin/java-conventions.gradle.kts
  hedera-mirror-rest/model/transactionResult.js
Labels: enhancement, dependencies

#8736 Increase prometheus default memory limits to 4GB
  charts/hedera-mirror-common/values.yaml
Labels: bug

#8735 Reorder monitor helm test
  charts/hedera-mirror-rest/templates/monitor/tests/pod.yaml
  charts/hedera-mirror-rest/values.yaml
Labels: bug, test, monitor

#8737 Increase prometheus default memory limits to 4GB (0.109)
  charts/hedera-mirror-common/values.yaml
Labels: bug

#8739 Reorder monitor helm test (0.109)
  charts/hedera-mirror-rest/templates/monitor/tests/pod.yaml
  charts/hedera-mirror-rest/values.yaml
Labels: bug, test, monitor

#8741 Fix automated deployment PR title
  .github/workflows/deploy.yaml
Labels: bug, github_actions

#8744 Deploy 0.109.0-rc1 to performance v1 and v2.
  clusters/preprod/common/helmrelease.yaml
  clusters/preprod/performance-citus/helmrelease.yaml
  clusters/preprod/performance/helmrelease.yaml
Labels: enhancement, process, deploy

#8745 Deploy 0.109.0-rc1 to mainnet-staging-na.
  clusters/mainnet-staging-na/common/helmrelease.yaml
  clusters/mainnet-staging-na/mainnet-citus/helmrelease.yaml
  clusters/mainnet-staging-na/mainnet/helmrelease.yaml
Labels: process

#8743 Fix NullPointerException when from field is null on contract create
  hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/MirrorEvmTxProcessorImpl.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/controller/ContractControllerTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/contracts/execution/MirrorEvmTxProcessorTest.java
Labels: bug, web3

#8747 Deploy v0.108.0 to mainnet-na
  clusters/mainnet-na/common/helmrelease.yaml
  clusters/mainnet-na/mainnet/helmrelease.yaml
Labels: enhancement, deploy

#8749 Deploy v0.108.0 to mainnet-eu
  clusters/mainnet-eu/common/helmrelease.yaml
  clusters/mainnet-eu/mainnet/helmrelease.yaml
Labels: enhancement, deploy

#8751 Fix yq install in deploy branch
  .github/workflows/deploy.yaml
Labels: bug, process, github_actions

#8756 Bump Gradle from 8.6 to 8.9
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: dependencies

#8755 prepare single coordinator read test
  clusters/mainnet-staging-na/mainnet-citus/helmrelease.yaml
Labels: enhancement, deploy

#8650 Refactor the way contract action index is tracked in `OpcodeTracer`
  hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/common/ContractCallContext.java
  hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/convert/BytesDecoder.java
  hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/AbstractEvmMessageCallProcessor.java
  hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/traceability/OpcodeTracer.java
  hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/validation/HexValidator.java
  hedera-mirror-web3/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/HederaOperationTracer.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/convert/BytesDecoderTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/contracts/execution/MirrorEvmMessageCallProcessorBaseTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/contracts/execution/MirrorEvmMessageCallProcessorTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/contracts/execution/traceability/OpcodeTracerTest.java
Labels: enhancement, web3, limechain

#8746 Optimize transaction_hash to support querying by the 32-byte prefix
  hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/EthereumTransaction.java
  hedera-mirror-common/src/test/java/com/hedera/mirror/common/domain/DomainBuilder.java
  hedera-mirror-common/src/test/java/com/hedera/mirror/common/domain/transaction/EthereumTransactionTest.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/exception/InvalidConfigurationException.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/BackfillTransactionHashMigration.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListener.java
  hedera-mirror-importer/src/main/resources/application.yml
  hedera-mirror-importer/src/main/resources/db/migration/v1/V1.98.0__adjust_transaction_hash_index.sql
  hedera-mirror-importer/src/main/resources/db/migration/v2/V2.3.0__adjust_transaction_hash_index.sql
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/TestUtils.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/BackfillTransactionHashMigrationTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/sql/SqlEntityListenerTest.java
  hedera-mirror-rest/__tests__/integration/transactionHash.test.js
  hedera-mirror-rest/__tests__/integrationDomainOps.js
  hedera-mirror-rest/__tests__/specs/transactions/{id}/no-params.json
  hedera-mirror-rest/__tests__/transactionHash.test.js
  hedera-mirror-rest/constants.js
  hedera-mirror-rest/transactionHash.js
  hedera-mirror-rest/transactions.js
Labels: enhancement, database

#8760 Enable remaining services on mainnet-citus
  clusters/mainnet-eu/mainnet-citus/helmrelease.yaml
Labels: enhancement, deploy

#8761 disable monitor mainnet-na
  clusters/mainnet-na/mainnet/helmrelease.yaml
Labels: enhancement, deploy

#8764 enable monitor in mainnet-na
  clusters/mainnet-na/mainnet/helmrelease.yaml
Labels: enhancement, deploy

#8783 Re-enable testnet-na
  clusters/testnet-na/testnet/helmrelease.yaml
Labels: enhancement, deploy

#8730 Modifying dynamic address book design to add admin_key and node table.
  docs/design/dynamic-addressbook.md
Labels: enhancement, design

#8681 Dynamic address book mirror node implementation
  docs/configuration.md
  docs/design/dynamic-addressbook.md
  hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/addressbook/AddressBookServiceEndpoint.java
  hedera-mirror-common/src/test/java/com/hedera/mirror/common/domain/DomainBuilder.java
  hedera-mirror-graphql/src/main/resources/graphql/common.graphqls
  hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/controller/NetworkController.java
  hedera-mirror-grpc/src/test/java/com/hedera/mirror/grpc/controller/NetworkControllerTest.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityProperties.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/NodeCreateTransactionHandler.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/NodeDeleteTransactionHandler.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/NodeUpdateTransactionHandler.java
  hedera-mirror-importer/src/main/resources/db/migration/v1/V1.98.1__add_domain_name.sql
  hedera-mirror-importer/src/main/resources/db/migration/v2/V2.3.1__add_domain_name.sql
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/AddAddressBookServiceEndpointsMigrationTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/MissingAddressBooksMigrationTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerNodeTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/NodeCreateTransactionHandlerTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/NodeDeleteTransactionHandlerTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/NodeUpdateTransactionHandlerTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/repository/AddressBookServiceEndpointRepositoryTest.java
  hedera-mirror-rest/__tests__/integrationDomainOps.js
  hedera-mirror-rest/__tests__/service/networkNodeService.test.js
  hedera-mirror-rest/__tests__/specs/network/nodes/all-params.json
  hedera-mirror-rest/__tests__/specs/network/nodes/file-101-args.json
  hedera-mirror-rest/__tests__/specs/network/nodes/max-limit.json
  hedera-mirror-rest/__tests__/specs/network/nodes/no-params.json
  hedera-mirror-rest/__tests__/specs/network/nodes/node-range.json
  hedera-mirror-rest/api/v1/openapi.yml
  hedera-mirror-rest/model/addressBookServiceEndpoint.js
  hedera-mirror-rest/service/networkNodeService.js
  hedera-mirror-rest/viewmodel/addressBookServiceEndpointViewModel.js
Labels: enhancement, parser

#8798 Update Redis IP and AUTH string for dev env
  clusters/preprod/dev/sealed-secret.yaml
Labels: deploy

#8800 Set web3 network to OTHER in stagings
  clusters/preprod/staging-lg/helmrelease.yaml
  clusters/preprod/staging-sm/helmrelease.yaml
Labels: deploy

#8806 Enable acceptance tests in dev
  clusters/preprod/dev/helmrelease.yaml
Labels: deploy

#8803 Add a `Deployments` section to the release notes
  .github/dependabot.yml
  .github/release-notes.yml
  .github/release.yml
  hedera-mirror-rest/monitoring/README.md
Labels: enhancement, process

#8822 Enable testnet-eu testnet API components
  clusters/testnet-eu/testnet-citus/helmrelease.yaml
  clusters/testnet-eu/testnet/helmrelease.yaml
Labels: deploy

#8826 Disable stateproof check in dev and integration-docker
  clusters/preprod/dev/helmrelease.yaml
  clusters/preprod/integration-docker/helmrelease.yaml
Labels: deploy

#8805 Fix Initial address book bootstrap failure
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java
Labels: bug, regression, parser

#8825 Optimize accounts rest api to avoid full entity_stake index scan
  hedera-mirror-rest/accounts.js
  hedera-mirror-rest/package-lock.json
  hedera-mirror-rest/package.json
  hedera-mirror-rest/utils.js
Labels: bug, performance, rest

#8824 Fix potential exception with TokenRejectHandler tokenIds
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenRejectTransactionHandler.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerTokenTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/transactionhandler/TokenRejectTransactionHandlerTest.java
Labels: bug, parser

#8846 Deploy 0.109.0 to mainnet-na
  clusters/mainnet-na/common/helmrelease.yaml
  clusters/mainnet-na/mainnet/helmrelease.yaml
Labels: deploy

#8847 Update unlimited associations proto version to 0.53 in web3
  hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/transaction/RecordFile.java
  hedera-mirror-web3/src/main/java/com/hedera/services/txns/crypto/AbstractAutoCreationLogic.java
  hedera-mirror-web3/src/test/java/com/hedera/services/txns/crypto/AutoCreationLogicTest.java
Labels: enhancement, web3

#8841 Change Citus coordinator replication mode to sync-all
  charts/hedera-mirror/templates/stackgres/stackgres-cluster.yaml
  charts/hedera-mirror/values.yaml
Labels: bug, database

#8848 Add the web3j-gradle-plugin
  buildSrc/build.gradle.kts
  hedera-mirror-web3/build.gradle.kts
  hedera-mirror-web3/src/test/solidity/HederaResponseCodes.sol
  hedera-mirror-web3/src/test/solidity/HederaTokenService.sol
  hedera-mirror-web3/src/test/solidity/IHederaTokenService.sol
  hedera-mirror-web3/src/test/solidity/PrecompileTestContract.sol
Labels: enhancement, web3

#8851 Fix address book bootstrap failing with null `ip_address_v4`
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImpl.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/addressbook/AddressBookServiceImplTest.java
Labels: bug, regression, parser

#8789 Add token name query parameter to `/api/v1/tokens`
  charts/hedera-mirror/templates/configmap-init.yaml
  charts/hedera-mirror/templates/secret-passwords.yaml
  charts/hedera-mirror/values.yaml
  docs/database/README.md
  hedera-mirror-common/src/test/resources/init.sql
  hedera-mirror-importer/src/main/resources/db/migration/v1/V1.98.2__token_name_index.sql
  hedera-mirror-importer/src/main/resources/db/migration/v2/V2.3.2__token_name_index.sql
  hedera-mirror-importer/src/main/resources/db/scripts/init.sh
  hedera-mirror-importer/src/main/resources/db/scripts/v2/migration.sh
  hedera-mirror-rest/__tests__/specs/tokens/invalid-query-params.json
  hedera-mirror-rest/__tests__/specs/tokens/name.json
  hedera-mirror-rest/__tests__/utils.test.js
  hedera-mirror-rest/api/v1/openapi.yml
  hedera-mirror-rest/constants.js
  hedera-mirror-rest/tokens.js
  hedera-mirror-rest/utils.js
  hedera-mirror-rosetta/container/entrypoint.sh
  hedera-mirror-test/k6/README.md
  hedera-mirror-test/k6/src/rest/libex/parameters.js
  hedera-mirror-test/k6/src/rest/test/index.js
  hedera-mirror-test/k6/src/rest/test/tokensName.js
Labels: enhancement, rest, database, hts

#8852 Fix case sensitive query parameters
  hedera-mirror-rest/__tests__/specs/contracts/results/logs/pagination-index-timestamp-range.json
  hedera-mirror-rest/__tests__/specs/transactions/all-params.json
  hedera-mirror-rest/__tests__/utils.test.js
  hedera-mirror-rest/middleware/requestHandler.js
  hedera-mirror-rest/utils.js
Labels: bug, rest

#8860 Deploy 0.110.0-rc1 to mainnet-staging-na.
  clusters/mainnet-staging-na/common/helmrelease.yaml
  clusters/mainnet-staging-na/mainnet-citus/helmrelease.yaml
  clusters/mainnet-staging-na/mainnet/helmrelease.yaml
Labels: deploy

#8863 configure new k6 test
  clusters/mainnet-staging-na/common/helmrelease.yaml
Labels: deploy

#8866 Fix Config Hierarchy
  clusters/mainnet-staging-na/mainnet-citus/helmrelease.yaml
Labels: deploy

#8853 feat: Add TestWeb3jService
  hedera-mirror-web3/build.gradle.kts
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/web3j/TestWeb3jService.java
Labels: test, web3

#8855 Add canonical test scenarios to `RecordFileParserPerformanceTest`
  docs/configuration.md
  hedera-mirror-importer/build.gradle.kts
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/downloader/provider/LocalStreamFileProvider.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/ErrataMigrationTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordFileBuilder.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/domain/RecordItemBuilder.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/ParserPerformanceProperties.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/RecordFileParserIntegrationTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/RecordFileParserPerformanceTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerContractTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerCryptoTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerEthereumTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerFreezeTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerNodeTest.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListenerTokenTest.java
  hedera-mirror-importer/src/test/resources/config/application.yml
  hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/controller/AllowancesControllerTest.java
Labels: enhancement, performance, test, parser

#8875 Enabling persisting node transactions data
  docs/configuration.md
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityProperties.java
Labels: enhancement

#8872 Return no Result Instead of 404 For Accounts Not Matched by Query
  hedera-mirror-rest/__tests__/service/__snapshots__/entityService.test.js.snap
  hedera-mirror-rest/__tests__/service/entityService.test.js
  hedera-mirror-rest/__tests__/specs/balances/invalid-param-values.json
  hedera-mirror-rest/__tests__/specs/balances/multiple-ids.json
  hedera-mirror-rest/balances.js
  hedera-mirror-rest/service/entityService.js
Labels: bug, rest

#8877 remove full page write settings
  clusters/preprod/performance-citus/helmrelease.yaml
Labels: deploy

#8879 Return no Result Instead of 404 For Accounts Not Matched by Query (0.110)
  hedera-mirror-rest/__tests__/service/__snapshots__/entityService.test.js.snap
  hedera-mirror-rest/__tests__/service/entityService.test.js
  hedera-mirror-rest/__tests__/specs/balances/invalid-param-values.json
  hedera-mirror-rest/__tests__/specs/balances/multiple-ids.json
  hedera-mirror-rest/balances.js
  hedera-mirror-rest/service/entityService.js
Labels: bug, rest

#8881 Enabling persisting node transactions data (#8875)
  docs/configuration.md
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityProperties.java
Labels: enhancement

#8880 Return no Result Instead of 404 For Accounts Not Matched by Query (0.109)
  hedera-mirror-rest/__tests__/service/__snapshots__/entityService.test.js.snap
  hedera-mirror-rest/__tests__/service/entityService.test.js
  hedera-mirror-rest/__tests__/specs/balances/invalid-param-values.json
  hedera-mirror-rest/__tests__/specs/balances/multiple-ids.json
  hedera-mirror-rest/balances.js
  hedera-mirror-rest/service/entityService.js
Labels: bug, rest

#8900 Downgrade go btcd btsec to v2.3.3
  hedera-mirror-rosetta/go.mod
  hedera-mirror-rosetta/go.sum
Labels: bug, dependencies, rosetta

#8897 Fix contracts results by hash false alert
  hedera-mirror-rest/monitoring/contracts_tests.js
Labels: bug, monitor

#8901 Fix contracts results by hash false alert (0.109)
  hedera-mirror-rest/monitoring/contracts_tests.js
Labels: bug, monitor

#8902 Fix contracts results by hash false alert (0.110)
  hedera-mirror-rest/monitoring/contracts_tests.js
Labels: bug, monitor

#8898 adjust full_page_write postgres setting
  charts/hedera-mirror/values.yaml
Labels: bug, database

#8870 HIP-540 Update REST API to return correct value for empty KeyLists
  hedera-mirror-rest/__tests__/specs/tokens/{id}/custom-fees.json
  hedera-mirror-rest/__tests__/utils.test.js
  hedera-mirror-rest/utils.js
Labels: enhancement, rest, hts

#8910 Conditionally create temp tables
  hedera-mirror-importer/src/main/resources/db/migration/common/R__01_temp_tables.sql
  hedera-mirror-importer/src/main/resources/db/migration/v2/R__02_temp_table_distribution.sql
Labels: enhancement, parser

#8911 Drop dissociate_token_transfer Temp Table Before Re-creating
  hedera-mirror-importer/src/main/resources/db/migration/common/R__01_temp_tables.sql
Labels: regression, database
