Repository hiero-ledger/hiero-mirror-node, pull requests merged in 2024-04, with the labels that each got.

#8002 Revert org.owasp:dependency-check-gradle from 9.1.0 to 8.4.3
  buildSrc/build.gradle.kts
Labels: dependencies

#7981 Add pause and unpause missing validations
  hedera-mirror-web3/src/main/java/com/hedera/services/store/models/Token.java
  hedera-mirror-web3/src/main/java/com/hedera/services/txn/token/FreezeLogic.java
  hedera-mirror-web3/src/main/java/com/hedera/services/txn/token/PauseLogic.java
  hedera-mirror-web3/src/main/java/com/hedera/services/txn/token/UnfreezeLogic.java
  hedera-mirror-web3/src/main/java/com/hedera/services/txn/token/UnpauseLogic.java
  hedera-mirror-web3/src/test/java/com/hedera/services/store/models/TokenTest.java
  hedera-mirror-web3/src/test/java/com/hedera/services/store/tokens/HederaTokenStoreTest.java
  hedera-mirror-web3/src/test/java/com/hedera/services/txn/token/PauseLogicTest.java
  hedera-mirror-web3/src/test/java/com/hedera/services/txn/token/UnpauseLogicTest.java
Labels: enhancement, web3, limechain

#8005 Fix Citus Init Script Failure
  charts/hedera-mirror/templates/secret-passwords.yaml
Labels: parser, database

#7881 Add a ZFS dashboard and alerts
  charts/hedera-mirror-common/dashboards/zfs.json
  charts/hedera-mirror-common/templates/prometheusrule.yaml
  charts/hedera-mirror-common/values.yaml
  charts/hedera-mirror/templates/stackgres/stackgres-cluster.yaml
  charts/hedera-mirror/values.yaml
  docs/database/zfs.md
Labels: enhancement, process

#8007 Update testnet-eu to 0.101.0
  clusters/testnet-eu/common/helmrelease.yaml
  clusters/testnet-eu/testnet/helmrelease.yaml
Labels: process

#8006 Add an importer duration metric
  docs/checklist/feature.md
  docs/configuration.md
  docs/importer/README.md
  hedera-mirror-common/src/test/java/com/hedera/mirror/common/domain/DomainBuilder.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/StreamFilename.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/AbstractParserProperties.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/AbstractStreamFileParser.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/AccountBalanceFileParser.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/balance/BalanceParserProperties.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/RecordFileParser.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/historicalbalance/HistoricalBalanceService.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/balance/CsvBalanceFileReader.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/balance/ProtoBalanceFileReader.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/record/AbstractPreV5RecordFileReader.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/record/ProtoRecordFileReader.java
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/reader/record/RecordFileReaderImplV5.java
  hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/parser/record/entity/AbstractEntityRecordItemListenerTest.java
Labels: enhancement, process

#7984 Fix address(this) resolution when mirror address is passed in the call
  hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/evm/contracts/execution/MirrorEvmTxProcessorImpl.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/evm/contracts/execution/MirrorEvmTxProcessorTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallDynamicCallsTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallEvmCodesTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallTestSetup.java
  hedera-mirror-web3/src/test/resources/contracts/DynamicEthCalls/DynamicEthCalls.bin
  hedera-mirror-web3/src/test/resources/contracts/DynamicEthCalls/DynamicEthCalls.json
  hedera-mirror-web3/src/test/resources/contracts/DynamicEthCalls/DynamicEthCalls.sol
  hedera-mirror-web3/src/test/resources/contracts/TestContractAddress/TestAddressThis.bin
  hedera-mirror-web3/src/test/resources/contracts/TestContractAddress/TestAddressThis.json
  hedera-mirror-web3/src/test/resources/contracts/TestContractAddress/TestAddressThis.sol
  hedera-mirror-web3/src/test/resources/contracts/TestContractAddress/TestAddressThisInit.bin
Labels: bug, web3, limechain

#8011 Update mainnet staging to 0.102.0-rc1
  clusters/mainnet-staging-na/common/helmrelease.yaml
  clusters/mainnet-staging-na/mainnet/helmrelease.yaml
Labels: process

#8018 Update performance to 0.102.0-rc1
  clusters/preprod/common/helmrelease.yaml
  clusters/preprod/performance-citus/helmrelease.yaml
  clusters/preprod/performance/helmrelease.yaml
Labels: process

#8013 Add KYC key validations for grant and revoke logics
  hedera-mirror-web3/src/main/java/com/hedera/services/store/models/TokenRelationship.java
  hedera-mirror-web3/src/main/java/com/hedera/services/store/tokens/HederaTokenStore.java
  hedera-mirror-web3/src/main/java/com/hedera/services/txn/token/GrantKycLogic.java
  hedera-mirror-web3/src/main/java/com/hedera/services/txn/token/RevokeKycLogic.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServicePrecompileTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallTestSetup.java
  hedera-mirror-web3/src/test/java/com/hedera/services/store/models/TokenRelationshipTest.java
  hedera-mirror-web3/src/test/java/com/hedera/services/store/tokens/HederaTokenStoreTest.java
  hedera-mirror-web3/src/test/java/com/hedera/services/txn/token/GrantKycLogicTest.java
  hedera-mirror-web3/src/test/java/com/hedera/services/txn/token/RevokeKycLogicTest.java
Labels: enhancement, web3, limechain

#8016 Fix issue when running RecordFileParserPerformanceTest
  buildSrc/src/main/kotlin/java-conventions.gradle.kts
Labels: bug, test

#8020 Bump Go from 1.21.3 to 1.22.2
  .github/workflows/security.yml
  buildSrc/src/main/kotlin/plugin/go/GoSetup.kt
  hedera-mirror-rosetta/Dockerfile
  hedera-mirror-rosetta/build.gradle.kts
  hedera-mirror-rosetta/go.mod
Labels: dependencies, go

#8024 Update README.md
  README.md
Labels: bug, documentation

#8022 Fix balance opcode for 0.0.999 acceptance test
  hedera-mirror-test/src/test/resources/features/contract/equivalence.feature
Labels: enhancement, web3, limechain

#8049 Prepare mainnet-eu for 0.101.0
  clusters/mainnet-eu/common/helmrelease.yaml
  clusters/mainnet-eu/mainnet/helmrelease.yaml
Labels: enhancement, process

#8050 Prepare mainnet-na for 0.101.0
  clusters/mainnet-na/common/helmrelease.yaml
  clusters/mainnet-na/mainnet/helmrelease.yaml
Labels: enhancement, process

#8030 Convert acceptances tests from WebClient to RestClient
  hedera-mirror-test/README.md
  hedera-mirror-test/build.gradle.kts
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AccountClient.java
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/MirrorNodeClient.java
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/StartupProbe.java
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/config/AcceptanceTestProperties.java
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/config/ClientConfiguration.java
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/config/RestProperties.java
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/config/Web3Properties.java
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/AbstractEstimateFeature.java
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/AbstractFeature.java
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/AccountFeature.java
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/ContractFeature.java
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EquivalenceFeature.java
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/HistoricalFeature.java
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/PrecompileContractFeature.java
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/RetryAsserts.java
Labels: enhancement, technical debt, test

#8065 Suppress NoSuchKey error in REST API
  README.md
  buildSrc/src/main/kotlin/spring-conventions.gradle.kts
  docs/contributing.md
  hedera-mirror-common/build.gradle.kts
  hedera-mirror-importer/build.gradle.kts
  hedera-mirror-rest/stateproof.js
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/StartupProbe.java
Labels: bug, rest

#8069 Increase max header size
  buildSrc/src/main/kotlin/javascript-conventions.gradle.kts
  charts/hedera-mirror-web3/values.yaml
  hedera-mirror-graphql/src/main/resources/application.yml
  hedera-mirror-grpc/src/main/resources/application.yml
  hedera-mirror-rest-java/src/main/resources/application.yml
  hedera-mirror-web3/src/main/resources/application.yml
Labels: bug, web3

#8059 Expose HIPs-646/657/765 token metadata in REST API
  hedera-mirror-rest/__tests__/integrationDomainOps.js
  hedera-mirror-rest/__tests__/specs/tokens/account-id.json
  hedera-mirror-rest/__tests__/specs/tokens/all-params.json
  hedera-mirror-rest/__tests__/specs/tokens/all-token-types.json
  hedera-mirror-rest/__tests__/specs/tokens/fungible-common-token-types.json
  hedera-mirror-rest/__tests__/specs/tokens/limit.json
  hedera-mirror-rest/__tests__/specs/tokens/multiple-ids.json
  hedera-mirror-rest/__tests__/specs/tokens/no-params.json
  hedera-mirror-rest/__tests__/specs/tokens/non-fungible-unique-token-types.json
  hedera-mirror-rest/__tests__/specs/tokens/publickey.json
  hedera-mirror-rest/__tests__/specs/tokens/token-range.json
  hedera-mirror-rest/__tests__/specs/tokens/{id}/custom-fees.json
  hedera-mirror-rest/__tests__/specs/tokens/{id}/historical-custom-fees.json
  hedera-mirror-rest/__tests__/specs/tokens/{id}/nft-custom-fees.json
  hedera-mirror-rest/__tests__/specs/tokens/{id}/no-params.json
  hedera-mirror-rest/__tests__/specs/tokens/{id}/non-fungible-unique-token-types.json
  hedera-mirror-rest/__tests__/tokens.test.js
  hedera-mirror-rest/api/v1/openapi.yml
  hedera-mirror-rest/model/token.js
  hedera-mirror-rest/tokens.js
Labels: enhancement, rest

#8076 Handle null and empty token metadata, and adjust REST API spec tests accordingly
  hedera-mirror-rest/__tests__/integrationDomainOps.js
  hedera-mirror-rest/__tests__/specs/tokens/account-id.json
  hedera-mirror-rest/__tests__/specs/tokens/all-params.json
  hedera-mirror-rest/__tests__/specs/tokens/all-token-types.json
  hedera-mirror-rest/__tests__/specs/tokens/fungible-common-token-types.json
  hedera-mirror-rest/__tests__/specs/tokens/limit.json
  hedera-mirror-rest/__tests__/specs/tokens/multiple-ids.json
  hedera-mirror-rest/__tests__/specs/tokens/non-fungible-unique-token-types.json
  hedera-mirror-rest/__tests__/specs/tokens/publickey.json
  hedera-mirror-rest/__tests__/specs/tokens/{id}/custom-fees.json
  hedera-mirror-rest/__tests__/specs/tokens/{id}/historical-custom-fees.json
  hedera-mirror-rest/__tests__/specs/tokens/{id}/nft-custom-fees.json
  hedera-mirror-rest/__tests__/specs/tokens/{id}/non-fungible-unique-token-types.json
  hedera-mirror-rest/__tests__/tokens.test.js
  hedera-mirror-rest/constants.js
  hedera-mirror-rest/tokens.js
Labels: bug, test, rest

#8026 Support EVM address and alias lookup in NFT allowance REST API
  buildSrc/src/main/kotlin/java-conventions.gradle.kts
  docs/configuration.md
  hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/RestJavaProperties.java
  hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/cache/CacheProperties.java
  hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/EntityIdAliasParameter.java
  hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/EntityIdEvmAddressParameter.java
  hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/EntityIdNumParameter.java
  hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/EntityIdParameter.java
  hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/ParameterNames.java
  hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/SpringApplicationContext.java
  hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/Utils.java
  hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/config/CacheConfiguration.java
  hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/controller/AllowancesController.java
  hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/controller/ExceptionControllerAdvice.java
  hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/controller/GenericControllerAdvice.java
  hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/converter/OrderConverter.java
  hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/mapper/CommonMapper.java
  hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/repository/EntityRepository.java
  hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/EntityService.java
  hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/EntityServiceImpl.java
  hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/NftAllowanceServiceImpl.java
  hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/common/EntityIdParameterTest.java
  hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/common/UtilsTest.java
  hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/controller/AllowancesControllerIntegrationTest.java
  hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/mapper/CommonMapperTest.java
  hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/mapper/NftAllowanceMapperTest.java
  hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/repository/EntityRepositoryTest.java
  hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/service/EntityServiceTest.java
  hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/service/NftAllowanceServiceTest.java
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
  hedera-mirror-web3/src/test/java/com/hedera/services/txn/token/GrantKycLogicTest.java
  hedera-mirror-web3/src/test/java/com/hedera/services/txn/token/RevokeKycLogicTest.java
Labels: enhancement, rest-java

#8080 Add an importer graph to dashboard
  build.gradle.kts
  buildSrc/src/main/kotlin/javascript-conventions.gradle.kts
  charts/hedera-mirror-common/dashboards/hedera-mirror-importer.json
Labels: enhancement, monitor

#8014 Fix flaky Rest test
  hedera-mirror-rest/__tests__/globalSetup.js
  hedera-mirror-rest/__tests__/globalTeardown.js
  hedera-mirror-rest/__tests__/integrationDbOps.js
  hedera-mirror-rest/jest.config.js
Labels: bug, test, rest

#8104 Fix REST Java fallback exception handling
  hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/EntityIdAliasParameter.java
  hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/EntityIdEvmAddressParameter.java
  hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/EntityIdNumParameter.java
  hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/controller/AllowancesController.java
  hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/controller/ExceptionControllerAdvice.java
  hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/controller/GenericControllerAdvice.java
  hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/controller/AllowancesControllerTest.java
Labels: bug, rest-java

#8073 Enable prometheus exporter and disable util stackgres sidecars
  charts/README.md
  charts/hedera-mirror-common/dashboards/hedera-mirror-importer.json
  charts/hedera-mirror/templates/stackgres/stackgres-cluster.yaml
  charts/hedera-mirror/values-prod.yaml
Labels: enhancement

#8107 Fix equivalence acceptance test regression
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EquivalenceFeature.java
Labels: bug, test, regression

#8110 Bump bouncy castle version to fix synk vulnerability
  build.gradle.kts
  hedera-mirror-web3/build.gradle.kts
Labels: security, dependencies

#8112 Prepare mainnet-na for 0.102.0
  clusters/mainnet-na/common/helmrelease.yaml
  clusters/mainnet-na/mainnet/helmrelease.yaml
Labels: enhancement, process

#8120 Fix chart install issue when applying migration v1.96.0
  charts/hedera-mirror/templates/configmap-init.yaml
Labels: bug, regression

#8121 Fix chart install issue when applying migration v1.96.0 (0.103)
  charts/hedera-mirror/templates/configmap-init.yaml
Labels: bug, regression

#8126 Add a Citus deploy to previewnet
  clusters/preprod/flux-system/alert-slack.yaml
  clusters/previewnet/flux-system/alert.yaml
  clusters/previewnet/previewnet-citus/helmrelease.yaml
  clusters/previewnet/previewnet-citus/helmrepository.yaml
  clusters/previewnet/previewnet-citus/namespace.yaml
  clusters/previewnet/previewnet-citus/sealed-secret.yaml
Labels: enhancement, process

#8130 Fix type conversion of `stackgres.postgresVersion`
  charts/hedera-mirror/templates/stackgres/stackgres-cluster.yaml
Labels: bug, process

#8131 Fix type conversion of `stackgres.postgresVersion` (0.103)
  charts/hedera-mirror/templates/stackgres/stackgres-cluster.yaml
Labels: bug, process

#8128 Remove numeric account entity ID existence check from NFT allowances API
  docs/configuration.md
  docs/rest-java/README.md
  hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/cache/CacheProperties.java
  hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/config/CacheConfiguration.java
  hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/repository/EntityRepository.java
  hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/EntityServiceImpl.java
  hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/controller/AllowancesControllerTest.java
  hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/repository/EntityRepositoryTest.java
  hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/service/EntityServiceTest.java
Labels: enhancement, rest-java

#8118 Unset restjava enable override in integration flux config
  clusters/preprod/integration/helmrelease.yaml
Labels: enhancement, rest-java

#8117 Enable rest java chart by default
  charts/README.md
  charts/hedera-mirror-rest-java/postman.json
  charts/hedera-mirror-rest-java/values.yaml
  charts/hedera-mirror/ci/v1-values.yaml
  charts/hedera-mirror/ci/v2-values.yaml
  charts/hedera-mirror/templates/NOTES.txt
  charts/hedera-mirror/values.yaml
  hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/controller/DummyController.java
  hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/EntityServiceImpl.java
  hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/controller/DummyControllerTest.java
Labels: enhancement, rest-java

#8021 Remove exception in TxnResourceUsageEstimator - usageGiven
  hedera-mirror-web3/src/main/java/com/hedera/services/fees/calculation/TxnResourceUsageEstimator.java
  hedera-mirror-web3/src/main/java/com/hedera/services/fees/calculation/UsageBasedFeeCalculator.java
  hedera-mirror-web3/src/main/java/com/hedera/services/fees/calculation/token/txns/TokenAssociateResourceUsage.java
  hedera-mirror-web3/src/main/java/com/hedera/services/fees/calculation/token/txns/TokenDeleteResourceUsage.java
  hedera-mirror-web3/src/main/java/com/hedera/services/fees/calculation/token/txns/TokenDissociateResourceUsage.java
  hedera-mirror-web3/src/main/java/com/hedera/services/fees/calculation/token/txns/TokenUpdateResourceUsage.java
  hedera-mirror-web3/src/test/java/com/hedera/services/fees/calculation/UsageBasedFeeCalculatorTest.java
Labels: enhancement, web3, limechain

#8141 Modify NftAllowance API to use repository layer filters
  build.gradle.kts
  docs/configuration.md
  hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/common/Filter.java
  hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/exception/MismatchedTypeException.java
  hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/repository/NftAllowanceRepository.java
  hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/repository/NftAllowanceRepositoryCustom.java
  hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/repository/NftAllowanceRepositoryCustomImpl.java
  hedera-mirror-rest-java/src/main/java/com/hedera/mirror/restjava/service/NftAllowanceServiceImpl.java
  hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/controller/AllowancesControllerTest.java
  hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/repository/EntityRepositoryTest.java
  hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/repository/NftAllowanceRepositoryTest.java
  hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/service/EntityServiceTest.java
  hedera-mirror-rest-java/src/test/java/com/hedera/mirror/restjava/service/NftAllowanceServiceTest.java
Labels: enhancement, nft

#8100 Adapt contract deploy to work for eth call
  hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/controller/ContractController.java
  hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/viewmodel/ContractCallRequest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/controller/ContractControllerTest.java
  hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServiceTest.java
Labels: bug, web3, limechain

#8167 Fix bats version in gcp marketplace release shell script
  charts/marketplace/gcp/release.sh
Labels: bug, process

#8162 Fix rest check state proof failing npm install in ci
  buildSrc/src/main/kotlin/javascript-conventions.gradle.kts
Labels: bug, test

#8170 Bump supertest from 6.3.4 to 7.0.0
  hedera-mirror-rest/package-lock.json
  hedera-mirror-rest/package.json
Labels: security, dependencies, javascript

#8171 specify limits for each stackgres container
  charts/hedera-mirror/values-prod.yaml
Labels: bug

#8047 ci: Apply best practices and standards to remaining workflows
  .github/workflows/charts.yml
  .github/workflows/cleanup.yml
  .github/workflows/gradle.yml
  .github/workflows/release-automation.yml
  .github/workflows/release-integration.yml
  .github/workflows/release-production.yml
  .github/workflows/rosetta.yml
  .github/workflows/security.yml
  .github/workflows/snyk-monitor.yml
  buildSrc/src/main/kotlin/java-conventions.gradle.kts
Labels: enhancement, process

#8175 Bump helm/kind-action from 1.9.0 to 1.10.0
  .github/workflows/charts.yml
Labels: dependencies, github_actions

#8179 ci: resolve release workflow failure due to missing charset and permissions
  .github/workflows/release-automation.yml
  .github/workflows/release-integration.yml
  .github/workflows/release-production.yml
Labels: bug, github_actions

#8184 ci: Update release engineering deploy job to include named steps
  .github/workflows/release-integration.yml
Labels: enhancement, github_actions

#8134 Speed up PostgreSQL to Citus migration
  charts/hedera-mirror/ci/v2-values.yaml
  docs/database/README.md
  hedera-mirror-importer/src/main/resources/db/scripts/v2/migration.config
  hedera-mirror-importer/src/main/resources/db/scripts/v2/migration.sh
Labels: enhancement, parser, database

#8187 Add a Redis cache to the REST API
  build.gradle.kts
  charts/hedera-mirror/templates/secret-redis.yaml
  charts/hedera-mirror/values.yaml
  docs/configuration.md
  hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResultServiceImpl.java
  hedera-mirror-rest/__tests__/application.yml
  hedera-mirror-rest/__tests__/cache.test.js
  hedera-mirror-rest/cache.js
  hedera-mirror-rest/config/application.yml
  hedera-mirror-rest/package-lock.json
  hedera-mirror-rest/package.json
  hedera-mirror-rest/transactions.js
Labels: enhancement, performance, rest

#8202 Add a Citus deployment to mainnet-staging
  clusters/mainnet-staging-na/common/helmrelease.yaml
  clusters/mainnet-staging-na/common/sealed-secret.yaml
  clusters/mainnet-staging-na/flux-system/alert.yaml
  clusters/mainnet-staging-na/mainnet-citus/helmrelease.yaml
  clusters/mainnet-staging-na/mainnet-citus/helmrepository.yaml
  clusters/mainnet-staging-na/mainnet-citus/namespace.yaml
  clusters/mainnet-staging-na/mainnet-citus/sealed-secret.yaml
Labels: enhancement, process

#8204 Fix integration deployment
  charts/hedera-mirror/templates/secret-redis.yaml
  charts/hedera-mirror/values.yaml
Labels: bug, regression, process

#8177 NFT allowances acceptance tests
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AccountClient.java
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/MirrorNodeClient.java
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/TokenClient.java
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/CallFeature.java
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimatePrecompileFeature.java
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/HistoricalFeature.java
  hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/TokenFeature.java
  hedera-mirror-test/src/test/resources/features/token/nftAllowance.feature
  hedera-mirror-test/src/test/resources/features/token/token.feature
Labels: enhancement, test, nft
